// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package metalperformanceshaders

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/mpsneuralnetwork"
	"github.com/deploymenttheory/go-bindings-macosplatform/internal/pureobjc"
)

// Apple documentation: https://developer.apple.com/documentation/metalperformanceshaders/mpscnncrosschannelnormalizationgradientnode
type MPSCNNCrossChannelNormalizationGradientNode struct {
	mpsneuralnetwork.MPSNNGradientFilterNode
}

var (
	_clsMPSCNNCrossChannelNormalizationGradientNode = _objcClass("MPSCNNCrossChannelNormalizationGradientNode")
	_mPSCNNCrossChannelNormalizationGradientNodeSelNodeWithSourceGradientSourceImageGradientStateKernelSize = objc.RegisterName("nodeWithSourceGradient:sourceImage:gradientState:kernelSize:")
	_mPSCNNCrossChannelNormalizationGradientNodeSelInitWithSourceGradientSourceImageGradientStateKernelSize = objc.RegisterName("initWithSourceGradient:sourceImage:gradientState:kernelSize:")
	_mPSCNNCrossChannelNormalizationGradientNodeSelKernelSize = objc.RegisterName("kernelSize")
)

func MPSCNNCrossChannelNormalizationGradientNodeFromID(id objc.ID) *MPSCNNCrossChannelNormalizationGradientNode {
	if id == 0 {
		return nil
	}
	o := &MPSCNNCrossChannelNormalizationGradientNode{}
	o.InitPtr(id)
	pureobjc.Track(o)
	return o
}

func MPSCNNCrossChannelNormalizationGradientNodeNodeWithSourceGradientSourceImageGradientStateKernelSize(sourceGradient *mpsneuralnetwork.MPSNNImageNode, sourceImage *mpsneuralnetwork.MPSNNImageNode, gradientState *mpsneuralnetwork.MPSNNGradientStateNode, kernelSize uint) *MPSCNNCrossChannelNormalizationGradientNode {
	_ret := objc.Send[objc.ID](objc.ID(_clsMPSCNNCrossChannelNormalizationGradientNode), _mPSCNNCrossChannelNormalizationGradientNodeSelNodeWithSourceGradientSourceImageGradientStateKernelSize, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr(), kernelSize)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSCNNCrossChannelNormalizationGradientNodeFromID(_ret)
}

func (o *MPSCNNCrossChannelNormalizationGradientNode) InitWithSourceGradientSourceImageGradientStateKernelSize(sourceGradient *mpsneuralnetwork.MPSNNImageNode, sourceImage *mpsneuralnetwork.MPSNNImageNode, gradientState *mpsneuralnetwork.MPSNNGradientStateNode, kernelSize uint) *MPSCNNCrossChannelNormalizationGradientNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _mPSCNNCrossChannelNormalizationGradientNodeSelInitWithSourceGradientSourceImageGradientStateKernelSize, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr(), kernelSize)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSCNNCrossChannelNormalizationGradientNodeFromID(_ret)
}

func (o *MPSCNNCrossChannelNormalizationGradientNode) KernelSize() uint {
	_ret := objc.Send[uint](o.Ptr(), _mPSCNNCrossChannelNormalizationGradientNodeSelKernelSize)
	return _ret
}

