// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package audiotoolbox

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/audiotoolbox"
	"github.com/ebitengine/purego/objc"
)

// ParameterTree wraps [raw.AUParameterTree] with a fluent Go API.
type ParameterTree struct {
	inner *raw.AUParameterTree
}

// Unwrap returns the underlying [raw.AUParameterTree].
func (x *ParameterTree) Unwrap() *raw.AUParameterTree { return x.inner }

// NewParameterTree creates a new [ParameterTree].
func NewParameterTree() *ParameterTree {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("AUParameterTree")), objc.RegisterName("new"))
	return &ParameterTree{inner: raw.AUParameterTreeFromID(_id)}
}

func (x *ParameterTree) asParameterGroup() *raw.AUParameterGroup { return &x.inner.AUParameterGroup }

func (x *ParameterTree) asParameterNode() *raw.AUParameterNode { return &x.inner.AUParameterGroup.AUParameterNode }

