// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package paravirtualizedgraphics

import (
	"unsafe"

	"github.com/ebitengine/purego"
)

// @const PGResumeErrorDomain The error domain for reporting errors in resume.
func PGResumeErrorDomain() uintptr {
	ptr, _ := purego.Dlsym(_paravirtualizedgraphicsLib, "PGResumeErrorDomain")
	return ptr
}

func ParavirtualizedGraphicsVersionNumber() float64 {
	ptr, _ := purego.Dlsym(_paravirtualizedgraphicsLib, "ParavirtualizedGraphicsVersionNumber")
	if ptr == 0 { return 0 }
	return *(*float64)(unsafe.Pointer(ptr))
}

func ParavirtualizedGraphicsVersionString() []unsafe.Pointer {
	ptr, _ := purego.Dlsym(_paravirtualizedgraphicsLib, "ParavirtualizedGraphicsVersionString")
	if ptr == 0 { return []unsafe.Pointer{} }
	return *(*[]unsafe.Pointer)(unsafe.Pointer(ptr))
}

