// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package screensaver

import (
	ebipurego "github.com/ebitengine/purego"
)

var _fnSSRandomFloatBetween func(float64, float64) float64

// SSRandomFloatBetween calls the ScreenSaver framework function SSRandomFloatBetween.
func SSRandomFloatBetween(a float64, b float64) float64 {
	_loadOnce.Do(_loadLibrary)
	if _fnSSRandomFloatBetween == nil {
		ebipurego.RegisterLibFunc(&_fnSSRandomFloatBetween, _lib, "SSRandomFloatBetween")
	}
	return _fnSSRandomFloatBetween(a, b)
}

var _fnSSRandomIntBetween func(int, int) int

// SSRandomIntBetween calls the ScreenSaver framework function SSRandomIntBetween.
func SSRandomIntBetween(a int, b int) int {
	_loadOnce.Do(_loadLibrary)
	if _fnSSRandomIntBetween == nil {
		ebipurego.RegisterLibFunc(&_fnSSRandomIntBetween, _lib, "SSRandomIntBetween")
	}
	return _fnSSRandomIntBetween(a, b)
}
