// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package scenekit

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/scenekit"
	"github.com/ebitengine/purego/objc"
)

// Capsule wraps [raw.SCNCapsule] with a fluent Go API.
type Capsule struct {
	inner *raw.SCNCapsule
}

// Unwrap returns the underlying [raw.SCNCapsule].
func (x *Capsule) Unwrap() *raw.SCNCapsule { return x.inner }

// NewCapsule creates a new [Capsule].
func NewCapsule() *Capsule {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("SCNCapsule")), objc.RegisterName("new"))
	return &Capsule{inner: raw.SCNCapsuleFromID(_id)}
}

// WithCapRadius sets the capRadius property and returns the receiver for chaining.
func (x *Capsule) WithCapRadius(capRadius float64) *Capsule {
	x.inner.SetCapRadius(capRadius)
	return x
}

// WithHeight sets the height property and returns the receiver for chaining.
func (x *Capsule) WithHeight(height float64) *Capsule {
	x.inner.SetHeight(height)
	return x
}

// WithRadialSegmentCount sets the radialSegmentCount property and returns the receiver for chaining.
func (x *Capsule) WithRadialSegmentCount(radialSegmentCount int) *Capsule {
	x.inner.SetRadialSegmentCount(radialSegmentCount)
	return x
}

// WithHeightSegmentCount sets the heightSegmentCount property and returns the receiver for chaining.
func (x *Capsule) WithHeightSegmentCount(heightSegmentCount int) *Capsule {
	x.inner.SetHeightSegmentCount(heightSegmentCount)
	return x
}

// WithCapSegmentCount sets the capSegmentCount property and returns the receiver for chaining.
func (x *Capsule) WithCapSegmentCount(capSegmentCount int) *Capsule {
	x.inner.SetCapSegmentCount(capSegmentCount)
	return x
}

func (x *Capsule) asGeometry() *raw.SCNGeometry { return &x.inner.SCNGeometry }

