// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package webkit

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/webkit"
	"github.com/ebitengine/purego/objc"
)

// WKFindConfiguration wraps [raw.WKFindConfiguration] with a fluent Go API.
type WKFindConfiguration struct {
	inner *raw.WKFindConfiguration
}

// Unwrap returns the underlying [raw.WKFindConfiguration].
func (x *WKFindConfiguration) Unwrap() *raw.WKFindConfiguration { return x.inner }

// NewWKFindConfiguration creates a new [WKFindConfiguration].
func NewWKFindConfiguration() *WKFindConfiguration {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("WKFindConfiguration")), objc.RegisterName("new"))
	return &WKFindConfiguration{inner: raw.WKFindConfigurationFromID(_id)}
}

// WithBackwards sets the backwards property and returns the receiver for chaining.
func (x *WKFindConfiguration) WithBackwards(backwards bool) *WKFindConfiguration {
	x.inner.SetBackwards(backwards)
	return x
}

// WithCaseSensitive sets the caseSensitive property and returns the receiver for chaining.
func (x *WKFindConfiguration) WithCaseSensitive(caseSensitive bool) *WKFindConfiguration {
	x.inner.SetCaseSensitive(caseSensitive)
	return x
}

// WithWraps sets the wraps property and returns the receiver for chaining.
func (x *WKFindConfiguration) WithWraps(wraps bool) *WKFindConfiguration {
	x.inner.SetWraps(wraps)
	return x
}

