// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package businesschat

import (
	"runtime"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
)

// OpenTranscriptIntentParameters open the chat transcript configured for a given business.
func OpenTranscriptIntentParameters(businessIdentifier string, intentParameters obj.Object) {
	defer runtime.KeepAlive(intentParameters)
	objc.Send[objc.ID](objc.ID(_class("BCChatAction")), objc.RegisterName("openTranscript:intentParameters:"), purego.NSString(businessIdentifier), objref.IDOf(intentParameters))
}
