// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package appkit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// A single dragged item within a dragging session.
//
// DraggingItem is an idiomatic wrapper over the Objective-C class NSDraggingItem.
type DraggingItem struct {
	objref.Handle
}

// DraggingItemFromID adopts an existing Objective-C object as a DraggingItem
// (nil for 0), retaining it and registering a release finalizer.
func DraggingItemFromID(id objc.ID) *DraggingItem {
	if id == 0 {
		return nil
	}
	x := &DraggingItem{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// draggingItemAdopt wraps an Objective-C object that this code just created as a
// DraggingItem (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func draggingItemAdopt(id objc.ID) *DraggingItem {
	if id == 0 {
		return nil
	}
	x := &DraggingItem{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *DraggingItem) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *DraggingItem) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *DraggingItem) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewDraggingItem creates a new DraggingItem.
func NewDraggingItem() *DraggingItem {
	_id := objc.Send[objc.ID](objc.ID(_class("NSDraggingItem")), objc.RegisterName("new"))
	return draggingItemAdopt(_id)
}

func (x *DraggingItem) Item() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("item"))
	return obj.Wrap(_r)
}

// ImageComponents returns the collection as a Go slice.
func (x *DraggingItem) ImageComponents() []*DraggingImageComponent {
	_arr := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("imageComponents"))
	return purego.NSArrayToSlice(_arr, func(_id objc.ID) *DraggingImageComponent { return DraggingImageComponentFromID(_id) })
}

// DraggingItemable is the interface implemented by [DraggingItem], for mocking and DI.
type DraggingItemable interface {
	obj.Object
	Item() obj.Object
	ImageComponents() []*DraggingImageComponent
}

var _ DraggingItemable = (*DraggingItem)(nil)
