// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package appkit

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/appkit"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/corefoundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/coreimage"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/quartzcore"
	"github.com/ebitengine/purego/objc"
	"unsafe"
)

// A text field that hides the typed text.
//
// SecureTextField wraps [raw.NSSecureTextField] with a fluent Go API.
type SecureTextField struct {
	inner *raw.NSSecureTextField
}

// Unwrap returns the underlying [raw.NSSecureTextField].
func (x *SecureTextField) Unwrap() *raw.NSSecureTextField { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *SecureTextField) ID() objc.ID { return x.inner.Ptr() }

// SecureTextFieldFromID adopts an existing object pointer as a SecureTextField (nil for 0).
func SecureTextFieldFromID(id objc.ID) *SecureTextField {
	if id == 0 {
		return nil
	}
	return &SecureTextField{inner: raw.NSSecureTextFieldFromID(id)}
}

// NewSecureTextField creates a new [SecureTextField].
func NewSecureTextField() *SecureTextField {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("NSSecureTextField")), objc.RegisterName("new"))
	return &SecureTextField{inner: raw.NSSecureTextFieldFromID(_id)}
}

// The string the text field displays when empty to help the user understand the text field’s purpose.
//
// WithPlaceholderString sets the placeholderString property and returns the receiver for chaining.
func (x *SecureTextField) WithPlaceholderString(placeholderString string) *SecureTextField {
	x.inner.NSTextField.SetPlaceholderString(foundation.NSStringStringWithUTF8String(placeholderString))
	return x
}

// The attributed string the text field displays when empty to help the user understand the text field’s purpose.
//
// WithPlaceholderAttributedString sets the placeholderAttributedString property and returns the receiver for chaining.
func (x *SecureTextField) WithPlaceholderAttributedString(placeholderAttributedString *foundation.NSAttributedString) *SecureTextField {
	x.inner.NSTextField.SetPlaceholderAttributedString(placeholderAttributedString)
	return x
}

// The color of the background the text field’s cell draws behind the text.
//
// WithBackgroundColor sets the backgroundColor property and returns the receiver for chaining.
func (x *SecureTextField) WithBackgroundColor(backgroundColor *Color) *SecureTextField {
	x.inner.NSTextField.SetBackgroundColor(backgroundColor.Unwrap())
	return x
}

// A Boolean value that controls whether the text field’s cell draws a background color behind the text.
//
// WithDrawsBackground sets the drawsBackground property and returns the receiver for chaining.
func (x *SecureTextField) WithDrawsBackground(drawsBackground bool) *SecureTextField {
	x.inner.NSTextField.SetDrawsBackground(drawsBackground)
	return x
}

// The color of the text field’s content.
//
// WithTextColor sets the textColor property and returns the receiver for chaining.
func (x *SecureTextField) WithTextColor(textColor *Color) *SecureTextField {
	x.inner.NSTextField.SetTextColor(textColor.Unwrap())
	return x
}

// A Boolean value that controls whether the text field draws a solid black border around its contents.
//
// WithBordered sets the bordered property and returns the receiver for chaining.
func (x *SecureTextField) WithBordered(bordered bool) *SecureTextField {
	x.inner.NSTextField.SetBordered(bordered)
	return x
}

// A Boolean value that controls whether the text field draws a bezeled background around its contents.
//
// WithBezeled sets the bezeled property and returns the receiver for chaining.
func (x *SecureTextField) WithBezeled(bezeled bool) *SecureTextField {
	x.inner.NSTextField.SetBezeled(bezeled)
	return x
}

// A Boolean value that controls whether the user can edit the value in the text field.
//
// WithEditable sets the editable property and returns the receiver for chaining.
func (x *SecureTextField) WithEditable(editable bool) *SecureTextField {
	x.inner.NSTextField.SetEditable(editable)
	return x
}

// A Boolean value that determines whether the user can select the content of the text field.
//
// WithSelectable sets the selectable property and returns the receiver for chaining.
func (x *SecureTextField) WithSelectable(selectable bool) *SecureTextField {
	x.inner.NSTextField.SetSelectable(selectable)
	return x
}

// The text field’s delegate.
//
// WithDelegate sets the delegate property and returns the receiver for chaining.
func (x *SecureTextField) WithDelegate(delegate raw.NSTextFieldDelegate) *SecureTextField {
	x.inner.NSTextField.SetDelegate(delegate)
	return x
}

// The text field’s bezel style, square or rounded.
//
// WithBezelStyle sets the bezelStyle property and returns the receiver for chaining.
func (x *SecureTextField) WithBezelStyle(bezelStyle NSTextFieldBezelStyle) *SecureTextField {
	x.inner.NSTextField.SetBezelStyle(raw.NSTextFieldBezelStyle(bezelStyle))
	return x
}

// The maximum width of the text field’s intrinsic content size.
//
// WithPreferredMaxLayoutWidth sets the preferredMaxLayoutWidth property and returns the receiver for chaining.
func (x *SecureTextField) WithPreferredMaxLayoutWidth(preferredMaxLayoutWidth float64) *SecureTextField {
	x.inner.NSTextField.SetPreferredMaxLayoutWidth(preferredMaxLayoutWidth)
	return x
}

// The maximum number of lines a wrapping text field displays before clipping or truncating the text.
//
// WithMaximumNumberOfLines sets the maximumNumberOfLines property and returns the receiver for chaining.
func (x *SecureTextField) WithMaximumNumberOfLines(maximumNumberOfLines int) *SecureTextField {
	x.inner.NSTextField.SetMaximumNumberOfLines(maximumNumberOfLines)
	return x
}

// A Boolean value that controls whether single-line text fields tighten intercharacter spacing before truncating the text.
//
// WithAllowsDefaultTighteningForTruncation sets the allowsDefaultTighteningForTruncation property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsDefaultTighteningForTruncation(allowsDefaultTighteningForTruncation bool) *SecureTextField {
	x.inner.NSTextField.SetAllowsDefaultTighteningForTruncation(allowsDefaultTighteningForTruncation)
	return x
}

// The strategy that the system uses to break lines when laying out multiple lines of text.
//
// WithLineBreakStrategy sets the lineBreakStrategy property and returns the receiver for chaining.
func (x *SecureTextField) WithLineBreakStrategy(lineBreakStrategy NSLineBreakStrategy) *SecureTextField {
	x.inner.NSTextField.SetLineBreakStrategy(raw.NSLineBreakStrategy(lineBreakStrategy))
	return x
}

// WithAllowsWritingTools sets the allowsWritingTools property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsWritingTools(allowsWritingTools bool) *SecureTextField {
	x.inner.NSTextField.SetAllowsWritingTools(allowsWritingTools)
	return x
}

// WithAllowsWritingToolsAffordance sets the allowsWritingToolsAffordance property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsWritingToolsAffordance(allowsWritingToolsAffordance bool) *SecureTextField {
	x.inner.NSTextField.SetAllowsWritingToolsAffordance(allowsWritingToolsAffordance)
	return x
}

// WithPlaceholderStrings sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithPlaceholderStrings(items ...*foundation.NSString) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.SetPlaceholderStrings(foundation.NSArrayFromID[*foundation.NSString](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.Ptr()
	}
	_arr := foundation.NSArrayFromID[*foundation.NSString](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.SetPlaceholderStrings(_arr)
	return x
}

// WithPlaceholderAttributedStrings sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithPlaceholderAttributedStrings(items ...*foundation.NSAttributedString) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.SetPlaceholderAttributedStrings(foundation.NSArrayFromID[*foundation.NSAttributedString](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.Ptr()
	}
	_arr := foundation.NSArrayFromID[*foundation.NSAttributedString](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.SetPlaceholderAttributedStrings(_arr)
	return x
}

// Specifies the behavior for resolving NSTextAlignmentNatural to the visual alignment.
//
// WithResolvesNaturalAlignmentWithBaseWritingDirection sets the resolvesNaturalAlignmentWithBaseWritingDirection property and returns the receiver for chaining.
func (x *SecureTextField) WithResolvesNaturalAlignmentWithBaseWritingDirection(resolvesNaturalAlignmentWithBaseWritingDirection bool) *SecureTextField {
	x.inner.NSTextField.SetResolvesNaturalAlignmentWithBaseWritingDirection(resolvesNaturalAlignmentWithBaseWritingDirection)
	return x
}

// A Boolean value that indicates whether the text field automatically completes text as the user types.
//
// WithAutomaticTextCompletionEnabled sets the automaticTextCompletionEnabled property and returns the receiver for chaining.
func (x *SecureTextField) WithAutomaticTextCompletionEnabled(automaticTextCompletionEnabled bool) *SecureTextField {
	x.inner.NSTextField.SetAutomaticTextCompletionEnabled(automaticTextCompletionEnabled)
	return x
}

// A Boolean value that controls whether the Touch Bar displays the character picker item for rich text fields.
//
// WithAllowsCharacterPickerTouchBarItem sets the allowsCharacterPickerTouchBarItem property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsCharacterPickerTouchBarItem(allowsCharacterPickerTouchBarItem bool) *SecureTextField {
	x.inner.NSTextField.SetAllowsCharacterPickerTouchBarItem(allowsCharacterPickerTouchBarItem)
	return x
}

// A Boolean value that controls whether the user can change font attributes of the text field’s string.
//
// WithAllowsEditingTextAttributes sets the allowsEditingTextAttributes property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsEditingTextAttributes(allowsEditingTextAttributes bool) *SecureTextField {
	x.inner.NSTextField.SetAllowsEditingTextAttributes(allowsEditingTextAttributes)
	return x
}

// A Boolean value that controls whether the user can drag image files into the text field.
//
// WithImportsGraphics sets the importsGraphics property and returns the receiver for chaining.
func (x *SecureTextField) WithImportsGraphics(importsGraphics bool) *SecureTextField {
	x.inner.NSTextField.SetImportsGraphics(importsGraphics)
	return x
}

// The target object that receives action messages from the cell.
//
// WithTarget sets the target property and returns the receiver for chaining.
func (x *SecureTextField) WithTarget(target objc.ID) *SecureTextField {
	x.inner.NSTextField.NSControl.SetTarget(target)
	return x
}

// The default action-message selector associated with the control.
//
// WithAction sets the action property and returns the receiver for chaining.
func (x *SecureTextField) WithAction(action objc.SEL) *SecureTextField {
	x.inner.NSTextField.NSControl.SetAction(action)
	return x
}

// The tag identifying the receiver (not the tag of the receiver’s cell).
//
// WithTag sets the tag property and returns the receiver for chaining.
func (x *SecureTextField) WithTag(tag int) *SecureTextField {
	x.inner.NSTextField.NSControl.SetTag(tag)
	return x
}

// A Boolean value indicating whether the receiver ignores multiple clicks made in rapid succession.
//
// WithIgnoresMultiClick sets the ignoresMultiClick property and returns the receiver for chaining.
func (x *SecureTextField) WithIgnoresMultiClick(ignoresMultiClick bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetIgnoresMultiClick(ignoresMultiClick)
	return x
}

// A Boolean value indicating whether the receiver’s cell sends its action message continuously to its target during mouse tracking.
//
// WithContinuous sets the continuous property and returns the receiver for chaining.
func (x *SecureTextField) WithContinuous(continuous bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetContinuous(continuous)
	return x
}

// A Boolean value that indicates whether the receiver reacts to mouse events.
//
// WithEnabled sets the enabled property and returns the receiver for chaining.
func (x *SecureTextField) WithEnabled(enabled bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetEnabled(enabled)
	return x
}

// A Boolean value indicating whether the receiver refuses the first responder role.
//
// WithRefusesFirstResponder sets the refusesFirstResponder property and returns the receiver for chaining.
func (x *SecureTextField) WithRefusesFirstResponder(refusesFirstResponder bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetRefusesFirstResponder(refusesFirstResponder)
	return x
}

// A Boolean value that indicates whether the cell is highlighted.
//
// WithHighlighted sets the highlighted property and returns the receiver for chaining.
func (x *SecureTextField) WithHighlighted(highlighted bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetHighlighted(highlighted)
	return x
}

// The size of the control.
//
// WithControlSize sets the controlSize property and returns the receiver for chaining.
func (x *SecureTextField) WithControlSize(controlSize NSControlSize) *SecureTextField {
	x.inner.NSTextField.NSControl.SetControlSize(raw.NSControlSize(controlSize))
	return x
}

// The receiver’s formatter.
//
// WithFormatter sets the formatter property and returns the receiver for chaining.
func (x *SecureTextField) WithFormatter(formatter *foundation.NSFormatter) *SecureTextField {
	x.inner.NSTextField.NSControl.SetFormatter(formatter)
	return x
}

// The value of the receiver’s cell as an Objective-C object.
//
// WithObjectValue sets the objectValue property and returns the receiver for chaining.
func (x *SecureTextField) WithObjectValue(objectValue objc.ID) *SecureTextField {
	x.inner.NSTextField.NSControl.SetObjectValue(objectValue)
	return x
}

// The value of the receiver’s cell as an NSString object.
//
// WithStringValue sets the stringValue property and returns the receiver for chaining.
func (x *SecureTextField) WithStringValue(stringValue string) *SecureTextField {
	x.inner.NSTextField.NSControl.SetStringValue(foundation.NSStringStringWithUTF8String(stringValue))
	return x
}

// The value of the receiver’s cell as an attributed string.
//
// WithAttributedStringValue sets the attributedStringValue property and returns the receiver for chaining.
func (x *SecureTextField) WithAttributedStringValue(attributedStringValue *foundation.NSAttributedString) *SecureTextField {
	x.inner.NSTextField.NSControl.SetAttributedStringValue(attributedStringValue)
	return x
}

// The value of the receiver’s cell as an integer.
//
// WithIntValue sets the intValue property and returns the receiver for chaining.
func (x *SecureTextField) WithIntValue(intValue int) *SecureTextField {
	x.inner.NSTextField.NSControl.SetIntValue(intValue)
	return x
}

// The value of the receiver’s cell as an integer value.
//
// WithIntegerValue sets the integerValue property and returns the receiver for chaining.
func (x *SecureTextField) WithIntegerValue(integerValue int) *SecureTextField {
	x.inner.NSTextField.NSControl.SetIntegerValue(integerValue)
	return x
}

// The value of the receiver’s cell as a single-precision floating-point number.
//
// WithFloatValue sets the floatValue property and returns the receiver for chaining.
func (x *SecureTextField) WithFloatValue(floatValue float32) *SecureTextField {
	x.inner.NSTextField.NSControl.SetFloatValue(floatValue)
	return x
}

// The value of the receiver’s cell as a double-precision floating-point number.
//
// WithDoubleValue sets the doubleValue property and returns the receiver for chaining.
func (x *SecureTextField) WithDoubleValue(doubleValue float64) *SecureTextField {
	x.inner.NSTextField.NSControl.SetDoubleValue(doubleValue)
	return x
}

// The font used to draw text in the receiver’s cell.
//
// WithFont sets the font property and returns the receiver for chaining.
func (x *SecureTextField) WithFont(font *Font) *SecureTextField {
	x.inner.NSTextField.NSControl.SetFont(font.Unwrap())
	return x
}

// A Boolean value that indicates whether the text in the control’s cell uses single line mode.
//
// WithUsesSingleLineMode sets the usesSingleLineMode property and returns the receiver for chaining.
func (x *SecureTextField) WithUsesSingleLineMode(usesSingleLineMode bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetUsesSingleLineMode(usesSingleLineMode)
	return x
}

// The line break mode to use for text in the control’s cell.
//
// WithLineBreakMode sets the lineBreakMode property and returns the receiver for chaining.
func (x *SecureTextField) WithLineBreakMode(lineBreakMode NSLineBreakMode) *SecureTextField {
	x.inner.NSTextField.NSControl.SetLineBreakMode(raw.NSLineBreakMode(lineBreakMode))
	return x
}

// The alignment mode of the text in the receiver’s cell.
//
// WithAlignment sets the alignment property and returns the receiver for chaining.
func (x *SecureTextField) WithAlignment(alignment NSTextAlignment) *SecureTextField {
	x.inner.NSTextField.NSControl.SetAlignment(raw.NSTextAlignment(alignment))
	return x
}

// The initial writing direction used to determine the actual writing direction for text.
//
// WithBaseWritingDirection sets the baseWritingDirection property and returns the receiver for chaining.
func (x *SecureTextField) WithBaseWritingDirection(baseWritingDirection NSWritingDirection) *SecureTextField {
	x.inner.NSTextField.NSControl.SetBaseWritingDirection(raw.NSWritingDirection(baseWritingDirection))
	return x
}

// A Boolean value that indicates whether expansion tool tips are shown when the control is hovered over.
//
// WithAllowsExpansionToolTips sets the allowsExpansionToolTips property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowsExpansionToolTips(allowsExpansionToolTips bool) *SecureTextField {
	x.inner.NSTextField.NSControl.SetAllowsExpansionToolTips(allowsExpansionToolTips)
	return x
}

// WithCell sets the cell property and returns the receiver for chaining.
func (x *SecureTextField) WithCell(cell CellProvider) *SecureTextField {
	x.inner.NSTextField.NSControl.SetCell(cell.asCell())
	return x
}

// WithSubviews sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithSubviews(items ...ViewProvider) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.NSControl.NSView.SetSubviews(foundation.NSArrayFromID[*raw.NSView](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.asView().Ptr()
	}
	_arr := foundation.NSArrayFromID[*raw.NSView](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.NSControl.NSView.SetSubviews(_arr)
	return x
}

// WithHidden sets the hidden property and returns the receiver for chaining.
func (x *SecureTextField) WithHidden(hidden bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetHidden(hidden)
	return x
}

// WithPostsFrameChangedNotifications sets the postsFrameChangedNotifications property and returns the receiver for chaining.
func (x *SecureTextField) WithPostsFrameChangedNotifications(postsFrameChangedNotifications bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetPostsFrameChangedNotifications(postsFrameChangedNotifications)
	return x
}

// WithAutoresizesSubviews sets the autoresizesSubviews property and returns the receiver for chaining.
func (x *SecureTextField) WithAutoresizesSubviews(autoresizesSubviews bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAutoresizesSubviews(autoresizesSubviews)
	return x
}

// WithAutoresizingMask sets the autoresizingMask property and returns the receiver for chaining.
func (x *SecureTextField) WithAutoresizingMask(autoresizingMask NSAutoresizingMaskOptions) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAutoresizingMask(raw.NSAutoresizingMaskOptions(autoresizingMask))
	return x
}

// The view’s frame rectangle, which defines its position and size in its superview’s coordinate system.
//
// WithFrame sets the frame property and returns the receiver for chaining.
func (x *SecureTextField) WithFrame(frame corefoundation.CGRect) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetFrame(frame)
	return x
}

// WithFrameRotation sets the frameRotation property and returns the receiver for chaining.
func (x *SecureTextField) WithFrameRotation(frameRotation float64) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetFrameRotation(frameRotation)
	return x
}

// WithFrameCenterRotation sets the frameCenterRotation property and returns the receiver for chaining.
func (x *SecureTextField) WithFrameCenterRotation(frameCenterRotation float64) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetFrameCenterRotation(frameCenterRotation)
	return x
}

// WithBoundsRotation sets the boundsRotation property and returns the receiver for chaining.
func (x *SecureTextField) WithBoundsRotation(boundsRotation float64) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetBoundsRotation(boundsRotation)
	return x
}

// The view’s bounds rectangle, which expresses its location and size in its own coordinate system.
//
// WithBounds sets the bounds property and returns the receiver for chaining.
func (x *SecureTextField) WithBounds(bounds corefoundation.CGRect) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetBounds(bounds)
	return x
}

// WithCanDrawConcurrently sets the canDrawConcurrently property and returns the receiver for chaining.
func (x *SecureTextField) WithCanDrawConcurrently(canDrawConcurrently bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetCanDrawConcurrently(canDrawConcurrently)
	return x
}

// A Boolean value that determines whether the view needs to be redrawn before being displayed.
//
// WithNeedsDisplay sets the needsDisplay property and returns the receiver for chaining.
func (x *SecureTextField) WithNeedsDisplay(needsDisplay bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetNeedsDisplay(needsDisplay)
	return x
}

// WithAcceptsTouchEvents sets the acceptsTouchEvents property and returns the receiver for chaining.
func (x *SecureTextField) WithAcceptsTouchEvents(acceptsTouchEvents bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAcceptsTouchEvents(acceptsTouchEvents)
	return x
}

// WithWantsRestingTouches sets the wantsRestingTouches property and returns the receiver for chaining.
func (x *SecureTextField) WithWantsRestingTouches(wantsRestingTouches bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetWantsRestingTouches(wantsRestingTouches)
	return x
}

// WithLayerContentsRedrawPolicy sets the layerContentsRedrawPolicy property and returns the receiver for chaining.
func (x *SecureTextField) WithLayerContentsRedrawPolicy(layerContentsRedrawPolicy NSViewLayerContentsRedrawPolicy) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetLayerContentsRedrawPolicy(raw.NSViewLayerContentsRedrawPolicy(layerContentsRedrawPolicy))
	return x
}

// WithLayerContentsPlacement sets the layerContentsPlacement property and returns the receiver for chaining.
func (x *SecureTextField) WithLayerContentsPlacement(layerContentsPlacement NSViewLayerContentsPlacement) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetLayerContentsPlacement(raw.NSViewLayerContentsPlacement(layerContentsPlacement))
	return x
}

// WithWantsLayer sets the wantsLayer property and returns the receiver for chaining.
func (x *SecureTextField) WithWantsLayer(wantsLayer bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetWantsLayer(wantsLayer)
	return x
}

// WithLayer sets the layer property and returns the receiver for chaining.
func (x *SecureTextField) WithLayer(layer *quartzcore.CALayer) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetLayer(layer)
	return x
}

// WithCanDrawSubviewsIntoLayer sets the canDrawSubviewsIntoLayer property and returns the receiver for chaining.
func (x *SecureTextField) WithCanDrawSubviewsIntoLayer(canDrawSubviewsIntoLayer bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetCanDrawSubviewsIntoLayer(canDrawSubviewsIntoLayer)
	return x
}

// WithNeedsLayout sets the needsLayout property and returns the receiver for chaining.
func (x *SecureTextField) WithNeedsLayout(needsLayout bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetNeedsLayout(needsLayout)
	return x
}

// WithAlphaValue sets the alphaValue property and returns the receiver for chaining.
func (x *SecureTextField) WithAlphaValue(alphaValue float64) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAlphaValue(alphaValue)
	return x
}

// WithLayerUsesCoreImageFilters sets the layerUsesCoreImageFilters property and returns the receiver for chaining.
func (x *SecureTextField) WithLayerUsesCoreImageFilters(layerUsesCoreImageFilters bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetLayerUsesCoreImageFilters(layerUsesCoreImageFilters)
	return x
}

// WithBackgroundFilters sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithBackgroundFilters(items ...*coreimage.CIFilter) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.NSControl.NSView.SetBackgroundFilters(foundation.NSArrayFromID[*coreimage.CIFilter](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.Ptr()
	}
	_arr := foundation.NSArrayFromID[*coreimage.CIFilter](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.NSControl.NSView.SetBackgroundFilters(_arr)
	return x
}

// WithCompositingFilter sets the compositingFilter property and returns the receiver for chaining.
func (x *SecureTextField) WithCompositingFilter(compositingFilter *coreimage.CIFilter) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetCompositingFilter(compositingFilter)
	return x
}

// WithContentFilters sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithContentFilters(items ...*coreimage.CIFilter) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.NSControl.NSView.SetContentFilters(foundation.NSArrayFromID[*coreimage.CIFilter](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.Ptr()
	}
	_arr := foundation.NSArrayFromID[*coreimage.CIFilter](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.NSControl.NSView.SetContentFilters(_arr)
	return x
}

// WithShadow sets the shadow property and returns the receiver for chaining.
func (x *SecureTextField) WithShadow(shadow *Shadow) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetShadow(shadow.Unwrap())
	return x
}

// WithClipsToBounds sets the clipsToBounds property and returns the receiver for chaining.
func (x *SecureTextField) WithClipsToBounds(clipsToBounds bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetClipsToBounds(clipsToBounds)
	return x
}

// WithPostsBoundsChangedNotifications sets the postsBoundsChangedNotifications property and returns the receiver for chaining.
func (x *SecureTextField) WithPostsBoundsChangedNotifications(postsBoundsChangedNotifications bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetPostsBoundsChangedNotifications(postsBoundsChangedNotifications)
	return x
}

// WithToolTip sets the toolTip property and returns the receiver for chaining.
func (x *SecureTextField) WithToolTip(toolTip string) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetToolTip(foundation.NSStringStringWithUTF8String(toolTip))
	return x
}

// WithUserInterfaceLayoutDirection sets the userInterfaceLayoutDirection property and returns the receiver for chaining.
func (x *SecureTextField) WithUserInterfaceLayoutDirection(userInterfaceLayoutDirection NSUserInterfaceLayoutDirection) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetUserInterfaceLayoutDirection(raw.NSUserInterfaceLayoutDirection(userInterfaceLayoutDirection))
	return x
}

// WithPreparedContentRect sets the preparedContentRect property and returns the receiver for chaining.
func (x *SecureTextField) WithPreparedContentRect(preparedContentRect corefoundation.CGRect) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetPreparedContentRect(preparedContentRect)
	return x
}

// WithNextKeyView sets the nextKeyView property and returns the receiver for chaining.
func (x *SecureTextField) WithNextKeyView(nextKeyView ViewProvider) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetNextKeyView(nextKeyView.asView())
	return x
}

// WithFocusRingType sets the focusRingType property and returns the receiver for chaining.
func (x *SecureTextField) WithFocusRingType(focusRingType NSFocusRingType) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetFocusRingType(raw.NSFocusRingType(focusRingType))
	return x
}

// WithGestureRecognizers sets the collection, converting the Go slice to an NSArray.
func (x *SecureTextField) WithGestureRecognizers(items ...GestureRecognizerProvider) *SecureTextField {
	if len(items) == 0 {
		// An empty (not nil) array: some raw setters dereference the argument.
		x.inner.NSTextField.NSControl.NSView.SetGestureRecognizers(foundation.NSArrayFromID[*raw.NSGestureRecognizer](
			objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
				objc.RegisterName("array"))))
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items {
		_ptrs[_i] = _v.asGestureRecognizer().Ptr()
	}
	_arr := foundation.NSArrayFromID[*raw.NSGestureRecognizer](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.NSTextField.NSControl.NSView.SetGestureRecognizers(_arr)
	return x
}

// WithAllowedTouchTypes sets the allowedTouchTypes property and returns the receiver for chaining.
func (x *SecureTextField) WithAllowedTouchTypes(allowedTouchTypes NSTouchTypeMask) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAllowedTouchTypes(raw.NSTouchTypeMask(allowedTouchTypes))
	return x
}

// WithAdditionalSafeAreaInsets sets the additionalSafeAreaInsets property and returns the receiver for chaining.
func (x *SecureTextField) WithAdditionalSafeAreaInsets(additionalSafeAreaInsets foundation.NSEdgeInsets) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetAdditionalSafeAreaInsets(additionalSafeAreaInsets)
	return x
}

// When this property is YES, any NSControls in the view or its descendants will be sized with compact metrics compatible with macOS 15.0 and earlier. Defaults to NO.
//
// WithPrefersCompactControlSizeMetrics sets the prefersCompactControlSizeMetrics property and returns the receiver for chaining.
func (x *SecureTextField) WithPrefersCompactControlSizeMetrics(prefersCompactControlSizeMetrics bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetPrefersCompactControlSizeMetrics(prefersCompactControlSizeMetrics)
	return x
}

// WithWritingToolsCoordinator sets the writingToolsCoordinator property and returns the receiver for chaining.
func (x *SecureTextField) WithWritingToolsCoordinator(writingToolsCoordinator *WritingToolsCoordinator) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetWritingToolsCoordinator(writingToolsCoordinator.Unwrap())
	return x
}

// WithNeedsUpdateConstraints sets the needsUpdateConstraints property and returns the receiver for chaining.
func (x *SecureTextField) WithNeedsUpdateConstraints(needsUpdateConstraints bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetNeedsUpdateConstraints(needsUpdateConstraints)
	return x
}

// WithTranslatesAutoresizingMaskIntoConstraints sets the translatesAutoresizingMaskIntoConstraints property and returns the receiver for chaining.
func (x *SecureTextField) WithTranslatesAutoresizingMaskIntoConstraints(translatesAutoresizingMaskIntoConstraints bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetTranslatesAutoresizingMaskIntoConstraints(translatesAutoresizingMaskIntoConstraints)
	return x
}

// WithHorizontalContentSizeConstraintActive sets the horizontalContentSizeConstraintActive property and returns the receiver for chaining.
func (x *SecureTextField) WithHorizontalContentSizeConstraintActive(horizontalContentSizeConstraintActive bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetHorizontalContentSizeConstraintActive(horizontalContentSizeConstraintActive)
	return x
}

// WithVerticalContentSizeConstraintActive sets the verticalContentSizeConstraintActive property and returns the receiver for chaining.
func (x *SecureTextField) WithVerticalContentSizeConstraintActive(verticalContentSizeConstraintActive bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetVerticalContentSizeConstraintActive(verticalContentSizeConstraintActive)
	return x
}

// WithWantsBestResolutionOpenGLSurface sets the wantsBestResolutionOpenGLSurface property and returns the receiver for chaining.
func (x *SecureTextField) WithWantsBestResolutionOpenGLSurface(wantsBestResolutionOpenGLSurface bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetWantsBestResolutionOpenGLSurface(wantsBestResolutionOpenGLSurface)
	return x
}

// WithWantsExtendedDynamicRangeOpenGLSurface sets the wantsExtendedDynamicRangeOpenGLSurface property and returns the receiver for chaining.
func (x *SecureTextField) WithWantsExtendedDynamicRangeOpenGLSurface(wantsExtendedDynamicRangeOpenGLSurface bool) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetWantsExtendedDynamicRangeOpenGLSurface(wantsExtendedDynamicRangeOpenGLSurface)
	return x
}

// WithPressureConfiguration sets the pressureConfiguration property and returns the receiver for chaining.
func (x *SecureTextField) WithPressureConfiguration(pressureConfiguration *PressureConfiguration) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.SetPressureConfiguration(pressureConfiguration.Unwrap())
	return x
}

// The next responder after this one, or nil if it has none.
//
// WithNextResponder sets the nextResponder property and returns the receiver for chaining.
func (x *SecureTextField) WithNextResponder(nextResponder ResponderProvider) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.NSResponder.SetNextResponder(nextResponder.asResponder())
	return x
}

// Returns the responder’s menu.
//
// WithMenu sets the menu property and returns the receiver for chaining.
func (x *SecureTextField) WithMenu(menu *Menu) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.NSResponder.SetMenu(menu.Unwrap())
	return x
}

// An object encapsulating a user activity supported by this responder.
//
// WithUserActivity sets the userActivity property and returns the receiver for chaining.
func (x *SecureTextField) WithUserActivity(userActivity *foundation.NSUserActivity) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.NSResponder.SetUserActivity(userActivity)
	return x
}

// The NSTouchBar object associated with the responder.
//
// WithTouchBar sets the touchBar property and returns the receiver for chaining.
func (x *SecureTextField) WithTouchBar(touchBar *TouchBar) *SecureTextField {
	x.inner.NSTextField.NSControl.NSView.NSResponder.SetTouchBar(touchBar.Unwrap())
	return x
}

func (x *SecureTextField) asTextField() *raw.NSTextField { return &x.inner.NSTextField }

func (x *SecureTextField) asControl() *raw.NSControl { return &x.inner.NSTextField.NSControl }

func (x *SecureTextField) asView() *raw.NSView { return &x.inner.NSTextField.NSControl.NSView }

func (x *SecureTextField) asResponder() *raw.NSResponder {
	return &x.inner.NSTextField.NSControl.NSView.NSResponder
}

// SecureTextFieldable is the interface implemented by [SecureTextField], for mocking and DI.
type SecureTextFieldable interface {
	Unwrap() *raw.NSSecureTextField
	WithPlaceholderString(placeholderString string) *SecureTextField
	WithPlaceholderAttributedString(placeholderAttributedString *foundation.NSAttributedString) *SecureTextField
	WithBackgroundColor(backgroundColor *Color) *SecureTextField
	WithDrawsBackground(drawsBackground bool) *SecureTextField
	WithTextColor(textColor *Color) *SecureTextField
	WithBordered(bordered bool) *SecureTextField
	WithBezeled(bezeled bool) *SecureTextField
	WithEditable(editable bool) *SecureTextField
	WithSelectable(selectable bool) *SecureTextField
	WithDelegate(delegate raw.NSTextFieldDelegate) *SecureTextField
	WithBezelStyle(bezelStyle NSTextFieldBezelStyle) *SecureTextField
	WithPreferredMaxLayoutWidth(preferredMaxLayoutWidth float64) *SecureTextField
	WithMaximumNumberOfLines(maximumNumberOfLines int) *SecureTextField
	WithAllowsDefaultTighteningForTruncation(allowsDefaultTighteningForTruncation bool) *SecureTextField
	WithLineBreakStrategy(lineBreakStrategy NSLineBreakStrategy) *SecureTextField
	WithAllowsWritingTools(allowsWritingTools bool) *SecureTextField
	WithAllowsWritingToolsAffordance(allowsWritingToolsAffordance bool) *SecureTextField
	WithPlaceholderStrings(items ...*foundation.NSString) *SecureTextField
	WithPlaceholderAttributedStrings(items ...*foundation.NSAttributedString) *SecureTextField
	WithResolvesNaturalAlignmentWithBaseWritingDirection(resolvesNaturalAlignmentWithBaseWritingDirection bool) *SecureTextField
	WithAutomaticTextCompletionEnabled(automaticTextCompletionEnabled bool) *SecureTextField
	WithAllowsCharacterPickerTouchBarItem(allowsCharacterPickerTouchBarItem bool) *SecureTextField
	WithAllowsEditingTextAttributes(allowsEditingTextAttributes bool) *SecureTextField
	WithImportsGraphics(importsGraphics bool) *SecureTextField
	WithTarget(target objc.ID) *SecureTextField
	WithAction(action objc.SEL) *SecureTextField
	WithTag(tag int) *SecureTextField
	WithIgnoresMultiClick(ignoresMultiClick bool) *SecureTextField
	WithContinuous(continuous bool) *SecureTextField
	WithEnabled(enabled bool) *SecureTextField
	WithRefusesFirstResponder(refusesFirstResponder bool) *SecureTextField
	WithHighlighted(highlighted bool) *SecureTextField
	WithControlSize(controlSize NSControlSize) *SecureTextField
	WithFormatter(formatter *foundation.NSFormatter) *SecureTextField
	WithObjectValue(objectValue objc.ID) *SecureTextField
	WithStringValue(stringValue string) *SecureTextField
	WithAttributedStringValue(attributedStringValue *foundation.NSAttributedString) *SecureTextField
	WithIntValue(intValue int) *SecureTextField
	WithIntegerValue(integerValue int) *SecureTextField
	WithFloatValue(floatValue float32) *SecureTextField
	WithDoubleValue(doubleValue float64) *SecureTextField
	WithFont(font *Font) *SecureTextField
	WithUsesSingleLineMode(usesSingleLineMode bool) *SecureTextField
	WithLineBreakMode(lineBreakMode NSLineBreakMode) *SecureTextField
	WithAlignment(alignment NSTextAlignment) *SecureTextField
	WithBaseWritingDirection(baseWritingDirection NSWritingDirection) *SecureTextField
	WithAllowsExpansionToolTips(allowsExpansionToolTips bool) *SecureTextField
	WithCell(cell CellProvider) *SecureTextField
	WithSubviews(items ...ViewProvider) *SecureTextField
	WithHidden(hidden bool) *SecureTextField
	WithPostsFrameChangedNotifications(postsFrameChangedNotifications bool) *SecureTextField
	WithAutoresizesSubviews(autoresizesSubviews bool) *SecureTextField
	WithAutoresizingMask(autoresizingMask NSAutoresizingMaskOptions) *SecureTextField
	WithFrame(frame corefoundation.CGRect) *SecureTextField
	WithFrameRotation(frameRotation float64) *SecureTextField
	WithFrameCenterRotation(frameCenterRotation float64) *SecureTextField
	WithBoundsRotation(boundsRotation float64) *SecureTextField
	WithBounds(bounds corefoundation.CGRect) *SecureTextField
	WithCanDrawConcurrently(canDrawConcurrently bool) *SecureTextField
	WithNeedsDisplay(needsDisplay bool) *SecureTextField
	WithAcceptsTouchEvents(acceptsTouchEvents bool) *SecureTextField
	WithWantsRestingTouches(wantsRestingTouches bool) *SecureTextField
	WithLayerContentsRedrawPolicy(layerContentsRedrawPolicy NSViewLayerContentsRedrawPolicy) *SecureTextField
	WithLayerContentsPlacement(layerContentsPlacement NSViewLayerContentsPlacement) *SecureTextField
	WithWantsLayer(wantsLayer bool) *SecureTextField
	WithLayer(layer *quartzcore.CALayer) *SecureTextField
	WithCanDrawSubviewsIntoLayer(canDrawSubviewsIntoLayer bool) *SecureTextField
	WithNeedsLayout(needsLayout bool) *SecureTextField
	WithAlphaValue(alphaValue float64) *SecureTextField
	WithLayerUsesCoreImageFilters(layerUsesCoreImageFilters bool) *SecureTextField
	WithBackgroundFilters(items ...*coreimage.CIFilter) *SecureTextField
	WithCompositingFilter(compositingFilter *coreimage.CIFilter) *SecureTextField
	WithContentFilters(items ...*coreimage.CIFilter) *SecureTextField
	WithShadow(shadow *Shadow) *SecureTextField
	WithClipsToBounds(clipsToBounds bool) *SecureTextField
	WithPostsBoundsChangedNotifications(postsBoundsChangedNotifications bool) *SecureTextField
	WithToolTip(toolTip string) *SecureTextField
	WithUserInterfaceLayoutDirection(userInterfaceLayoutDirection NSUserInterfaceLayoutDirection) *SecureTextField
	WithPreparedContentRect(preparedContentRect corefoundation.CGRect) *SecureTextField
	WithNextKeyView(nextKeyView ViewProvider) *SecureTextField
	WithFocusRingType(focusRingType NSFocusRingType) *SecureTextField
	WithGestureRecognizers(items ...GestureRecognizerProvider) *SecureTextField
	WithAllowedTouchTypes(allowedTouchTypes NSTouchTypeMask) *SecureTextField
	WithAdditionalSafeAreaInsets(additionalSafeAreaInsets foundation.NSEdgeInsets) *SecureTextField
	WithPrefersCompactControlSizeMetrics(prefersCompactControlSizeMetrics bool) *SecureTextField
	WithWritingToolsCoordinator(writingToolsCoordinator *WritingToolsCoordinator) *SecureTextField
	WithNeedsUpdateConstraints(needsUpdateConstraints bool) *SecureTextField
	WithTranslatesAutoresizingMaskIntoConstraints(translatesAutoresizingMaskIntoConstraints bool) *SecureTextField
	WithHorizontalContentSizeConstraintActive(horizontalContentSizeConstraintActive bool) *SecureTextField
	WithVerticalContentSizeConstraintActive(verticalContentSizeConstraintActive bool) *SecureTextField
	WithWantsBestResolutionOpenGLSurface(wantsBestResolutionOpenGLSurface bool) *SecureTextField
	WithWantsExtendedDynamicRangeOpenGLSurface(wantsExtendedDynamicRangeOpenGLSurface bool) *SecureTextField
	WithPressureConfiguration(pressureConfiguration *PressureConfiguration) *SecureTextField
	WithNextResponder(nextResponder ResponderProvider) *SecureTextField
	WithMenu(menu *Menu) *SecureTextField
	WithUserActivity(userActivity *foundation.NSUserActivity) *SecureTextField
	WithTouchBar(touchBar *TouchBar) *SecureTextField
}

var _ SecureTextFieldable = (*SecureTextField)(nil)
