// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package appkit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// SliderTouchBarItem is an idiomatic wrapper over the Objective-C class NSSliderTouchBarItem.
//
// It embeds [TouchBarItem], promoting that type's methods.
//
// A bar item that provides a slider control for choosing a value in a range.
type SliderTouchBarItem struct {
	TouchBarItem
}

// SliderTouchBarItemFromID adopts an existing Objective-C object as a SliderTouchBarItem
// (nil for 0), retaining it and registering a release finalizer.
func SliderTouchBarItemFromID(id objc.ID) *SliderTouchBarItem {
	if id == 0 {
		return nil
	}
	x := &SliderTouchBarItem{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// sliderTouchBarItemAdopt wraps an Objective-C object that this code just created as a
// SliderTouchBarItem (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func sliderTouchBarItemAdopt(id objc.ID) *SliderTouchBarItem {
	if id == 0 {
		return nil
	}
	x := &SliderTouchBarItem{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewSliderTouchBarItem creates a new SliderTouchBarItem.
func NewSliderTouchBarItem() *SliderTouchBarItem {
	_id := objc.Send[objc.ID](objc.ID(_class("NSSliderTouchBarItem")), objc.RegisterName("new"))
	return sliderTouchBarItemAdopt(_id)
}

// WithSlider sets the slider displayed by the bar item.
func (stbi *SliderTouchBarItem) WithSlider(slider *Slider) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setSlider:"), objref.IDOf(slider))
	return stbi
}

// WithDoubleValue sets the double value of the slider.
func (stbi *SliderTouchBarItem) WithDoubleValue(doubleValue float64) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setDoubleValue:"), doubleValue)
	return stbi
}

// WithMinimumSliderWidth sets the minimum width of the slider’s track.
func (stbi *SliderTouchBarItem) WithMinimumSliderWidth(minimumSliderWidth float64) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setMinimumSliderWidth:"), minimumSliderWidth)
	return stbi
}

// WithMaximumSliderWidth sets the maximum width of the slider’s track.
func (stbi *SliderTouchBarItem) WithMaximumSliderWidth(maximumSliderWidth float64) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setMaximumSliderWidth:"), maximumSliderWidth)
	return stbi
}

// WithLabel sets the text displayed alongside the slider.
func (stbi *SliderTouchBarItem) WithLabel(label string) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setLabel:"), purego.NSString(label))
	return stbi
}

// WithMinimumValueAccessory sets the accessory that appears at the end of the slider with the minimum value.
func (stbi *SliderTouchBarItem) WithMinimumValueAccessory(minimumValueAccessory *SliderAccessory) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setMinimumValueAccessory:"), objref.IDOf(minimumValueAccessory))
	return stbi
}

// WithMaximumValueAccessory sets the accessory that appears at the end of the slider with the maximum value.
func (stbi *SliderTouchBarItem) WithMaximumValueAccessory(maximumValueAccessory *SliderAccessory) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setMaximumValueAccessory:"), objref.IDOf(maximumValueAccessory))
	return stbi
}

// WithValueAccessoryWidth sets the width of the value accessories that appear at either end of the slider.
func (stbi *SliderTouchBarItem) WithValueAccessoryWidth(valueAccessoryWidth float64) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setValueAccessoryWidth:"), valueAccessoryWidth)
	return stbi
}

// WithTarget sets an object that is notified when a user interacts with the slider or either of the accessories.
func (stbi *SliderTouchBarItem) WithTarget(target obj.Object) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setTarget:"), objref.IDOf(target))
	return stbi
}

// WithCustomizationLabel sets the user-visible string identifying this item during bar customization.
func (stbi *SliderTouchBarItem) WithCustomizationLabel(customizationLabel string) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setCustomizationLabel:"), purego.NSString(customizationLabel))
	return stbi
}

// WithVisibilityPriority sets determines which items are shown in a bar when space is limited.
func (stbi *SliderTouchBarItem) WithVisibilityPriority(visibilityPriority float32) *SliderTouchBarItem {
	objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("setVisibilityPriority:"), visibilityPriority)
	return stbi
}

// Slider returns the slider displayed by the bar item. It is automatically created, but can be set to a custom subclass. doubleValue, minValue, maxValue, etc can all be read and set through the slider.
func (stbi *SliderTouchBarItem) Slider() *Slider {
	_r := objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("slider"))
	return SliderFromID(_r)
}

// DoubleValue returns the double value of the control
func (stbi *SliderTouchBarItem) DoubleValue() float64 {
	_r := objc.Send[float64](objref.IDOf(stbi), objc.RegisterName("doubleValue"))
	return _r
}

// MinimumSliderWidth returns the width boundaries of the slider track of this item. The system defines the default minimum. The maximum defaults to MAXFLOAT
func (stbi *SliderTouchBarItem) MinimumSliderWidth() float64 {
	_r := objc.Send[float64](objref.IDOf(stbi), objc.RegisterName("minimumSliderWidth"))
	return _r
}

// MaximumSliderWidth wraps the corresponding Objective-C method.
func (stbi *SliderTouchBarItem) MaximumSliderWidth() float64 {
	_r := objc.Send[float64](objref.IDOf(stbi), objc.RegisterName("maximumSliderWidth"))
	return _r
}

// Label returns the text label displayed along with the slider. If set to nil, the label will not have space reserved in the item.
func (stbi *SliderTouchBarItem) Label() string {
	_r := objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("label"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

// MinimumValueAccessory returns the accessory that appears on the end of the slider with the minimum value
func (stbi *SliderTouchBarItem) MinimumValueAccessory() *SliderAccessory {
	_r := objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("minimumValueAccessory"))
	return SliderAccessoryFromID(_r)
}

// MaximumValueAccessory returns the accessory that appears on the end of the slider with the maximum value
func (stbi *SliderTouchBarItem) MaximumValueAccessory() *SliderAccessory {
	_r := objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("maximumValueAccessory"))
	return SliderAccessoryFromID(_r)
}

// ValueAccessoryWidth returns the width of the value accessories. Defaults to `.default`, but can be set to `.wide` or a custom value.
func (stbi *SliderTouchBarItem) ValueAccessoryWidth() float64 {
	_r := objc.Send[float64](objref.IDOf(stbi), objc.RegisterName("valueAccessoryWidth"))
	return _r
}

// Target returns the target of the item, notified when the slider or accessories receive user interaction.
func (stbi *SliderTouchBarItem) Target() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(stbi), objc.RegisterName("target"))
	return obj.Wrap(_r)
}

var _ TouchBarItemProvider = (*SliderTouchBarItem)(nil)
