// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package webkit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// WKFindResult is an idiomatic wrapper over the Objective-C class WKFindResult.
//
// An object that contains the results of searching the web view’s contents.
type WKFindResult struct {
	objref.Handle
}

// WKFindResultFromID adopts an existing Objective-C object as a WKFindResult
// (nil for 0), retaining it and registering a release finalizer.
func WKFindResultFromID(id objc.ID) *WKFindResult {
	if id == 0 {
		return nil
	}
	x := &WKFindResult{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// wKFindResultAdopt wraps an Objective-C object that this code just created as a
// WKFindResult (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func wKFindResultAdopt(id objc.ID) *WKFindResult {
	if id == 0 {
		return nil
	}
	x := &WKFindResult{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (wfr *WKFindResult) Description() string {
	return rt.Description(objref.IDOf(wfr))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (wfr *WKFindResult) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(wfr), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (wfr *WKFindResult) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(wfr), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (wfr *WKFindResult) String() string {
	return rt.Description(objref.IDOf(wfr))
}

// NewWKFindResult creates a new WKFindResult.
func NewWKFindResult() *WKFindResult {
	_id := objc.Send[objc.ID](objc.ID(_class("WKFindResult")), objc.RegisterName("new"))
	return wKFindResultAdopt(_id)
}

// MatchFound wraps the corresponding Objective-C method.
func (wfr *WKFindResult) MatchFound() bool {
	_r := objc.Send[bool](objref.IDOf(wfr), objc.RegisterName("matchFound"))
	return _r
}
