// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package symbols

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/symbols"
	"github.com/ebitengine/purego/objc"
)

// An abstract base class for transitions you can apply to symbol-based images.
//
// SymbolContentTransition wraps [raw.NSSymbolContentTransition] with a fluent Go API.
type SymbolContentTransition struct {
	inner *raw.NSSymbolContentTransition
}

// Unwrap returns the underlying [raw.NSSymbolContentTransition].
func (x *SymbolContentTransition) Unwrap() *raw.NSSymbolContentTransition { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *SymbolContentTransition) ID() objc.ID { return x.inner.Ptr() }

// SymbolContentTransitionFromID adopts an existing object pointer as a SymbolContentTransition (nil for 0).
func SymbolContentTransitionFromID(id objc.ID) *SymbolContentTransition {
	if id == 0 {
		return nil
	}
	return &SymbolContentTransition{inner: raw.NSSymbolContentTransitionFromID(id)}
}

// NewSymbolContentTransition creates a new [SymbolContentTransition].
func NewSymbolContentTransition() *SymbolContentTransition {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("NSSymbolContentTransition")), objc.RegisterName("new"))
	return &SymbolContentTransition{inner: raw.NSSymbolContentTransitionFromID(_id)}
}

func (x *SymbolContentTransition) asSymbolContentTransition() *raw.NSSymbolContentTransition {
	return x.inner
}

// SymbolContentTransitionable is the interface implemented by [SymbolContentTransition], for mocking and DI.
type SymbolContentTransitionable interface {
	Unwrap() *raw.NSSymbolContentTransition
}

var _ SymbolContentTransitionable = (*SymbolContentTransition)(nil)
