// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package devicediscoveryextension

import (
	"fmt"
	"strings"
)

type DDDeviceCategory int64

const (
	DDDeviceCategoryHiFiSpeaker         DDDeviceCategory = 0
	DDDeviceCategoryHiFiSpeakerMultiple DDDeviceCategory = 1
	DDDeviceCategoryTVWithMediaBox      DDDeviceCategory = 2
	DDDeviceCategoryTV                  DDDeviceCategory = 3
	DDDeviceCategoryLaptopComputer      DDDeviceCategory = 4
	DDDeviceCategoryDesktopComputer     DDDeviceCategory = 5
	DDDeviceCategoryAccessorySetup      DDDeviceCategory = 6
)

func (e DDDeviceCategory) String() string {
	switch e {
	case DDDeviceCategoryHiFiSpeaker:
		return "DDDeviceCategoryHiFiSpeaker"
	case DDDeviceCategoryHiFiSpeakerMultiple:
		return "DDDeviceCategoryHiFiSpeakerMultiple"
	case DDDeviceCategoryTVWithMediaBox:
		return "DDDeviceCategoryTVWithMediaBox"
	case DDDeviceCategoryTV:
		return "DDDeviceCategoryTV"
	case DDDeviceCategoryLaptopComputer:
		return "DDDeviceCategoryLaptopComputer"
	case DDDeviceCategoryDesktopComputer:
		return "DDDeviceCategoryDesktopComputer"
	case DDDeviceCategoryAccessorySetup:
		return "DDDeviceCategoryAccessorySetup"
	default:
		return fmt.Sprintf("DDDeviceCategory(%d)", int64(e))
	}
}

type DDDeviceMediaPlaybackState int64

const (
	DDDeviceMediaPlaybackStateNoContent DDDeviceMediaPlaybackState = 0
	DDDeviceMediaPlaybackStatePaused    DDDeviceMediaPlaybackState = 1
	DDDeviceMediaPlaybackStatePlaying   DDDeviceMediaPlaybackState = 2
)

func (e DDDeviceMediaPlaybackState) String() string {
	switch e {
	case DDDeviceMediaPlaybackStateNoContent:
		return "DDDeviceMediaPlaybackStateNoContent"
	case DDDeviceMediaPlaybackStatePaused:
		return "DDDeviceMediaPlaybackStatePaused"
	case DDDeviceMediaPlaybackStatePlaying:
		return "DDDeviceMediaPlaybackStatePlaying"
	default:
		return fmt.Sprintf("DDDeviceMediaPlaybackState(%d)", int64(e))
	}
}

type DDDeviceProtocol int64

const (
	DDDeviceProtocolInvalid DDDeviceProtocol = 0
	DDDeviceProtocolDIAL    DDDeviceProtocol = 1
)

func (e DDDeviceProtocol) String() string {
	switch e {
	case DDDeviceProtocolInvalid:
		return "DDDeviceProtocolInvalid"
	case DDDeviceProtocolDIAL:
		return "DDDeviceProtocolDIAL"
	default:
		return fmt.Sprintf("DDDeviceProtocol(%d)", int64(e))
	}
}

type DDDeviceState int64

const (
	DDDeviceStateInvalid      DDDeviceState = 0
	DDDeviceStateActivating   DDDeviceState = 10
	DDDeviceStateActivated    DDDeviceState = 20
	DDDeviceStateAuthorized   DDDeviceState = 25
	DDDeviceStateInvalidating DDDeviceState = 30
)

func (e DDDeviceState) String() string {
	switch e {
	case DDDeviceStateInvalid:
		return "DDDeviceStateInvalid"
	case DDDeviceStateActivating:
		return "DDDeviceStateActivating"
	case DDDeviceStateActivated:
		return "DDDeviceStateActivated"
	case DDDeviceStateAuthorized:
		return "DDDeviceStateAuthorized"
	case DDDeviceStateInvalidating:
		return "DDDeviceStateInvalidating"
	default:
		return fmt.Sprintf("DDDeviceState(%d)", int64(e))
	}
}

// Bitmask — values may be combined with |.
type DDDeviceSupports uint64

const (
	DDDeviceSupportsBluetoothPairingLE         DDDeviceSupports = 2
	DDDeviceSupportsBluetoothTransportBridging DDDeviceSupports = 4
	DDDeviceSupportsBluetoothHID               DDDeviceSupports = 8
)

func (e DDDeviceSupports) String() string {
	var parts []string
	if e&DDDeviceSupportsBluetoothPairingLE != 0 {
		parts = append(parts, "DDDeviceSupportsBluetoothPairingLE")
	}
	if e&DDDeviceSupportsBluetoothTransportBridging != 0 {
		parts = append(parts, "DDDeviceSupportsBluetoothTransportBridging")
	}
	if e&DDDeviceSupportsBluetoothHID != 0 {
		parts = append(parts, "DDDeviceSupportsBluetoothHID")
	}
	if len(parts) == 0 {
		return "0"
	}
	return strings.Join(parts, "|")
}

type DDDeviceWiFiAwareServiceRole int64

const (
	DDDeviceWiFiAwareServiceRoleSubscriber DDDeviceWiFiAwareServiceRole = 10
	DDDeviceWiFiAwareServiceRolePublisher  DDDeviceWiFiAwareServiceRole = 20
)

func (e DDDeviceWiFiAwareServiceRole) String() string {
	switch e {
	case DDDeviceWiFiAwareServiceRoleSubscriber:
		return "DDDeviceWiFiAwareServiceRoleSubscriber"
	case DDDeviceWiFiAwareServiceRolePublisher:
		return "DDDeviceWiFiAwareServiceRolePublisher"
	default:
		return fmt.Sprintf("DDDeviceWiFiAwareServiceRole(%d)", int64(e))
	}
}

type DDErrorCode int64

const (
	DDErrorCodeSuccess            DDErrorCode = 0
	DDErrorCodeUnknown            DDErrorCode = 350000
	DDErrorCodeBadParameter       DDErrorCode = 350001
	DDErrorCodeUnsupported        DDErrorCode = 350002
	DDErrorCodeTimeout            DDErrorCode = 350003
	DDErrorCodeInternal           DDErrorCode = 350004
	DDErrorCodeMissingEntitlement DDErrorCode = 350005
	DDErrorCodePermission         DDErrorCode = 350006
	DDErrorCodeNext               DDErrorCode = 350007
)

func (e DDErrorCode) String() string {
	switch e {
	case DDErrorCodeSuccess:
		return "DDErrorCodeSuccess"
	case DDErrorCodeUnknown:
		return "DDErrorCodeUnknown"
	case DDErrorCodeBadParameter:
		return "DDErrorCodeBadParameter"
	case DDErrorCodeUnsupported:
		return "DDErrorCodeUnsupported"
	case DDErrorCodeTimeout:
		return "DDErrorCodeTimeout"
	case DDErrorCodeInternal:
		return "DDErrorCodeInternal"
	case DDErrorCodeMissingEntitlement:
		return "DDErrorCodeMissingEntitlement"
	case DDErrorCodePermission:
		return "DDErrorCodePermission"
	case DDErrorCodeNext:
		return "DDErrorCodeNext"
	default:
		return fmt.Sprintf("DDErrorCode(%d)", int64(e))
	}
}

type DDEventType int64

const (
	DDEventTypeUnknown       DDEventType = 0
	DDEventTypeDeviceFound   DDEventType = 40
	DDEventTypeDeviceLost    DDEventType = 41
	DDEventTypeDeviceChanged DDEventType = 42
)

func (e DDEventType) String() string {
	switch e {
	case DDEventTypeUnknown:
		return "DDEventTypeUnknown"
	case DDEventTypeDeviceFound:
		return "DDEventTypeDeviceFound"
	case DDEventTypeDeviceLost:
		return "DDEventTypeDeviceLost"
	case DDEventTypeDeviceChanged:
		return "DDEventTypeDeviceChanged"
	default:
		return fmt.Sprintf("DDEventType(%d)", int64(e))
	}
}
