// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package authenticationservices

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/authenticationservices"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/ebitengine/purego/objc"
	"unsafe"
)

// AuthorizationProviderExtensionLoginConfiguration wraps [raw.ASAuthorizationProviderExtensionLoginConfiguration] with a fluent Go API.
type AuthorizationProviderExtensionLoginConfiguration struct {
	inner *raw.ASAuthorizationProviderExtensionLoginConfiguration
}

// Unwrap returns the underlying [raw.ASAuthorizationProviderExtensionLoginConfiguration].
func (x *AuthorizationProviderExtensionLoginConfiguration) Unwrap() *raw.ASAuthorizationProviderExtensionLoginConfiguration { return x.inner }

// NewAuthorizationProviderExtensionLoginConfigurationWithClientIDIssuerTokenEndpointURLJwksEndpointURLAudience creates a new [AuthorizationProviderExtensionLoginConfiguration].
func NewAuthorizationProviderExtensionLoginConfigurationWithClientIDIssuerTokenEndpointURLJwksEndpointURLAudience(clientID string, issuer string, tokenEndpointURL string, jwksEndpointURL string, audience string) *AuthorizationProviderExtensionLoginConfiguration {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("ASAuthorizationProviderExtensionLoginConfiguration")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithClientID:issuer:tokenEndpointURL:jwksEndpointURL:audience:"), foundation.NSStringStringWithUTF8String(clientID).Ptr(), foundation.NSStringStringWithUTF8String(issuer).Ptr(), foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(tokenEndpointURL)).Ptr(), foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(jwksEndpointURL)).Ptr(), foundation.NSStringStringWithUTF8String(audience).Ptr())
	return &AuthorizationProviderExtensionLoginConfiguration{inner: raw.ASAuthorizationProviderExtensionLoginConfigurationFromID(_id)}
}

// WithInvalidCredentialPredicate sets the invalidCredentialPredicate property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithInvalidCredentialPredicate(invalidCredentialPredicate string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetInvalidCredentialPredicate(foundation.NSStringStringWithUTF8String(invalidCredentialPredicate))
	return x
}

// WithAccountDisplayName sets the accountDisplayName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithAccountDisplayName(accountDisplayName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetAccountDisplayName(foundation.NSStringStringWithUTF8String(accountDisplayName))
	return x
}

// WithAudience sets the audience property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithAudience(audience string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetAudience(foundation.NSStringStringWithUTF8String(audience))
	return x
}

// WithTokenEndpointURL sets the tokenEndpointURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithTokenEndpointURL(tokenEndpointURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetTokenEndpointURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(tokenEndpointURL)))
	return x
}

// WithJwksEndpointURL sets the jwksEndpointURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithJwksEndpointURL(jwksEndpointURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetJwksEndpointURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(jwksEndpointURL)))
	return x
}

// WithDeviceContext sets the deviceContext property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithDeviceContext(deviceContext *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetDeviceContext(deviceContext)
	return x
}

// WithUserSecureEnclaveKeyBiometricPolicy sets the userSecureEnclaveKeyBiometricPolicy property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithUserSecureEnclaveKeyBiometricPolicy(userSecureEnclaveKeyBiometricPolicy raw.ASAuthorizationProviderExtensionUserSecureEnclaveKeyBiometricPolicy) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetUserSecureEnclaveKeyBiometricPolicy(userSecureEnclaveKeyBiometricPolicy)
	return x
}

// WithNonceEndpointURL sets the nonceEndpointURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithNonceEndpointURL(nonceEndpointURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetNonceEndpointURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(nonceEndpointURL)))
	return x
}

// WithNonceResponseKeypath sets the nonceResponseKeypath property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithNonceResponseKeypath(nonceResponseKeypath string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetNonceResponseKeypath(foundation.NSStringStringWithUTF8String(nonceResponseKeypath))
	return x
}

// WithServerNonceClaimName sets the serverNonceClaimName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithServerNonceClaimName(serverNonceClaimName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetServerNonceClaimName(foundation.NSStringStringWithUTF8String(serverNonceClaimName))
	return x
}

// WithCustomNonceRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomNonceRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomNonceRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomNonceRequestValues(_arr)
	return x
}

// WithAdditionalScopes sets the additionalScopes property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithAdditionalScopes(additionalScopes string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetAdditionalScopes(foundation.NSStringStringWithUTF8String(additionalScopes))
	return x
}

// WithAdditionalAuthorizationScopes sets the additionalAuthorizationScopes property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithAdditionalAuthorizationScopes(additionalAuthorizationScopes string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetAdditionalAuthorizationScopes(foundation.NSStringStringWithUTF8String(additionalAuthorizationScopes))
	return x
}

// WithIncludePreviousRefreshTokenInLoginRequest sets the includePreviousRefreshTokenInLoginRequest property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithIncludePreviousRefreshTokenInLoginRequest(includePreviousRefreshTokenInLoginRequest bool) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetIncludePreviousRefreshTokenInLoginRequest(includePreviousRefreshTokenInLoginRequest)
	return x
}

// WithPreviousRefreshTokenClaimName sets the previousRefreshTokenClaimName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithPreviousRefreshTokenClaimName(previousRefreshTokenClaimName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetPreviousRefreshTokenClaimName(foundation.NSStringStringWithUTF8String(previousRefreshTokenClaimName))
	return x
}

// WithCustomRequestJWTParameterName sets the customRequestJWTParameterName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomRequestJWTParameterName(customRequestJWTParameterName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetCustomRequestJWTParameterName(foundation.NSStringStringWithUTF8String(customRequestJWTParameterName))
	return x
}

// WithCustomLoginRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomLoginRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomLoginRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomLoginRequestValues(_arr)
	return x
}

// WithUniqueIdentifierClaimName sets the uniqueIdentifierClaimName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithUniqueIdentifierClaimName(uniqueIdentifierClaimName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetUniqueIdentifierClaimName(foundation.NSStringStringWithUTF8String(uniqueIdentifierClaimName))
	return x
}

// WithGroupRequestClaimName sets the groupRequestClaimName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithGroupRequestClaimName(groupRequestClaimName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetGroupRequestClaimName(foundation.NSStringStringWithUTF8String(groupRequestClaimName))
	return x
}

// WithGroupResponseClaimName sets the groupResponseClaimName property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithGroupResponseClaimName(groupResponseClaimName string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetGroupResponseClaimName(foundation.NSStringStringWithUTF8String(groupResponseClaimName))
	return x
}

// WithKerberosTicketMappings sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithKerberosTicketMappings(items ...*raw.ASAuthorizationProviderExtensionKerberosMapping) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetKerberosTicketMappings(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*raw.ASAuthorizationProviderExtensionKerberosMapping](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetKerberosTicketMappings(_arr)
	return x
}

// WithRefreshEndpointURL sets the refreshEndpointURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithRefreshEndpointURL(refreshEndpointURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetRefreshEndpointURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(refreshEndpointURL)))
	return x
}

// WithCustomRefreshRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomRefreshRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomRefreshRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomRefreshRequestValues(_arr)
	return x
}

// WithFederationType sets the federationType property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationType(federationType raw.ASAuthorizationProviderExtensionFederationType) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationType(federationType)
	return x
}

// WithFederationRequestURN sets the federationRequestURN property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationRequestURN(federationRequestURN string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationRequestURN(foundation.NSStringStringWithUTF8String(federationRequestURN))
	return x
}

// WithFederationMEXURL sets the federationMEXURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationMEXURL(federationMEXURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationMEXURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(federationMEXURL)))
	return x
}

// WithFederationUserPreauthenticationURL sets the federationUserPreauthenticationURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationUserPreauthenticationURL(federationUserPreauthenticationURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationUserPreauthenticationURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(federationUserPreauthenticationURL)))
	return x
}

// WithFederationMEXURLKeypath sets the federationMEXURLKeypath property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationMEXURLKeypath(federationMEXURLKeypath string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationMEXURLKeypath(foundation.NSStringStringWithUTF8String(federationMEXURLKeypath))
	return x
}

// WithFederationPredicate sets the federationPredicate property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithFederationPredicate(federationPredicate string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetFederationPredicate(foundation.NSStringStringWithUTF8String(federationPredicate))
	return x
}

// WithCustomFederationUserPreauthenticationRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomFederationUserPreauthenticationRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomFederationUserPreauthenticationRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomFederationUserPreauthenticationRequestValues(_arr)
	return x
}

// WithLoginRequestEncryptionAPVPrefix sets the loginRequestEncryptionAPVPrefix property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithLoginRequestEncryptionAPVPrefix(loginRequestEncryptionAPVPrefix *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetLoginRequestEncryptionAPVPrefix(loginRequestEncryptionAPVPrefix)
	return x
}

// WithLoginRequestEncryptionAlgorithm sets the loginRequestEncryptionAlgorithm property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithLoginRequestEncryptionAlgorithm(loginRequestEncryptionAlgorithm *foundation.NSNumber) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetLoginRequestEncryptionAlgorithm(loginRequestEncryptionAlgorithm)
	return x
}

// WithLoginRequestHPKEPreSharedKey sets the loginRequestHPKEPreSharedKey property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithLoginRequestHPKEPreSharedKey(loginRequestHPKEPreSharedKey *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetLoginRequestHPKEPreSharedKey(loginRequestHPKEPreSharedKey)
	return x
}

// WithLoginRequestHPKEPreSharedKeyID sets the loginRequestHPKEPreSharedKeyID property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithLoginRequestHPKEPreSharedKeyID(loginRequestHPKEPreSharedKeyID *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetLoginRequestHPKEPreSharedKeyID(loginRequestHPKEPreSharedKeyID)
	return x
}

// WithKeyEndpointURL sets the keyEndpointURL property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithKeyEndpointURL(keyEndpointURL string) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetKeyEndpointURL(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(keyEndpointURL)))
	return x
}

// WithCustomKeyExchangeRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomKeyExchangeRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomKeyExchangeRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomKeyExchangeRequestValues(_arr)
	return x
}

// WithCustomKeyRequestValues sets the collection, converting the Go slice to an NSArray.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithCustomKeyRequestValues(items ...*foundation.NSURLQueryItem) *AuthorizationProviderExtensionLoginConfiguration {
	if len(items) == 0 {
		x.inner.SetCustomKeyRequestValues(nil)
		return x
	}
	_ptrs := make([]objc.ID, len(items))
	for _i, _v := range items { _ptrs[_i] = _v.Ptr() }
	_arr := foundation.NSArrayFromID[*foundation.NSURLQueryItem](
		objc.Send[objc.ID](objc.ID(objc.GetClass("NSArray")),
			objc.RegisterName("arrayWithObjects:count:"),
			unsafe.Pointer(&_ptrs[0]), uint(len(_ptrs))))
	x.inner.SetCustomKeyRequestValues(_arr)
	return x
}

// WithHpkePreSharedKey sets the hpkePreSharedKey property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithHpkePreSharedKey(hpkePreSharedKey *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetHpkePreSharedKey(hpkePreSharedKey)
	return x
}

// WithHpkePreSharedKeyID sets the hpkePreSharedKeyID property and returns the receiver for chaining.
func (x *AuthorizationProviderExtensionLoginConfiguration) WithHpkePreSharedKeyID(hpkePreSharedKeyID *foundation.NSData) *AuthorizationProviderExtensionLoginConfiguration {
	x.inner.SetHpkePreSharedKeyID(hpkePreSharedKeyID)
	return x
}

// CustomNonceRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomNonceRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomNonceRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// CustomLoginRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomLoginRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomLoginRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// KerberosTicketMappings returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) KerberosTicketMappings() []*raw.ASAuthorizationProviderExtensionKerberosMapping {
	arr := x.inner.KerberosTicketMappings()
	if arr == nil {
		return nil
	}
	out := make([]*raw.ASAuthorizationProviderExtensionKerberosMapping, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// CustomRefreshRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomRefreshRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomRefreshRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// CustomFederationUserPreauthenticationRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomFederationUserPreauthenticationRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomFederationUserPreauthenticationRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// CustomKeyExchangeRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomKeyExchangeRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomKeyExchangeRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

// CustomKeyRequestValues returns the collection as a Go slice.
func (x *AuthorizationProviderExtensionLoginConfiguration) CustomKeyRequestValues() []*foundation.NSURLQueryItem {
	arr := x.inner.CustomKeyRequestValues()
	if arr == nil {
		return nil
	}
	out := make([]*foundation.NSURLQueryItem, arr.Count())
	for i := range out {
		out[i] = arr.ObjectAtIndex(uint(i))
	}
	return out
}

