// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package passkit

import (
	"unsafe"

	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// Apple documentation: https://developer.apple.com/documentation/passkit/pkaddpassmetadatapreview
type PKAddPassMetadataPreview struct {
	foundation.NSObject
}

var (
	_clsPKAddPassMetadataPreview = _objcClass("PKAddPassMetadataPreview")
	_pKAddPassMetadataPreviewSelInitWithPassThumbnailLocalizedDescription = objc.RegisterName("initWithPassThumbnail:localizedDescription:")
	_pKAddPassMetadataPreviewSelPreviewWithPassThumbnailLocalizedDescription = objc.RegisterName("previewWithPassThumbnail:localizedDescription:")
	_pKAddPassMetadataPreviewSelPassThumbnailImage = objc.RegisterName("passThumbnailImage")
	_pKAddPassMetadataPreviewSelLocalizedDescription = objc.RegisterName("localizedDescription")
)

func PKAddPassMetadataPreviewFromID(id objc.ID) *PKAddPassMetadataPreview {
	if id == 0 {
		return nil
	}
	o := &PKAddPassMetadataPreview{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

// Initializer preview object to represent the pass being added to Wallet.which requires a CGImage of the pass's card art and a localized description. - Properties: - passThumbnail: CGImage representing the card artwork of the pass to be presented during provisioning. - localizedDescription: Localized description of the pass.
func (o *PKAddPassMetadataPreview) InitWithPassThumbnailLocalizedDescription(passThumbnail unsafe.Pointer, description *foundation.NSString) *PKAddPassMetadataPreview {
	_ret := objc.Send[objc.ID](o.Ptr(), _pKAddPassMetadataPreviewSelInitWithPassThumbnailLocalizedDescription, passThumbnail, description.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return PKAddPassMetadataPreviewFromID(_ret)
}

func PKAddPassMetadataPreviewPreviewWithPassThumbnailLocalizedDescription(passThumbnail unsafe.Pointer, description *foundation.NSString) *PKAddPassMetadataPreview {
	_ret := objc.Send[objc.ID](objc.ID(_clsPKAddPassMetadataPreview), _pKAddPassMetadataPreviewSelPreviewWithPassThumbnailLocalizedDescription, passThumbnail, description.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return PKAddPassMetadataPreviewFromID(_ret)
}

// CGImage representing the pass in our provisioning UI.
func (o *PKAddPassMetadataPreview) PassThumbnailImage() unsafe.Pointer {
	_ret := objc.Send[unsafe.Pointer](o.Ptr(), _pKAddPassMetadataPreviewSelPassThumbnailImage)
	return _ret
}

// Localized description of the pass to be referenced during provisioning.
func (o *PKAddPassMetadataPreview) LocalizedDescription() *foundation.NSString {
	_ret := objc.Send[objc.ID](o.Ptr(), _pKAddPassMetadataPreviewSelLocalizedDescription)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return foundation.NSStringFromID(_ret)
}

