// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package spritekit

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/avfaudio"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// A node that plays audio.
//
// Apple documentation: https://developer.apple.com/documentation/spritekit/skaudionode
type SKAudioNode struct {
	SKNode
}

var (
	_clsSKAudioNode                    = _objcClass("SKAudioNode")
	_sKAudioNodeSelInitWithAVAudioNode = objc.RegisterName("initWithAVAudioNode:")
	_sKAudioNodeSelInitWithCoder       = objc.RegisterName("initWithCoder:")
	_sKAudioNodeSelInitWithFileNamed   = objc.RegisterName("initWithFileNamed:")
	_sKAudioNodeSelInitWithURL         = objc.RegisterName("initWithURL:")
	_sKAudioNodeSelAvAudioNode         = objc.RegisterName("avAudioNode")
	_sKAudioNodeSelSetAvAudioNode      = objc.RegisterName("setAvAudioNode:")
	_sKAudioNodeSelAutoplayLooped      = objc.RegisterName("autoplayLooped")
	_sKAudioNodeSelSetAutoplayLooped   = objc.RegisterName("setAutoplayLooped:")
	_sKAudioNodeSelIsPositional        = objc.RegisterName("isPositional")
	_sKAudioNodeSelSetPositional       = objc.RegisterName("setPositional:")
)

func SKAudioNodeFromID(id objc.ID) *SKAudioNode {
	if id == 0 {
		return nil
	}
	o := &SKAudioNode{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

// Initializes an audio node from an AVFoundation audio node.
func (o *SKAudioNode) InitWithAVAudioNode(node *avfaudio.AVAudioNode) *SKAudioNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _sKAudioNodeSelInitWithAVAudioNode, node.Ptr())
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return SKAudioNodeFromID(_ret)
}

// Tells you when to initialize an audio node that has been unarchived.
func (o *SKAudioNode) InitWithCoder(aDecoder *foundation.NSCoder) *SKAudioNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _sKAudioNodeSelInitWithCoder, aDecoder.Ptr())
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return SKAudioNodeFromID(_ret)
}

// Initializes an audio node from an audio asset with the specified filename.
func (o *SKAudioNode) InitWithFileNamed(name *foundation.NSString) *SKAudioNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _sKAudioNodeSelInitWithFileNamed, name.Ptr())
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return SKAudioNodeFromID(_ret)
}

// Initializes an audio node from an audio asset with the specified URL.
func (o *SKAudioNode) InitWithURL(url *foundation.NSURL) *SKAudioNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _sKAudioNodeSelInitWithURL, url.Ptr())
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return SKAudioNodeFromID(_ret)
}

// Sets or gets the current AVAudioNode used by this instance.
func (o *SKAudioNode) AvAudioNode() *avfaudio.AVAudioNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _sKAudioNodeSelAvAudioNode)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return avfaudio.AVAudioNodeFromID(_ret)
}

func (o *SKAudioNode) SetAvAudioNode(avAudioNode *avfaudio.AVAudioNode) {
	o.Ptr().Send(_sKAudioNodeSelSetAvAudioNode, avAudioNode.Ptr())
}

// Specifies whether the node is to automatically play sound when added to a scene. If autoplaysLooped is NO, the node and its sound must be explicitly scheduled and played using the scene's engine. If YES, the node will automatically play sound when added to a scene. Defaults to YES. @see SKView.paused
func (o *SKAudioNode) AutoplayLooped() bool {
	_ret := objc.Send[bool](o.Ptr(), _sKAudioNodeSelAutoplayLooped)
	return _ret
}

func (o *SKAudioNode) SetAutoplayLooped(autoplayLooped bool) {
	o.Ptr().Send(_sKAudioNodeSelSetAutoplayLooped, autoplayLooped)
}

// Marks the audio source as positional so that the audio mix considers relative position and velocity with regards to the scene's current listener node. @see AVAudio3DMixing @see SKScene.listener
func (o *SKAudioNode) IsPositional() bool {
	_ret := objc.Send[bool](o.Ptr(), _sKAudioNodeSelIsPositional)
	return _ret
}

func (o *SKAudioNode) SetPositional(positional bool) {
	o.Ptr().Send(_sKAudioNodeSelSetPositional, positional)
}
