// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package mpsneuralnetwork

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// CNNConvolutionWeightsAndBiasesState is an idiomatic wrapper over the Objective-C class MPSCNNConvolutionWeightsAndBiasesState.
type CNNConvolutionWeightsAndBiasesState struct {
	objref.Handle
}

// CNNConvolutionWeightsAndBiasesStateFromID adopts an existing Objective-C object as a CNNConvolutionWeightsAndBiasesState
// (nil for 0), retaining it and registering a release finalizer.
func CNNConvolutionWeightsAndBiasesStateFromID(id objc.ID) *CNNConvolutionWeightsAndBiasesState {
	if id == 0 {
		return nil
	}
	x := &CNNConvolutionWeightsAndBiasesState{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// cNNConvolutionWeightsAndBiasesStateAdopt wraps an Objective-C object that this code just created as a
// CNNConvolutionWeightsAndBiasesState (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func cNNConvolutionWeightsAndBiasesStateAdopt(id objc.ID) *CNNConvolutionWeightsAndBiasesState {
	if id == 0 {
		return nil
	}
	x := &CNNConvolutionWeightsAndBiasesState{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *CNNConvolutionWeightsAndBiasesState) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *CNNConvolutionWeightsAndBiasesState) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *CNNConvolutionWeightsAndBiasesState) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewCNNConvolutionWeightsAndBiasesState creates a new CNNConvolutionWeightsAndBiasesState.
func NewCNNConvolutionWeightsAndBiasesState() *CNNConvolutionWeightsAndBiasesState {
	_id := objc.Send[objc.ID](objc.ID(_class("MPSCNNConvolutionWeightsAndBiasesState")), objc.RegisterName("new"))
	return cNNConvolutionWeightsAndBiasesStateAdopt(_id)
}

// Offset at which weights start in weights buffer Default value is 0.
func (x *CNNConvolutionWeightsAndBiasesState) WeightsOffset() int {
	_r := objc.Send[int](objref.IDOf(x), objc.RegisterName("weightsOffset"))
	return _r
}

// Offset at which weights start in biases buffer Default value is 0.
func (x *CNNConvolutionWeightsAndBiasesState) BiasesOffset() int {
	_r := objc.Send[int](objref.IDOf(x), objc.RegisterName("biasesOffset"))
	return _r
}

// CNNConvolutionWeightsAndBiasesStateable is the interface implemented by [CNNConvolutionWeightsAndBiasesState], for mocking and DI.
type CNNConvolutionWeightsAndBiasesStateable interface {
	obj.Object
	WeightsOffset() int
	BiasesOffset() int
}

var _ CNNConvolutionWeightsAndBiasesStateable = (*CNNConvolutionWeightsAndBiasesState)(nil)
