// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package networkextension

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// The result from a filter data provder for subsequent chunks of data on a flow.
//
// NEFilterDataVerdict is an idiomatic wrapper over the Objective-C class NEFilterDataVerdict.
type NEFilterDataVerdict struct {
	objref.Handle
}

// NEFilterDataVerdictFromID adopts an existing Objective-C object as a NEFilterDataVerdict
// (nil for 0), retaining it and registering a release finalizer.
func NEFilterDataVerdictFromID(id objc.ID) *NEFilterDataVerdict {
	if id == 0 {
		return nil
	}
	x := &NEFilterDataVerdict{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// nEFilterDataVerdictAdopt wraps an Objective-C object that this code just created as a
// NEFilterDataVerdict (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func nEFilterDataVerdictAdopt(id objc.ID) *NEFilterDataVerdict {
	if id == 0 {
		return nil
	}
	x := &NEFilterDataVerdict{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *NEFilterDataVerdict) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *NEFilterDataVerdict) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *NEFilterDataVerdict) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewNEFilterDataVerdict creates a new NEFilterDataVerdict.
func NewNEFilterDataVerdict() *NEFilterDataVerdict {
	_id := objc.Send[objc.ID](objc.ID(_class("NEFilterDataVerdict")), objc.RegisterName("new"))
	return nEFilterDataVerdictAdopt(_id)
}

// The frequencty at which to provide flow statistics to the data provider.
//
// WithStatisticsReportFrequency sets statisticsReportFrequency and returns the receiver so calls can be chained.
func (x *NEFilterDataVerdict) WithStatisticsReportFrequency(statisticsReportFrequency NEFilterReportFrequency) *NEFilterDataVerdict {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStatisticsReportFrequency:"), statisticsReportFrequency)
	return x
}

// A Boolean value that indicates whether to send a report to the control provider when processing this verdict.
//
// WithShouldReport sets shouldReport and returns the receiver so calls can be chained.
func (x *NEFilterDataVerdict) WithShouldReport(shouldReport bool) *NEFilterDataVerdict {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldReport:"), shouldReport)
	return x
}

// The frequency at which the data provider's -[NEFilterProvider handleReport:] method is called with a NEFilterReport instance with an event of NEFilterReportEventFlowStatistics. The default value is NEFilterReportFrequencyNone, so by default no statistics are reported.
func (x *NEFilterDataVerdict) StatisticsReportFrequency() NEFilterReportFrequency {
	_r := objc.Send[NEFilterReportFrequency](objref.IDOf(x), objc.RegisterName("statisticsReportFrequency"))
	return _r
}

func (x *NEFilterDataVerdict) SetStatisticsReportFrequency(statisticsReportFrequency NEFilterReportFrequency) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStatisticsReportFrequency:"), statisticsReportFrequency)
}

// NEFilterDataVerdictable is the interface implemented by [NEFilterDataVerdict], for mocking and DI.
type NEFilterDataVerdictable interface {
	obj.Object
	WithStatisticsReportFrequency(statisticsReportFrequency NEFilterReportFrequency) *NEFilterDataVerdict
	WithShouldReport(shouldReport bool) *NEFilterDataVerdict
	StatisticsReportFrequency() NEFilterReportFrequency
	SetStatisticsReportFrequency(statisticsReportFrequency NEFilterReportFrequency)
}

var _ NEFilterDataVerdictable = (*NEFilterDataVerdict)(nil)
