// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package intents

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// SendMessageIntentResponse is an idiomatic wrapper over the Objective-C class INSendMessageIntentResponse.
//
// It embeds [IntentResponse], promoting that type's methods.
//
// Your app’s response to a send message intent.
type SendMessageIntentResponse struct {
	IntentResponse
}

// SendMessageIntentResponseFromID adopts an existing Objective-C object as a SendMessageIntentResponse
// (nil for 0), retaining it and registering a release finalizer.
func SendMessageIntentResponseFromID(id objc.ID) *SendMessageIntentResponse {
	if id == 0 {
		return nil
	}
	x := &SendMessageIntentResponse{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// sendMessageIntentResponseAdopt wraps an Objective-C object that this code just created as a
// SendMessageIntentResponse (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func sendMessageIntentResponseAdopt(id objc.ID) *SendMessageIntentResponse {
	if id == 0 {
		return nil
	}
	x := &SendMessageIntentResponse{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewSendMessageIntentResponseWithCodeUserActivity initializes the response object with the specified code and user activity object.
func NewSendMessageIntentResponseWithCodeUserActivity(code SendMessageIntentResponseCode, userActivity obj.Object) *SendMessageIntentResponse {
	_alloc := objc.Send[objc.ID](objc.ID(_class("INSendMessageIntentResponse")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithCode:userActivity:"), code, objref.IDOf(userActivity))
	return sendMessageIntentResponseAdopt(_id)
}

// WithUserActivity sets the user activity object to use when launching the app.
func (smir *SendMessageIntentResponse) WithUserActivity(userActivity obj.Object) *SendMessageIntentResponse {
	objc.Send[objc.ID](objref.IDOf(smir), objc.RegisterName("setUserActivity:"), objref.IDOf(userActivity))
	return smir
}

// Code returns the code.
func (smir *SendMessageIntentResponse) Code() SendMessageIntentResponseCode {
	_r := objc.Send[SendMessageIntentResponseCode](objref.IDOf(smir), objc.RegisterName("code"))
	return _r
}

// SentMessages returns the sent messages.
func (smir *SendMessageIntentResponse) SentMessages() []obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(smir), objc.RegisterName("sentMessages"))
	return purego.NSArrayToSlice(_r, func(_id objc.ID) obj.Object { return obj.Wrap(_id) })
}

// SetSentMessages wraps the corresponding Objective-C method.
func (smir *SendMessageIntentResponse) SetSentMessages(sentMessages []obj.Object) {
	objc.Send[objc.ID](objref.IDOf(smir), objc.RegisterName("setSentMessages:"), purego.SliceToNSArray(sentMessages, func(_v obj.Object) objc.ID { return objref.IDOf(_v) }))
}

var _ IntentResponseProvider = (*SendMessageIntentResponse)(nil)
