// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package foundation

import (
	"unsafe"

	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/ae"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// Apple documentation: https://developer.apple.com/documentation/foundation/nsappleeventmanager
type NSAppleEventManager struct {
	NSObject
}

var (
	_clsNSAppleEventManager                                                  = _objcClass("NSAppleEventManager")
	_nSAppleEventManagerSelSharedAppleEventManager                           = objc.RegisterName("sharedAppleEventManager")
	_nSAppleEventManagerSelSetEventHandlerAndSelectorForEventClassAndEventID = objc.RegisterName("setEventHandler:andSelector:forEventClass:andEventID:")
	_nSAppleEventManagerSelRemoveEventHandlerForEventClassAndEventID         = objc.RegisterName("removeEventHandlerForEventClass:andEventID:")
	_nSAppleEventManagerSelDispatchRawAppleEventWithRawReplyHandlerRefCon    = objc.RegisterName("dispatchRawAppleEvent:withRawReply:handlerRefCon:")
	_nSAppleEventManagerSelSuspendCurrentAppleEvent                          = objc.RegisterName("suspendCurrentAppleEvent")
	_nSAppleEventManagerSelAppleEventForSuspensionID                         = objc.RegisterName("appleEventForSuspensionID:")
	_nSAppleEventManagerSelReplyAppleEventForSuspensionID                    = objc.RegisterName("replyAppleEventForSuspensionID:")
	_nSAppleEventManagerSelSetCurrentAppleEventAndReplyEventWithSuspensionID = objc.RegisterName("setCurrentAppleEventAndReplyEventWithSuspensionID:")
	_nSAppleEventManagerSelResumeWithSuspensionID                            = objc.RegisterName("resumeWithSuspensionID:")
	_nSAppleEventManagerSelCurrentAppleEvent                                 = objc.RegisterName("currentAppleEvent")
	_nSAppleEventManagerSelCurrentReplyAppleEvent                            = objc.RegisterName("currentReplyAppleEvent")
)

func NSAppleEventManagerFromID(id objc.ID) *NSAppleEventManager {
	if id == 0 {
		return nil
	}
	o := &NSAppleEventManager{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

func NSAppleEventManagerSharedAppleEventManager() *NSAppleEventManager {
	_ret := objc.Send[objc.ID](objc.ID(_clsNSAppleEventManager), _nSAppleEventManagerSelSharedAppleEventManager)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return NSAppleEventManagerFromID(_ret)
}

func (o *NSAppleEventManager) SetEventHandlerAndSelectorForEventClassAndEventID(handler objc.ID, handleEventSelector objc.SEL, eventClass uint, eventID uint) {
	o.Ptr().Send(_nSAppleEventManagerSelSetEventHandlerAndSelectorForEventClassAndEventID, handler, handleEventSelector, eventClass, eventID)
}

func (o *NSAppleEventManager) RemoveEventHandlerForEventClassAndEventID(eventClass uint, eventID uint) {
	o.Ptr().Send(_nSAppleEventManagerSelRemoveEventHandlerForEventClassAndEventID, eventClass, eventID)
}

func (o *NSAppleEventManager) DispatchRawAppleEventWithRawReplyHandlerRefCon(theAppleEvent *ae.AEDesc, theReply *ae.AEDesc, handlerRefCon unsafe.Pointer) int16 {
	_ret := objc.Send[int16](o.Ptr(), _nSAppleEventManagerSelDispatchRawAppleEventWithRawReplyHandlerRefCon, theAppleEvent, theReply, handlerRefCon)
	return _ret
}

func (o *NSAppleEventManager) SuspendCurrentAppleEvent() unsafe.Pointer {
	_ret := objc.Send[unsafe.Pointer](o.Ptr(), _nSAppleEventManagerSelSuspendCurrentAppleEvent)
	return _ret
}

func (o *NSAppleEventManager) AppleEventForSuspensionID(suspensionID unsafe.Pointer) *NSAppleEventDescriptor {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSAppleEventManagerSelAppleEventForSuspensionID, suspensionID)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return NSAppleEventDescriptorFromID(_ret)
}

func (o *NSAppleEventManager) ReplyAppleEventForSuspensionID(suspensionID unsafe.Pointer) *NSAppleEventDescriptor {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSAppleEventManagerSelReplyAppleEventForSuspensionID, suspensionID)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return NSAppleEventDescriptorFromID(_ret)
}

func (o *NSAppleEventManager) SetCurrentAppleEventAndReplyEventWithSuspensionID(suspensionID unsafe.Pointer) {
	o.Ptr().Send(_nSAppleEventManagerSelSetCurrentAppleEventAndReplyEventWithSuspensionID, suspensionID)
}

func (o *NSAppleEventManager) ResumeWithSuspensionID(suspensionID unsafe.Pointer) {
	o.Ptr().Send(_nSAppleEventManagerSelResumeWithSuspensionID, suspensionID)
}

func (o *NSAppleEventManager) CurrentAppleEvent() *NSAppleEventDescriptor {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSAppleEventManagerSelCurrentAppleEvent)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return NSAppleEventDescriptorFromID(_ret)
}

func (o *NSAppleEventManager) CurrentReplyAppleEvent() *NSAppleEventDescriptor {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSAppleEventManagerSelCurrentReplyAppleEvent)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return NSAppleEventDescriptorFromID(_ret)
}
