// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package automaticassessmentconfiguration

import (
	"github.com/ebitengine/purego"
)

func AEAssessmentErrorDomain() uintptr {
	ptr, _ := purego.Dlsym(_automaticassessmentconfigurationLib, "AEAssessmentErrorDomain")
	return ptr
}

func AENotInstalledParticipantsKey() uintptr {
	ptr, _ := purego.Dlsym(_automaticassessmentconfigurationLib, "AENotInstalledParticipantsKey")
	return ptr
}

func AERestrictedSystemParticipantsKey() uintptr {
	ptr, _ := purego.Dlsym(_automaticassessmentconfigurationLib, "AERestrictedSystemParticipantsKey")
	return ptr
}

