// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package corehaptics

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/corehaptics"
	"github.com/ebitengine/purego/objc"
)

// HapticParameterCurveControlPoint wraps [raw.CHHapticParameterCurveControlPoint] with a fluent Go API.
type HapticParameterCurveControlPoint struct {
	inner *raw.CHHapticParameterCurveControlPoint
}

// Unwrap returns the underlying [raw.CHHapticParameterCurveControlPoint].
func (x *HapticParameterCurveControlPoint) Unwrap() *raw.CHHapticParameterCurveControlPoint { return x.inner }

// NewHapticParameterCurveControlPointWithRelativeTimeValue creates a new [HapticParameterCurveControlPoint].
func NewHapticParameterCurveControlPointWithRelativeTimeValue(time_ float64, value float32) *HapticParameterCurveControlPoint {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("CHHapticParameterCurveControlPoint")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithRelativeTime:value:"), time_, value)
	return &HapticParameterCurveControlPoint{inner: raw.CHHapticParameterCurveControlPointFromID(_id)}
}

// WithRelativeTime sets the relativeTime property and returns the receiver for chaining.
func (x *HapticParameterCurveControlPoint) WithRelativeTime(relativeTime float64) *HapticParameterCurveControlPoint {
	x.inner.SetRelativeTime(relativeTime)
	return x
}

// WithValue sets the value property and returns the receiver for chaining.
func (x *HapticParameterCurveControlPoint) WithValue(value float32) *HapticParameterCurveControlPoint {
	x.inner.SetValue(value)
	return x
}

// RelativeTime calls the underlying RelativeTime.
func (x *HapticParameterCurveControlPoint) RelativeTime() float64 {
	return x.inner.RelativeTime()
}

// SetRelativeTime calls the underlying SetRelativeTime.
func (x *HapticParameterCurveControlPoint) SetRelativeTime(relativeTime float64) {
	x.inner.SetRelativeTime(relativeTime)
}

// Value calls the underlying Value.
func (x *HapticParameterCurveControlPoint) Value() float32 {
	return x.inner.Value()
}

// SetValue calls the underlying SetValue.
func (x *HapticParameterCurveControlPoint) SetValue(value float32) {
	x.inner.SetValue(value)
}

// HapticParameterCurveControlPointable is the interface implemented by [HapticParameterCurveControlPoint], for mocking and DI.
type HapticParameterCurveControlPointable interface {
	Unwrap() *raw.CHHapticParameterCurveControlPoint
	WithRelativeTime(relativeTime float64) *HapticParameterCurveControlPoint
	WithValue(value float32) *HapticParameterCurveControlPoint
	RelativeTime() float64
	SetRelativeTime(relativeTime float64)
	Value() float32
	SetValue(value float32)
}

var _ HapticParameterCurveControlPointable = (*HapticParameterCurveControlPoint)(nil)

