// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package avfoundation

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/internal/pureobjc"
)

// Apple documentation: https://developer.apple.com/documentation/avfoundation/avassetresourceloadingdatarequest
type AVAssetResourceLoadingDataRequest struct {
	foundation.NSObject
}

var (
	_clsAVAssetResourceLoadingDataRequest = _objcClass("AVAssetResourceLoadingDataRequest")
	_aVAssetResourceLoadingDataRequestSelRespondWithData = objc.RegisterName("respondWithData:")
	_aVAssetResourceLoadingDataRequestSelRequestedOffset = objc.RegisterName("requestedOffset")
	_aVAssetResourceLoadingDataRequestSelRequestedLength = objc.RegisterName("requestedLength")
	_aVAssetResourceLoadingDataRequestSelRequestsAllDataToEndOfResource = objc.RegisterName("requestsAllDataToEndOfResource")
	_aVAssetResourceLoadingDataRequestSelCurrentOffset = objc.RegisterName("currentOffset")
)

func AVAssetResourceLoadingDataRequestFromID(id objc.ID) *AVAssetResourceLoadingDataRequest {
	if id == 0 {
		return nil
	}
	o := &AVAssetResourceLoadingDataRequest{}
	o.InitPtr(id)
	pureobjc.Track(o)
	return o
}

// @method 		respondWithData: @abstract		Provides data to the receiver. @param			data An instance of NSData containing some or all of the requested bytes. @discussion	May be invoked multiple times on the same instance of AVAssetResourceLoadingDataRequest to provide the full range of requested data incrementally. Upon each invocation, the value of currentOffset will be updated to accord with the amount of data provided. The instance of NSData that you provide may be retained for use in parsing or other processing for an indefinite period of time after this method returns. For this reason, if you are providing an instance of NSMutableData, you should avoid mutating it further after sharing its contents. If you are managing your own memory pool for I/O and resource loading, consider using -[NSData initWithBytesNoCopy:length:deallocator:] in order to receive notification of the earliest opportunity for safe recycling of the underlying memory.
func (o *AVAssetResourceLoadingDataRequest) RespondWithData(data *foundation.NSData) {
	o.Ptr().Send(_aVAssetResourceLoadingDataRequestSelRespondWithData, data.Ptr())
}

// @property 		requestedOffset @abstract		The position within the resource of the first byte requested.
func (o *AVAssetResourceLoadingDataRequest) RequestedOffset() int64 {
	_ret := objc.Send[int64](o.Ptr(), _aVAssetResourceLoadingDataRequestSelRequestedOffset)
	return _ret
}

// @property 		requestedLength @abstract		The length of the data requested. @discussion	Note that requestsAllDataToEndOfResource will be set to YES when the entire remaining length of the resource is being requested from requestedOffset to the end of the resource. This can occur even when the content length has not yet been reported by you via a prior finished loading request. When requestsAllDataToEndOfResource has a value of YES, you should disregard the value of requestedLength and incrementally provide as much data starting from the requestedOffset as the resource contains, until you have provided all of the available data successfully and invoked -finishLoading, until you have encountered a failure and invoked -finishLoadingWithError:, or until you have received -resourceLoader:didCancelLoadingRequest: for the AVAssetResourceLoadingRequest from which the AVAssetResourceLoadingDataRequest was obtained. When requestsAllDataToEndOfResource is YES and the content length has not yet been provided by you via a prior finished loading request, the value of requestedLength is set to NSIntegerMax. Starting in macOS 10.11 and iOS 9.0, in 32-bit applications requestedLength is also set to NSIntegerMax when all of the remaining resource data is being requested and the known length of the remaining data exceeds NSIntegerMax.
func (o *AVAssetResourceLoadingDataRequest) RequestedLength() int {
	_ret := objc.Send[int](o.Ptr(), _aVAssetResourceLoadingDataRequestSelRequestedLength)
	return _ret
}

// @property 		requestsAllDataToEndOfResource @abstract		Specifies that the entire remaining length of the resource from requestedOffset to the end of the resource is being requested. @discussion	When requestsAllDataToEndOfResource has a value of YES, you should disregard the value of requestedLength and incrementally provide as much data starting from the requestedOffset as the resource contains, until you have provided all of the available data successfully and invoked -finishLoading, until you have encountered a failure and invoked -finishLoadingWithError:, or until you have received -resourceLoader:didCancelLoadingRequest: for the AVAssetResourceLoadingRequest from which the AVAssetResourceLoadingDataRequest was obtained.
func (o *AVAssetResourceLoadingDataRequest) RequestsAllDataToEndOfResource() bool {
	_ret := objc.Send[bool](o.Ptr(), _aVAssetResourceLoadingDataRequestSelRequestsAllDataToEndOfResource)
	return _ret
}

// @property 		currentOffset @abstract		The position within the resource of the next byte within the resource following the bytes that have already been provided via prior invocations of -respondWithData.
func (o *AVAssetResourceLoadingDataRequest) CurrentOffset() int64 {
	_ret := objc.Send[int64](o.Ptr(), _aVAssetResourceLoadingDataRequestSelCurrentOffset)
	return _ret
}

