// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package avfoundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
)

// MetadataFocusTrackedObject is an idiomatic wrapper over the Objective-C class AVMetadataFocusTrackedObject.
//
// It embeds [MetadataObject], promoting that type's methods.
//
// A metadata object that is maintained in focus by the camera’s auto focus system continuously tracking it.
type MetadataFocusTrackedObject struct {
	MetadataObject
}

// MetadataFocusTrackedObjectFromID adopts an existing Objective-C object as a MetadataFocusTrackedObject
// (nil for 0), retaining it and registering a release finalizer.
func MetadataFocusTrackedObjectFromID(id objc.ID) *MetadataFocusTrackedObject {
	if id == 0 {
		return nil
	}
	x := &MetadataFocusTrackedObject{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// metadataFocusTrackedObjectAdopt wraps an Objective-C object that this code just created as a
// MetadataFocusTrackedObject (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func metadataFocusTrackedObjectAdopt(id objc.ID) *MetadataFocusTrackedObject {
	if id == 0 {
		return nil
	}
	x := &MetadataFocusTrackedObject{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewMetadataFocusTrackedObject creates a new MetadataFocusTrackedObject.
func NewMetadataFocusTrackedObject() *MetadataFocusTrackedObject {
	_id := objc.Send[objc.ID](objc.ID(_class("AVMetadataFocusTrackedObject")), objc.RegisterName("new"))
	return metadataFocusTrackedObjectAdopt(_id)
}

var _ MetadataObjectProvider = (*MetadataFocusTrackedObject)(nil)
