// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package metrickit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// An abstract data class for a metric.
//
// Metric is an idiomatic wrapper over the Objective-C class MXMetric.
type Metric struct {
	objref.Handle
}

// MetricFromID adopts an existing Objective-C object as a Metric
// (nil for 0), retaining it and registering a release finalizer.
func MetricFromID(id objc.ID) *Metric {
	if id == 0 {
		return nil
	}
	x := &Metric{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// metricAdopt wraps an Objective-C object that this code just created as a
// Metric (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func metricAdopt(id objc.ID) *Metric {
	if id == 0 {
		return nil
	}
	x := &Metric{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *Metric) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *Metric) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *Metric) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewMetric creates a new Metric.
func NewMetric() *Metric {
	_id := objc.Send[objc.ID](objc.ID(_class("MXMetric")), objc.RegisterName("new"))
	return metricAdopt(_id)
}

// Returns the contents of the metric in JSON format.
func (x *Metric) JSONRepresentation() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("JSONRepresentation"))
	return obj.Wrap(_r)
}

// Returns the contents of a metric as a dictionary.
func (x *Metric) DictionaryRepresentation() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("dictionaryRepresentation"))
	return obj.Wrap(_r)
}

// Metricable is the interface implemented by [Metric], for mocking and DI.
type Metricable interface {
	obj.Object
	JSONRepresentation() obj.Object
	DictionaryRepresentation() obj.Object
}

var _ Metricable = (*Metric)(nil)
