// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package virtualization

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// The host audio input stream source that provides audio from the host system’s default input device.
//
// Apple documentation: https://developer.apple.com/documentation/virtualization/vzhostaudioinputstreamsource
type VZHostAudioInputStreamSource struct {
	VZAudioInputStreamSource
}

var (
	_clsVZHostAudioInputStreamSource     = _objcClass("VZHostAudioInputStreamSource")
	_vZHostAudioInputStreamSourceSelInit = objc.RegisterName("init")
)

func VZHostAudioInputStreamSourceFromID(id objc.ID) *VZHostAudioInputStreamSource {
	if id == 0 {
		return nil
	}
	o := &VZHostAudioInputStreamSource{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

// Creates a new audio input stream source.
func (o *VZHostAudioInputStreamSource) Init() *VZHostAudioInputStreamSource {
	_ret := objc.Send[objc.ID](o.Ptr(), _vZHostAudioInputStreamSourceSelInit)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return VZHostAudioInputStreamSourceFromID(_ret)
}
