// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package eventkit

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/raw/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// A class that represents the day of the week.
//
// Apple documentation: https://developer.apple.com/documentation/eventkit/ekrecurrencedayofweek
type EKRecurrenceDayOfWeek struct {
	foundation.NSObject
}

var (
	_clsEKRecurrenceDayOfWeek                               = _objcClass("EKRecurrenceDayOfWeek")
	_eKRecurrenceDayOfWeekSelDayOfWeek                      = objc.RegisterName("dayOfWeek:")
	_eKRecurrenceDayOfWeekSelDayOfWeekWeekNumber            = objc.RegisterName("dayOfWeek:weekNumber:")
	_eKRecurrenceDayOfWeekSelInitWithDayOfTheWeekWeekNumber = objc.RegisterName("initWithDayOfTheWeek:weekNumber:")
	_eKRecurrenceDayOfWeekSelDayOfTheWeek                   = objc.RegisterName("dayOfTheWeek")
	_eKRecurrenceDayOfWeekSelWeekNumber                     = objc.RegisterName("weekNumber")
)

func EKRecurrenceDayOfWeekFromID(id objc.ID) *EKRecurrenceDayOfWeek {
	if id == 0 {
		return nil
	}
	o := &EKRecurrenceDayOfWeek{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

// Creates and returns a day of the week with a given day.
func EKRecurrenceDayOfWeekDayOfWeek(dayOfTheWeek EKWeekday) *EKRecurrenceDayOfWeek {
	_ret := objc.Send[objc.ID](objc.ID(_clsEKRecurrenceDayOfWeek), _eKRecurrenceDayOfWeekSelDayOfWeek, dayOfTheWeek)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return EKRecurrenceDayOfWeekFromID(_ret)
}

// Creates and returns an autoreleased day of the week with a given day and week number.
func EKRecurrenceDayOfWeekDayOfWeekWeekNumber(dayOfTheWeek EKWeekday, weekNumber int) *EKRecurrenceDayOfWeek {
	_ret := objc.Send[objc.ID](objc.ID(_clsEKRecurrenceDayOfWeek), _eKRecurrenceDayOfWeekSelDayOfWeekWeekNumber, dayOfTheWeek, weekNumber)
	if _ret != 0 {
		_ret.Send(objc.RegisterName("retain"))
	}
	return EKRecurrenceDayOfWeekFromID(_ret)
}

// Initializes and returns a day of the week with a given day and week number.
func (o *EKRecurrenceDayOfWeek) InitWithDayOfTheWeekWeekNumber(dayOfTheWeek EKWeekday, weekNumber int) objc.ID {
	_ret := objc.Send[objc.ID](o.Ptr(), _eKRecurrenceDayOfWeekSelInitWithDayOfTheWeekWeekNumber, dayOfTheWeek, weekNumber)
	return _ret
}

// @property   dayOfTheWeek @abstract   The day of the week.
func (o *EKRecurrenceDayOfWeek) DayOfTheWeek() EKWeekday {
	_ret := objc.Send[EKWeekday](o.Ptr(), _eKRecurrenceDayOfWeekSelDayOfTheWeek)
	return _ret
}

// @property   weekNumber @abstract   The week number.
func (o *EKRecurrenceDayOfWeek) WeekNumber() int {
	_ret := objc.Send[int](o.Ptr(), _eKRecurrenceDayOfWeekSelWeekNumber)
	return _ret
}
