// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package appkit

import (
	"unsafe"

	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/corefoundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
)

// Apple documentation: https://developer.apple.com/documentation/appkit/nsmenu
type NSMenu struct {
	foundation.NSObject
}

var (
	_clsNSMenu = _objcClass("NSMenu")
	_nSMenuSelInitWithTitle = objc.RegisterName("initWithTitle:")
	_nSMenuSelInitWithCoder = objc.RegisterName("initWithCoder:")
	_nSMenuSelPopUpContextMenuWithEventForView = objc.RegisterName("popUpContextMenu:withEvent:forView:")
	_nSMenuSelPopUpContextMenuWithEventForViewWithFont = objc.RegisterName("popUpContextMenu:withEvent:forView:withFont:")
	_nSMenuSelPopUpMenuPositioningItemAtLocationInView = objc.RegisterName("popUpMenuPositioningItem:atLocation:inView:")
	_nSMenuSelSetMenuBarVisible = objc.RegisterName("setMenuBarVisible:")
	_nSMenuSelMenuBarVisible = objc.RegisterName("menuBarVisible")
	_nSMenuSelInsertItemAtIndex = objc.RegisterName("insertItem:atIndex:")
	_nSMenuSelAddItem = objc.RegisterName("addItem:")
	_nSMenuSelInsertItemWithTitleActionKeyEquivalentAtIndex = objc.RegisterName("insertItemWithTitle:action:keyEquivalent:atIndex:")
	_nSMenuSelAddItemWithTitleActionKeyEquivalent = objc.RegisterName("addItemWithTitle:action:keyEquivalent:")
	_nSMenuSelRemoveItemAtIndex = objc.RegisterName("removeItemAtIndex:")
	_nSMenuSelRemoveItem = objc.RegisterName("removeItem:")
	_nSMenuSelSetSubmenuForItem = objc.RegisterName("setSubmenu:forItem:")
	_nSMenuSelRemoveAllItems = objc.RegisterName("removeAllItems")
	_nSMenuSelItemAtIndex = objc.RegisterName("itemAtIndex:")
	_nSMenuSelIndexOfItem = objc.RegisterName("indexOfItem:")
	_nSMenuSelIndexOfItemWithTitle = objc.RegisterName("indexOfItemWithTitle:")
	_nSMenuSelIndexOfItemWithTag = objc.RegisterName("indexOfItemWithTag:")
	_nSMenuSelIndexOfItemWithRepresentedObject = objc.RegisterName("indexOfItemWithRepresentedObject:")
	_nSMenuSelIndexOfItemWithSubmenu = objc.RegisterName("indexOfItemWithSubmenu:")
	_nSMenuSelIndexOfItemWithTargetAndAction = objc.RegisterName("indexOfItemWithTarget:andAction:")
	_nSMenuSelItemWithTitle = objc.RegisterName("itemWithTitle:")
	_nSMenuSelItemWithTag = objc.RegisterName("itemWithTag:")
	_nSMenuSelUpdate = objc.RegisterName("update")
	_nSMenuSelPerformKeyEquivalent = objc.RegisterName("performKeyEquivalent:")
	_nSMenuSelItemChanged = objc.RegisterName("itemChanged:")
	_nSMenuSelPerformActionForItemAtIndex = objc.RegisterName("performActionForItemAtIndex:")
	_nSMenuSelCancelTracking = objc.RegisterName("cancelTracking")
	_nSMenuSelCancelTrackingWithoutAnimation = objc.RegisterName("cancelTrackingWithoutAnimation")
	_nSMenuSelTitle = objc.RegisterName("title")
	_nSMenuSelSetTitle = objc.RegisterName("setTitle:")
	_nSMenuSelSupermenu = objc.RegisterName("supermenu")
	_nSMenuSelSetSupermenu = objc.RegisterName("setSupermenu:")
	_nSMenuSelItemArray = objc.RegisterName("itemArray")
	_nSMenuSelSetItemArray = objc.RegisterName("setItemArray:")
	_nSMenuSelNumberOfItems = objc.RegisterName("numberOfItems")
	_nSMenuSelAutoenablesItems = objc.RegisterName("autoenablesItems")
	_nSMenuSelSetAutoenablesItems = objc.RegisterName("setAutoenablesItems:")
	_nSMenuSelDelegate = objc.RegisterName("delegate")
	_nSMenuSelSetDelegate = objc.RegisterName("setDelegate:")
	_nSMenuSelMenuBarHeight = objc.RegisterName("menuBarHeight")
	_nSMenuSelHighlightedItem = objc.RegisterName("highlightedItem")
	_nSMenuSelMinimumWidth = objc.RegisterName("minimumWidth")
	_nSMenuSelSetMinimumWidth = objc.RegisterName("setMinimumWidth:")
	_nSMenuSelSize = objc.RegisterName("size")
	_nSMenuSelFont = objc.RegisterName("font")
	_nSMenuSelSetFont = objc.RegisterName("setFont:")
	_nSMenuSelAllowsContextMenuPlugIns = objc.RegisterName("allowsContextMenuPlugIns")
	_nSMenuSelSetAllowsContextMenuPlugIns = objc.RegisterName("setAllowsContextMenuPlugIns:")
	_nSMenuSelAutomaticallyInsertsWritingToolsItems = objc.RegisterName("automaticallyInsertsWritingToolsItems")
	_nSMenuSelSetAutomaticallyInsertsWritingToolsItems = objc.RegisterName("setAutomaticallyInsertsWritingToolsItems:")
	_nSMenuSelShowsStateColumn = objc.RegisterName("showsStateColumn")
	_nSMenuSelSetShowsStateColumn = objc.RegisterName("setShowsStateColumn:")
	_nSMenuSelUserInterfaceLayoutDirection = objc.RegisterName("userInterfaceLayoutDirection")
	_nSMenuSelSetUserInterfaceLayoutDirection = objc.RegisterName("setUserInterfaceLayoutDirection:")
	_nSMenuSelPaletteMenuWithColorsTitlesSelectionHandler = objc.RegisterName("paletteMenuWithColors:titles:selectionHandler:")
	_nSMenuSelPaletteMenuWithColorsTitlesTemplateImageSelectionHandler = objc.RegisterName("paletteMenuWithColors:titles:templateImage:selectionHandler:")
	_nSMenuSelPresentationStyle = objc.RegisterName("presentationStyle")
	_nSMenuSelSetPresentationStyle = objc.RegisterName("setPresentationStyle:")
	_nSMenuSelSelectionMode = objc.RegisterName("selectionMode")
	_nSMenuSelSetSelectionMode = objc.RegisterName("setSelectionMode:")
	_nSMenuSelSelectedItems = objc.RegisterName("selectedItems")
	_nSMenuSelSetSelectedItems = objc.RegisterName("setSelectedItems:")
	_nSMenuSelSubmenuAction = objc.RegisterName("submenuAction:")
	_nSMenuSelPropertiesToUpdate = objc.RegisterName("propertiesToUpdate")
	_nSMenuSelSetMenuRepresentation = objc.RegisterName("setMenuRepresentation:")
	_nSMenuSelMenuRepresentation = objc.RegisterName("menuRepresentation")
	_nSMenuSelSetContextMenuRepresentation = objc.RegisterName("setContextMenuRepresentation:")
	_nSMenuSelContextMenuRepresentation = objc.RegisterName("contextMenuRepresentation")
	_nSMenuSelSetTearOffMenuRepresentation = objc.RegisterName("setTearOffMenuRepresentation:")
	_nSMenuSelTearOffMenuRepresentation = objc.RegisterName("tearOffMenuRepresentation")
	_nSMenuSelMenuZone = objc.RegisterName("menuZone")
	_nSMenuSelSetMenuZone = objc.RegisterName("setMenuZone:")
	_nSMenuSelAttachedMenu = objc.RegisterName("attachedMenu")
	_nSMenuSelIsAttached = objc.RegisterName("isAttached")
	_nSMenuSelSizeToFit = objc.RegisterName("sizeToFit")
	_nSMenuSelLocationForSubmenu = objc.RegisterName("locationForSubmenu:")
	_nSMenuSelHelpRequested = objc.RegisterName("helpRequested:")
	_nSMenuSelMenuChangedMessagesEnabled = objc.RegisterName("menuChangedMessagesEnabled")
	_nSMenuSelSetMenuChangedMessagesEnabled = objc.RegisterName("setMenuChangedMessagesEnabled:")
	_nSMenuSelIsTornOff = objc.RegisterName("isTornOff")
)

func NSMenuFromID(id objc.ID) *NSMenu {
	if id == 0 {
		return nil
	}
	o := &NSMenu{}
	o.InitPtr(id)
	purego.Track(o)
	return o
}

func (o *NSMenu) InitWithTitle(title *foundation.NSString) *NSMenu {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelInitWithTitle, title.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

func (o *NSMenu) InitWithCoder(coder *foundation.NSCoder) *NSMenu {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelInitWithCoder, coder.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

func NSMenuPopUpContextMenuWithEventForView(menu *NSMenu, event *NSEvent, view *NSView) {
	objc.ID(_clsNSMenu).Send(_nSMenuSelPopUpContextMenuWithEventForView, menu.Ptr(), event.Ptr(), view.Ptr())
}

func NSMenuPopUpContextMenuWithEventForViewWithFont(menu *NSMenu, event *NSEvent, view *NSView, font *NSFont) {
	objc.ID(_clsNSMenu).Send(_nSMenuSelPopUpContextMenuWithEventForViewWithFont, menu.Ptr(), event.Ptr(), view.Ptr(), font.Ptr())
}

func (o *NSMenu) PopUpMenuPositioningItemAtLocationInView(item *NSMenuItem, location corefoundation.CGPoint, view *NSView) bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelPopUpMenuPositioningItemAtLocationInView, item.Ptr(), location, view.Ptr())
	return _ret
}

func NSMenuSetMenuBarVisible(visible bool) {
	objc.ID(_clsNSMenu).Send(_nSMenuSelSetMenuBarVisible, visible)
}

func NSMenuMenuBarVisible() bool {
	_ret := objc.Send[bool](objc.ID(_clsNSMenu), _nSMenuSelMenuBarVisible)
	return _ret
}

func (o *NSMenu) InsertItemAtIndex(newItem *NSMenuItem, index int) {
	o.Ptr().Send(_nSMenuSelInsertItemAtIndex, newItem.Ptr(), index)
}

func (o *NSMenu) AddItem(newItem *NSMenuItem) {
	o.Ptr().Send(_nSMenuSelAddItem, newItem.Ptr())
}

func (o *NSMenu) InsertItemWithTitleActionKeyEquivalentAtIndex(string_ *foundation.NSString, selector objc.SEL, charCode *foundation.NSString, index int) *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelInsertItemWithTitleActionKeyEquivalentAtIndex, string_.Ptr(), selector, charCode.Ptr(), index)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) AddItemWithTitleActionKeyEquivalent(string_ *foundation.NSString, selector objc.SEL, charCode *foundation.NSString) *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelAddItemWithTitleActionKeyEquivalent, string_.Ptr(), selector, charCode.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) RemoveItemAtIndex(index int) {
	o.Ptr().Send(_nSMenuSelRemoveItemAtIndex, index)
}

func (o *NSMenu) RemoveItem(item *NSMenuItem) {
	o.Ptr().Send(_nSMenuSelRemoveItem, item.Ptr())
}

func (o *NSMenu) SetSubmenuForItem(menu *NSMenu, item *NSMenuItem) {
	o.Ptr().Send(_nSMenuSelSetSubmenuForItem, menu.Ptr(), item.Ptr())
}

func (o *NSMenu) RemoveAllItems() {
	o.Ptr().Send(_nSMenuSelRemoveAllItems)
}

func (o *NSMenu) ItemAtIndex(index int) *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelItemAtIndex, index)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) IndexOfItem(item *NSMenuItem) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItem, item.Ptr())
	return _ret
}

func (o *NSMenu) IndexOfItemWithTitle(title *foundation.NSString) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItemWithTitle, title.Ptr())
	return _ret
}

func (o *NSMenu) IndexOfItemWithTag(tag int) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItemWithTag, tag)
	return _ret
}

func (o *NSMenu) IndexOfItemWithRepresentedObject(object objc.ID) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItemWithRepresentedObject, object)
	return _ret
}

func (o *NSMenu) IndexOfItemWithSubmenu(submenu *NSMenu) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItemWithSubmenu, submenu.Ptr())
	return _ret
}

func (o *NSMenu) IndexOfItemWithTargetAndAction(target objc.ID, actionSelector objc.SEL) int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelIndexOfItemWithTargetAndAction, target, actionSelector)
	return _ret
}

func (o *NSMenu) ItemWithTitle(title *foundation.NSString) *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelItemWithTitle, title.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) ItemWithTag(tag int) *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelItemWithTag, tag)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) Update() {
	o.Ptr().Send(_nSMenuSelUpdate)
}

func (o *NSMenu) PerformKeyEquivalent(event *NSEvent) bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelPerformKeyEquivalent, event.Ptr())
	return _ret
}

func (o *NSMenu) ItemChanged(item *NSMenuItem) {
	o.Ptr().Send(_nSMenuSelItemChanged, item.Ptr())
}

func (o *NSMenu) PerformActionForItemAtIndex(index int) {
	o.Ptr().Send(_nSMenuSelPerformActionForItemAtIndex, index)
}

func (o *NSMenu) CancelTracking() {
	o.Ptr().Send(_nSMenuSelCancelTracking)
}

func (o *NSMenu) CancelTrackingWithoutAnimation() {
	o.Ptr().Send(_nSMenuSelCancelTrackingWithoutAnimation)
}

func (o *NSMenu) Title() *foundation.NSString {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelTitle)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return foundation.NSStringFromID(_ret)
}

func (o *NSMenu) SetTitle(title *foundation.NSString) {
	o.Ptr().Send(_nSMenuSelSetTitle, title.Ptr())
}

func (o *NSMenu) Supermenu() *NSMenu {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelSupermenu)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

func (o *NSMenu) SetSupermenu(supermenu *NSMenu) {
	o.Ptr().Send(_nSMenuSelSetSupermenu, supermenu.Ptr())
}

func (o *NSMenu) ItemArray() *foundation.NSArray[*NSMenuItem] {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelItemArray)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return foundation.NSArrayFromID[*NSMenuItem](_ret)
}

func (o *NSMenu) SetItemArray(itemArray *foundation.NSArray[*NSMenuItem]) {
	o.Ptr().Send(_nSMenuSelSetItemArray, itemArray.Ptr())
}

func (o *NSMenu) NumberOfItems() int {
	_ret := objc.Send[int](o.Ptr(), _nSMenuSelNumberOfItems)
	return _ret
}

func (o *NSMenu) AutoenablesItems() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelAutoenablesItems)
	return _ret
}

func (o *NSMenu) SetAutoenablesItems(autoenablesItems bool) {
	o.Ptr().Send(_nSMenuSelSetAutoenablesItems, autoenablesItems)
}

func (o *NSMenu) Delegate() NSMenuDelegate {
	_ret := objc.Send[NSMenuDelegate](o.Ptr(), _nSMenuSelDelegate)
	return _ret
}

func (o *NSMenu) SetDelegate(delegate NSMenuDelegate) {
	o.Ptr().Send(_nSMenuSelSetDelegate, delegate)
}

func (o *NSMenu) MenuBarHeight() float64 {
	_ret := objc.Send[float64](o.Ptr(), _nSMenuSelMenuBarHeight)
	return _ret
}

func (o *NSMenu) HighlightedItem() *NSMenuItem {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelHighlightedItem)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuItemFromID(_ret)
}

func (o *NSMenu) MinimumWidth() float64 {
	_ret := objc.Send[float64](o.Ptr(), _nSMenuSelMinimumWidth)
	return _ret
}

func (o *NSMenu) SetMinimumWidth(minimumWidth float64) {
	o.Ptr().Send(_nSMenuSelSetMinimumWidth, minimumWidth)
}

func (o *NSMenu) Size() corefoundation.CGSize {
	_ret := objc.Send[corefoundation.CGSize](o.Ptr(), _nSMenuSelSize)
	return _ret
}

func (o *NSMenu) Font() *NSFont {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelFont)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSFontFromID(_ret)
}

func (o *NSMenu) SetFont(font *NSFont) {
	o.Ptr().Send(_nSMenuSelSetFont, font.Ptr())
}

func (o *NSMenu) AllowsContextMenuPlugIns() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelAllowsContextMenuPlugIns)
	return _ret
}

func (o *NSMenu) SetAllowsContextMenuPlugIns(allowsContextMenuPlugIns bool) {
	o.Ptr().Send(_nSMenuSelSetAllowsContextMenuPlugIns, allowsContextMenuPlugIns)
}

func (o *NSMenu) AutomaticallyInsertsWritingToolsItems() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelAutomaticallyInsertsWritingToolsItems)
	return _ret
}

func (o *NSMenu) SetAutomaticallyInsertsWritingToolsItems(automaticallyInsertsWritingToolsItems bool) {
	o.Ptr().Send(_nSMenuSelSetAutomaticallyInsertsWritingToolsItems, automaticallyInsertsWritingToolsItems)
}

func (o *NSMenu) ShowsStateColumn() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelShowsStateColumn)
	return _ret
}

func (o *NSMenu) SetShowsStateColumn(showsStateColumn bool) {
	o.Ptr().Send(_nSMenuSelSetShowsStateColumn, showsStateColumn)
}

func (o *NSMenu) UserInterfaceLayoutDirection() NSUserInterfaceLayoutDirection {
	_ret := objc.Send[NSUserInterfaceLayoutDirection](o.Ptr(), _nSMenuSelUserInterfaceLayoutDirection)
	return _ret
}

func (o *NSMenu) SetUserInterfaceLayoutDirection(userInterfaceLayoutDirection NSUserInterfaceLayoutDirection) {
	o.Ptr().Send(_nSMenuSelSetUserInterfaceLayoutDirection, userInterfaceLayoutDirection)
}

// Creates a palette menu displaying user-selectable color tags using the provided array of colors and optional titles. Note that the palette menu is configured for display as an inline menu; you must set it as the submenu of another menu item, contained in a standard menu. The palette menu cannot be used to invoke the `popUpMenuPositioningItem` method, or attached directly to a popup button or toolbar item. @return An autoconfigured palette menu.
func NSMenuPaletteMenuWithColorsTitlesSelectionHandler(colors *foundation.NSArray[*NSColor], itemTitles *foundation.NSArray[*foundation.NSString], onSelectionChange func(*NSMenu)) *NSMenu {
	var __block_onSelectionChange objc.Block
	if onSelectionChange != nil {
		__block_onSelectionChange = objc.NewBlock(func(_ objc.Block, blockParam0 objc.ID) {
			if blockParam0 != 0 {
				blockParam0.Send(objc.RegisterName("retain"))
			}
			onSelectionChange(NSMenuFromID(blockParam0))
		})
		defer __block_onSelectionChange.Release()
	}
	_ret := objc.Send[objc.ID](objc.ID(_clsNSMenu), _nSMenuSelPaletteMenuWithColorsTitlesSelectionHandler, colors.Ptr(), itemTitles, __block_onSelectionChange)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

// Creates a palette menu displaying user-selectable color tags using the provided template image, tinted using the specified array of colors. Optionally allows observing changes to the selection state in the compact menu. The block is invoked after the selection has been updated. Currently selected items can be retrieved from the `selectedItems` property. Note that the palette menu is configured for display as an inline menu; you must set it as the submenu of another menu item, contained in a standard menu. The palette menu cannot be used to invoke the `popUpMenuPositioningItem` method, or attached directly to a popup button or toolbar item. @return An autoconfigured palette menu.
func NSMenuPaletteMenuWithColorsTitlesTemplateImageSelectionHandler(colors *foundation.NSArray[*NSColor], itemTitles *foundation.NSArray[*foundation.NSString], image *NSImage, onSelectionChange func(*NSMenu)) *NSMenu {
	var __block_onSelectionChange objc.Block
	if onSelectionChange != nil {
		__block_onSelectionChange = objc.NewBlock(func(_ objc.Block, blockParam0 objc.ID) {
			if blockParam0 != 0 {
				blockParam0.Send(objc.RegisterName("retain"))
			}
			onSelectionChange(NSMenuFromID(blockParam0))
		})
		defer __block_onSelectionChange.Release()
	}
	_ret := objc.Send[objc.ID](objc.ID(_clsNSMenu), _nSMenuSelPaletteMenuWithColorsTitlesTemplateImageSelectionHandler, colors.Ptr(), itemTitles, image.Ptr(), __block_onSelectionChange)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

// The presentation style of the menu. @note This property is not respected if the menu is the main menu of the app.
func (o *NSMenu) PresentationStyle() NSMenuPresentationStyle {
	_ret := objc.Send[NSMenuPresentationStyle](o.Ptr(), _nSMenuSelPresentationStyle)
	return _ret
}

// The presentation style of the menu. @note This property is not respected if the menu is the main menu of the app.
func (o *NSMenu) SetPresentationStyle(presentationStyle NSMenuPresentationStyle) {
	o.Ptr().Send(_nSMenuSelSetPresentationStyle, presentationStyle)
}

// The selection mode of the menu. Note the selection mode only has effect on menu items that belong to the same selection group. A selection group consists of the items with the same target/action.
func (o *NSMenu) SelectionMode() NSMenuSelectionMode {
	_ret := objc.Send[NSMenuSelectionMode](o.Ptr(), _nSMenuSelSelectionMode)
	return _ret
}

// The selection mode of the menu. Note the selection mode only has effect on menu items that belong to the same selection group. A selection group consists of the items with the same target/action.
func (o *NSMenu) SetSelectionMode(selectionMode NSMenuSelectionMode) {
	o.Ptr().Send(_nSMenuSelSetSelectionMode, selectionMode)
}

// The menu items that are selected. An item is selected when its state is `NSControl.StateValue.on`. @note This property is settable. Setting `selectedItems` will select any items that are contained in the provided array, and deselect any previously selected items that are not in the array.
func (o *NSMenu) SelectedItems() *foundation.NSArray[*NSMenuItem] {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelSelectedItems)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return foundation.NSArrayFromID[*NSMenuItem](_ret)
}

// The menu items that are selected. An item is selected when its state is `NSControl.StateValue.on`. @note This property is settable. Setting `selectedItems` will select any items that are contained in the provided array, and deselect any previously selected items that are not in the array.
func (o *NSMenu) SetSelectedItems(selectedItems *foundation.NSArray[*NSMenuItem]) {
	o.Ptr().Send(_nSMenuSelSetSelectedItems, selectedItems.Ptr())
}

func (o *NSMenu) SubmenuAction(sender objc.ID) {
	o.Ptr().Send(_nSMenuSelSubmenuAction, sender)
}

func (o *NSMenu) PropertiesToUpdate() NSMenuProperties {
	_ret := objc.Send[NSMenuProperties](o.Ptr(), _nSMenuSelPropertiesToUpdate)
	return _ret
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) SetMenuRepresentation(menuRep objc.ID) {
	o.Ptr().Send(_nSMenuSelSetMenuRepresentation, menuRep)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) MenuRepresentation() objc.ID {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelMenuRepresentation)
	return _ret
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) SetContextMenuRepresentation(menuRep objc.ID) {
	o.Ptr().Send(_nSMenuSelSetContextMenuRepresentation, menuRep)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) ContextMenuRepresentation() objc.ID {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelContextMenuRepresentation)
	return _ret
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) SetTearOffMenuRepresentation(menuRep objc.ID) {
	o.Ptr().Send(_nSMenuSelSetTearOffMenuRepresentation, menuRep)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) TearOffMenuRepresentation() objc.ID {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelTearOffMenuRepresentation)
	return _ret
}

// Deprecated: since macOS 10.11.
func NSMenuMenuZone() unsafe.Pointer {
	_ret := objc.Send[unsafe.Pointer](objc.ID(_clsNSMenu), _nSMenuSelMenuZone)
	return _ret
}

// Deprecated: since macOS 10.2.
func NSMenuSetMenuZone(zone unsafe.Pointer) {
	objc.ID(_clsNSMenu).Send(_nSMenuSelSetMenuZone, zone)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) AttachedMenu() *NSMenu {
	_ret := objc.Send[objc.ID](o.Ptr(), _nSMenuSelAttachedMenu)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return NSMenuFromID(_ret)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) IsAttached() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelIsAttached)
	return _ret
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) SizeToFit() {
	o.Ptr().Send(_nSMenuSelSizeToFit)
}

// Deprecated: since macOS 10.2.
func (o *NSMenu) LocationForSubmenu(submenu *NSMenu) corefoundation.CGPoint {
	_ret := objc.Send[corefoundation.CGPoint](o.Ptr(), _nSMenuSelLocationForSubmenu, submenu.Ptr())
	return _ret
}

// Deprecated: since macOS 10.11.
func (o *NSMenu) HelpRequested(eventPtr *NSEvent) {
	o.Ptr().Send(_nSMenuSelHelpRequested, eventPtr.Ptr())
}

// Deprecated: since macOS 10.11.
func (o *NSMenu) MenuChangedMessagesEnabled() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelMenuChangedMessagesEnabled)
	return _ret
}

// Deprecated: since macOS 10.11.
func (o *NSMenu) SetMenuChangedMessagesEnabled(menuChangedMessagesEnabled bool) {
	o.Ptr().Send(_nSMenuSelSetMenuChangedMessagesEnabled, menuChangedMessagesEnabled)
}

// Deprecated: since macOS 10.11.
func (o *NSMenu) IsTornOff() bool {
	_ret := objc.Send[bool](o.Ptr(), _nSMenuSelIsTornOff)
	return _ret
}

