// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package coreaudiokit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/carboncore"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/coreaudiokit"
	"github.com/ebitengine/purego/objc"
)

// AUGenericView wraps [raw.AUGenericView] with a fluent Go API.
type AUGenericView struct {
	inner *raw.AUGenericView
}

// Unwrap returns the underlying [raw.AUGenericView].
func (x *AUGenericView) Unwrap() *raw.AUGenericView { return x.inner }

// NewAUGenericViewWithAudioUnit creates a new [AUGenericView].
func NewAUGenericViewWithAudioUnit(au *carboncore.ComponentInstanceRecord) *AUGenericView {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("AUGenericView")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithAudioUnit:"), au)
	return &AUGenericView{inner: raw.AUGenericViewFromID(_id)}
}

// NewAUGenericViewWithAudioUnitDisplayFlags creates a new [AUGenericView].
func NewAUGenericViewWithAudioUnitDisplayFlags(inAudioUnit *carboncore.ComponentInstanceRecord, inFlags raw.AUGenericViewDisplayFlags) *AUGenericView {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("AUGenericView")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithAudioUnit:displayFlags:"), inAudioUnit, inFlags)
	return &AUGenericView{inner: raw.AUGenericViewFromID(_id)}
}

// WithShowsExpertParameters sets the showsExpertParameters property and returns the receiver for chaining.
func (x *AUGenericView) WithShowsExpertParameters(showsExpertParameters bool) *AUGenericView {
	x.inner.SetShowsExpertParameters(showsExpertParameters)
	return x
}

