// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package phase

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/avfaudio"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/phase"
	"github.com/ebitengine/purego/objc"
)

// A central repository of audio assets.
//
// AssetRegistry wraps [raw.PHASEAssetRegistry] with a fluent Go API.
type AssetRegistry struct {
	inner *raw.PHASEAssetRegistry
}

// Unwrap returns the underlying [raw.PHASEAssetRegistry].
func (x *AssetRegistry) Unwrap() *raw.PHASEAssetRegistry { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *AssetRegistry) ID() objc.ID { return x.inner.Ptr() }

// AssetRegistryFromID adopts an existing object pointer as a AssetRegistry (nil for 0).
func AssetRegistryFromID(id objc.ID) *AssetRegistry {
	if id == 0 {
		return nil
	}
	return &AssetRegistry{inner: raw.PHASEAssetRegistryFromID(id)}
}

// NewAssetRegistry creates a new [AssetRegistry].
func NewAssetRegistry() *AssetRegistry {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("PHASEAssetRegistry")), objc.RegisterName("new"))
	return &AssetRegistry{inner: raw.PHASEAssetRegistryFromID(_id)}
}

// Registers a global metaparameter with the asset registry.
//
// RegisterGlobalMetaParameterError calls the underlying RegisterGlobalMetaParameterError.
func (x *AssetRegistry) RegisterGlobalMetaParameterError(metaParameterDefinition *raw.PHASEMetaParameterDefinition) (*GlobalMetaParameterAsset, error) {
	_r, _err := x.inner.RegisterGlobalMetaParameterError(metaParameterDefinition)
	if _err != nil {
		return nil, _err
	}
	if _r == nil {
		return nil, nil
	}
	return &GlobalMetaParameterAsset{inner: _r}, nil
}

// Registers the root node of the sound event asset.
//
// RegisterSoundEventAssetWithRootNodeIdentifierError calls the underlying RegisterSoundEventAssetWithRootNodeIdentifierError.
func (x *AssetRegistry) RegisterSoundEventAssetWithRootNodeIdentifierError(rootNode *raw.PHASESoundEventNodeDefinition, identifier string) (*SoundEventNodeAsset, error) {
	_r, _err := x.inner.RegisterSoundEventAssetWithRootNodeIdentifierError(rootNode, foundation.NSStringStringWithUTF8String(identifier))
	if _err != nil {
		return nil, _err
	}
	if _r == nil {
		return nil, nil
	}
	return &SoundEventNodeAsset{inner: _r}, nil
}

// Loads a sound asset from the argument URL and adds it to the engine’s list of registered assets.
//
// RegisterSoundAssetAtURLIdentifierAssetTypeChannelLayoutNormalizationModeError calls the underlying RegisterSoundAssetAtURLIdentifierAssetTypeChannelLayoutNormalizationModeError.
func (x *AssetRegistry) RegisterSoundAssetAtURLIdentifierAssetTypeChannelLayoutNormalizationModeError(url string, identifier string, assetType PHASEAssetType, channelLayout *avfaudio.AVAudioChannelLayout, normalizationMode PHASENormalizationMode) (*SoundAsset, error) {
	_r, _err := x.inner.RegisterSoundAssetAtURLIdentifierAssetTypeChannelLayoutNormalizationModeError(foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(url)), foundation.NSStringStringWithUTF8String(identifier), raw.PHASEAssetType(assetType), channelLayout, raw.PHASENormalizationMode(normalizationMode))
	if _err != nil {
		return nil, _err
	}
	if _r == nil {
		return nil, nil
	}
	return &SoundAsset{inner: _r}, nil
}

// Loads a sound asset from memory and adds it to the engine’s list of registered assets.
//
// RegisterSoundAssetWithDataIdentifierFormatNormalizationModeError calls the underlying RegisterSoundAssetWithDataIdentifierFormatNormalizationModeError.
func (x *AssetRegistry) RegisterSoundAssetWithDataIdentifierFormatNormalizationModeError(data *foundation.NSData, identifier string, format *avfaudio.AVAudioFormat, normalizationMode PHASENormalizationMode) (*SoundAsset, error) {
	_r, _err := x.inner.RegisterSoundAssetWithDataIdentifierFormatNormalizationModeError(data, foundation.NSStringStringWithUTF8String(identifier), format, raw.PHASENormalizationMode(normalizationMode))
	if _err != nil {
		return nil, _err
	}
	if _r == nil {
		return nil, nil
	}
	return &SoundAsset{inner: _r}, nil
}

// Deallocates system memory for a given asset and removes it from the engine’s list of registered assets.
//
// UnregisterAssetWithIdentifierCompletion calls the underlying UnregisterAssetWithIdentifierCompletion.
func (x *AssetRegistry) UnregisterAssetWithIdentifierCompletion(identifier string, handler func(bool)) {
	x.inner.UnregisterAssetWithIdentifierCompletion(foundation.NSStringStringWithUTF8String(identifier), handler)
}

// Provides the asset named with the designated identifier.
//
// AssetForIdentifier calls the underlying AssetForIdentifier.
func (x *AssetRegistry) AssetForIdentifier(identifier string) *Asset {
	_r := x.inner.AssetForIdentifier(foundation.NSStringStringWithUTF8String(identifier))
	if _r == nil {
		return nil
	}
	return &Asset{inner: _r}
}

// GlobalMetaParameters calls the underlying GlobalMetaParameters.
func (x *AssetRegistry) GlobalMetaParameters() *foundation.NSDictionary[*foundation.NSString, *raw.PHASEMetaParameter] {
	return x.inner.GlobalMetaParameters()
}

// AssetRegistryable is the interface implemented by [AssetRegistry], for mocking and DI.
type AssetRegistryable interface {
	Unwrap() *raw.PHASEAssetRegistry
	RegisterGlobalMetaParameterError(metaParameterDefinition *raw.PHASEMetaParameterDefinition) (*GlobalMetaParameterAsset, error)
	RegisterSoundEventAssetWithRootNodeIdentifierError(rootNode *raw.PHASESoundEventNodeDefinition, identifier string) (*SoundEventNodeAsset, error)
	RegisterSoundAssetAtURLIdentifierAssetTypeChannelLayoutNormalizationModeError(url string, identifier string, assetType PHASEAssetType, channelLayout *avfaudio.AVAudioChannelLayout, normalizationMode PHASENormalizationMode) (*SoundAsset, error)
	RegisterSoundAssetWithDataIdentifierFormatNormalizationModeError(data *foundation.NSData, identifier string, format *avfaudio.AVAudioFormat, normalizationMode PHASENormalizationMode) (*SoundAsset, error)
	UnregisterAssetWithIdentifierCompletion(identifier string, handler func(bool))
	AssetForIdentifier(identifier string) *Asset
	GlobalMetaParameters() *foundation.NSDictionary[*foundation.NSString, *raw.PHASEMetaParameter]
}

var _ AssetRegistryable = (*AssetRegistry)(nil)
