// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package phase

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// SpatialMixerDefinition is an idiomatic wrapper over the Objective-C class PHASESpatialMixerDefinition.
//
// It embeds [MixerDefinition], promoting that type's methods.
//
// An audio-layering object that produces environmental effects and plays sound with a 3D position and orientation.
type SpatialMixerDefinition struct {
	MixerDefinition
}

// SpatialMixerDefinitionFromID adopts an existing Objective-C object as a SpatialMixerDefinition
// (nil for 0), retaining it and registering a release finalizer.
func SpatialMixerDefinitionFromID(id objc.ID) *SpatialMixerDefinition {
	if id == 0 {
		return nil
	}
	x := &SpatialMixerDefinition{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// spatialMixerDefinitionAdopt wraps an Objective-C object that this code just created as a
// SpatialMixerDefinition (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func spatialMixerDefinitionAdopt(id objc.ID) *SpatialMixerDefinition {
	if id == 0 {
		return nil
	}
	x := &SpatialMixerDefinition{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewSpatialMixerDefinitionWithSpatialPipeline creates a mixer with the designated spatial pipeline.
func NewSpatialMixerDefinitionWithSpatialPipeline(spatialPipeline *SpatialPipeline) *SpatialMixerDefinition {
	_alloc := objc.Send[objc.ID](objc.ID(_class("PHASESpatialMixerDefinition")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithSpatialPipeline:"), objref.IDOf(spatialPipeline))
	return spatialMixerDefinitionAdopt(_id)
}

// NewSpatialMixerDefinitionWithSpatialPipelineIdentifier creates a named mixer with the designated spatial pipeline.
func NewSpatialMixerDefinitionWithSpatialPipelineIdentifier(spatialPipeline *SpatialPipeline, identifier string) *SpatialMixerDefinition {
	_alloc := objc.Send[objc.ID](objc.ID(_class("PHASESpatialMixerDefinition")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithSpatialPipeline:identifier:"), objref.IDOf(spatialPipeline), purego.NSString(identifier))
	return spatialMixerDefinitionAdopt(_id)
}

// WithDistanceModelParameters an effect that changes sound as it carries over a distance.
func (x *SpatialMixerDefinition) WithDistanceModelParameters(distanceModelParameters DistanceModelParametersProvider) *SpatialMixerDefinition {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDistanceModelParameters:"), objref.IDOf(distanceModelParameters))
	return x
}

// WithListenerDirectivityModelParameters a data set that determines how well the listener hears depending on its direction relative to a sound source.
func (x *SpatialMixerDefinition) WithListenerDirectivityModelParameters(listenerDirectivityModelParameters DirectivityModelParametersProvider) *SpatialMixerDefinition {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setListenerDirectivityModelParameters:"), objref.IDOf(listenerDirectivityModelParameters))
	return x
}

// WithSourceDirectivityModelParameters a data set that directs sound such that it’s louder when directed at the listener.
func (x *SpatialMixerDefinition) WithSourceDirectivityModelParameters(sourceDirectivityModelParameters DirectivityModelParametersProvider) *SpatialMixerDefinition {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setSourceDirectivityModelParameters:"), objref.IDOf(sourceDirectivityModelParameters))
	return x
}

// WithGain the mixer’s volume.
func (x *SpatialMixerDefinition) WithGain(gain float64) *SpatialMixerDefinition {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setGain:"), gain)
	return x
}

// WithGainMetaParameterDefinition a template for a parameter that changes the mixer’s volume gradually over a period of time.
func (x *SpatialMixerDefinition) WithGainMetaParameterDefinition(gainMetaParameterDefinition NumberMetaParameterDefinitionProvider) *SpatialMixerDefinition {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setGainMetaParameterDefinition:"), objref.IDOf(gainMetaParameterDefinition))
	return x
}

// SpatialPipeline spatial Pipeline.
func (x *SpatialMixerDefinition) SpatialPipeline() *SpatialPipeline {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("spatialPipeline"))
	return SpatialPipelineFromID(_r)
}

// DistanceModelParameters distance model parameters (optional).
func (x *SpatialMixerDefinition) DistanceModelParameters() *DistanceModelParameters {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("distanceModelParameters"))
	return DistanceModelParametersFromID(_r)
}

// SetDistanceModelParameters wraps the corresponding Objective-C method.
func (x *SpatialMixerDefinition) SetDistanceModelParameters(distanceModelParameters *DistanceModelParameters) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDistanceModelParameters:"), objref.IDOf(distanceModelParameters))
}

// ListenerDirectivityModelParameters listener directivity model parameters (optional).
func (x *SpatialMixerDefinition) ListenerDirectivityModelParameters() *DirectivityModelParameters {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("listenerDirectivityModelParameters"))
	return DirectivityModelParametersFromID(_r)
}

// SetListenerDirectivityModelParameters wraps the corresponding Objective-C method.
func (x *SpatialMixerDefinition) SetListenerDirectivityModelParameters(listenerDirectivityModelParameters *DirectivityModelParameters) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setListenerDirectivityModelParameters:"), objref.IDOf(listenerDirectivityModelParameters))
}

// SourceDirectivityModelParameters source directivity model parameters (optional).
func (x *SpatialMixerDefinition) SourceDirectivityModelParameters() *DirectivityModelParameters {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("sourceDirectivityModelParameters"))
	return DirectivityModelParametersFromID(_r)
}

// SetSourceDirectivityModelParameters wraps the corresponding Objective-C method.
func (x *SpatialMixerDefinition) SetSourceDirectivityModelParameters(sourceDirectivityModelParameters *DirectivityModelParameters) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setSourceDirectivityModelParameters:"), objref.IDOf(sourceDirectivityModelParameters))
}

// SpatialMixerDefinitionable is the interface implemented by [SpatialMixerDefinition], for mocking and DI.
type SpatialMixerDefinitionable interface {
	obj.Object
	WithDistanceModelParameters(distanceModelParameters DistanceModelParametersProvider) *SpatialMixerDefinition
	WithListenerDirectivityModelParameters(listenerDirectivityModelParameters DirectivityModelParametersProvider) *SpatialMixerDefinition
	WithSourceDirectivityModelParameters(sourceDirectivityModelParameters DirectivityModelParametersProvider) *SpatialMixerDefinition
	WithGain(gain float64) *SpatialMixerDefinition
	WithGainMetaParameterDefinition(gainMetaParameterDefinition NumberMetaParameterDefinitionProvider) *SpatialMixerDefinition
	SpatialPipeline() *SpatialPipeline
	DistanceModelParameters() *DistanceModelParameters
	SetDistanceModelParameters(distanceModelParameters *DistanceModelParameters)
	ListenerDirectivityModelParameters() *DirectivityModelParameters
	SetListenerDirectivityModelParameters(listenerDirectivityModelParameters *DirectivityModelParameters)
	SourceDirectivityModelParameters() *DirectivityModelParameters
	SetSourceDirectivityModelParameters(sourceDirectivityModelParameters *DirectivityModelParameters)
}

var _ SpatialMixerDefinitionable = (*SpatialMixerDefinition)(nil)

var _ MixerDefinitionProvider = (*SpatialMixerDefinition)(nil)

var _ DefinitionProvider = (*SpatialMixerDefinition)(nil)
