// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package imagekit

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// CameraDeviceView is an idiomatic wrapper over the Objective-C class IKCameraDeviceView.
type CameraDeviceView struct {
	objref.Handle
}

// CameraDeviceViewFromID adopts an existing Objective-C object as a CameraDeviceView
// (nil for 0), retaining it and registering a release finalizer.
func CameraDeviceViewFromID(id objc.ID) *CameraDeviceView {
	if id == 0 {
		return nil
	}
	x := &CameraDeviceView{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// cameraDeviceViewAdopt wraps an Objective-C object that this code just created as a
// CameraDeviceView (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func cameraDeviceViewAdopt(id objc.ID) *CameraDeviceView {
	if id == 0 {
		return nil
	}
	x := &CameraDeviceView{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *CameraDeviceView) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *CameraDeviceView) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *CameraDeviceView) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (x *CameraDeviceView) String() string {
	return rt.Description(objref.IDOf(x))
}

// NewCameraDeviceView creates a new CameraDeviceView.
func NewCameraDeviceView() *CameraDeviceView {
	_id := objc.Send[objc.ID](objc.ID(_class("IKCameraDeviceView")), objc.RegisterName("new"))
	return cameraDeviceViewAdopt(_id)
}

// WithCameraDevice the camera device.
func (x *CameraDeviceView) WithCameraDevice(cameraDevice obj.Object) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCameraDevice:"), objref.IDOf(cameraDevice))
	return x
}

// WithMode current display mode.
func (x *CameraDeviceView) WithMode(mode CameraDeviceViewDisplayMode) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setMode:"), mode)
	return x
}

// WithHasDisplayModeTable support table view display mode.
func (x *CameraDeviceView) WithHasDisplayModeTable(hasDisplayModeTable bool) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setHasDisplayModeTable:"), hasDisplayModeTable)
	return x
}

// WithHasDisplayModeIcon support icon view display mode.
func (x *CameraDeviceView) WithHasDisplayModeIcon(hasDisplayModeIcon bool) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setHasDisplayModeIcon:"), hasDisplayModeIcon)
	return x
}

// WithDownloadAllControlLabel label for the 'Download All' control - allows for example renaming to 'Import All'.
func (x *CameraDeviceView) WithDownloadAllControlLabel(downloadAllControlLabel string) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadAllControlLabel:"), purego.NSString(downloadAllControlLabel))
	return x
}

// WithDownloadSelectedControlLabel label for the 'Download Selected' control.
func (x *CameraDeviceView) WithDownloadSelectedControlLabel(downloadSelectedControlLabel string) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadSelectedControlLabel:"), purego.NSString(downloadSelectedControlLabel))
	return x
}

// WithIconSize in icon mode: size of the image thumbnails.
func (x *CameraDeviceView) WithIconSize(iconSize int) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setIconSize:"), iconSize)
	return x
}

// WithTransferMode transfer mode either file based - or - in memory.
func (x *CameraDeviceView) WithTransferMode(transferMode CameraDeviceViewTransferMode) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setTransferMode:"), transferMode)
	return x
}

// WithDisplaysDownloadsDirectoryControl show a downloads directory control.
func (x *CameraDeviceView) WithDisplaysDownloadsDirectoryControl(displaysDownloadsDirectoryControl bool) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDisplaysDownloadsDirectoryControl:"), displaysDownloadsDirectoryControl)
	return x
}

// WithDownloadsDirectory downloads directory.
func (x *CameraDeviceView) WithDownloadsDirectory(downloadsDirectory string) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadsDirectory:"), rt.FileURL(downloadsDirectory))
	return x
}

// WithDisplaysPostProcessApplicationControl show a postprocessing application control.
func (x *CameraDeviceView) WithDisplaysPostProcessApplicationControl(displaysPostProcessApplicationControl bool) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDisplaysPostProcessApplicationControl:"), displaysPostProcessApplicationControl)
	return x
}

// WithPostProcessApplication postprocessing application.
func (x *CameraDeviceView) WithPostProcessApplication(postProcessApplication string) *CameraDeviceView {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setPostProcessApplication:"), rt.FileURL(postProcessApplication))
	return x
}

// SelectedIndexes current user selection.
func (x *CameraDeviceView) SelectedIndexes() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("selectedIndexes"))
	return obj.Wrap(_r)
}

// SelectIndexesByExtendingSelection setting current user selection.
func (x *CameraDeviceView) SelectIndexesByExtendingSelection(indexes obj.Object, extend bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("selectIndexes:byExtendingSelection:"), objref.IDOf(indexes), extend)
}

// RotateLeft rotate selected items left.
func (x *CameraDeviceView) RotateLeft(sender obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("rotateLeft:"), objref.IDOf(sender))
}

// RotateRight rotate selected items right.
func (x *CameraDeviceView) RotateRight(sender obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("rotateRight:"), objref.IDOf(sender))
}

// DeleteSelectedItems delete selected items.
func (x *CameraDeviceView) DeleteSelectedItems(sender obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("deleteSelectedItems:"), objref.IDOf(sender))
}

// DownloadSelectedItems download selected items.
func (x *CameraDeviceView) DownloadSelectedItems(sender obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("downloadSelectedItems:"), objref.IDOf(sender))
}

// DownloadAllItems download all items.
func (x *CameraDeviceView) DownloadAllItems(sender obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("downloadAllItems:"), objref.IDOf(sender))
}

// SetCustomIconSizeSlider provide your own NSSlider to resize item thumbnails
func (x *CameraDeviceView) SetCustomIconSizeSlider(slider obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCustomIconSizeSlider:"), objref.IDOf(slider))
}

// SetCustomModeControl provide your own control to toggle between IKCameraDeviceViewDisplayMode table / icon
func (x *CameraDeviceView) SetCustomModeControl(control obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCustomModeControl:"), objref.IDOf(control))
}

// SetCustomActionControl provide your own control to toggle between IKCameraDeviceViewDisplayMode table / icon
func (x *CameraDeviceView) SetCustomActionControl(control obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCustomActionControl:"), objref.IDOf(control))
}

// SetCustomRotateControl provide your own control to rotate items (multiple of 90º)
func (x *CameraDeviceView) SetCustomRotateControl(control obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCustomRotateControl:"), objref.IDOf(control))
}

// SetCustomDeleteControl provide your own control to delete selected items
func (x *CameraDeviceView) SetCustomDeleteControl(control obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCustomDeleteControl:"), objref.IDOf(control))
}

// SetShowStatusInfoAsWindowSubtitle display status info as window subtitle
func (x *CameraDeviceView) SetShowStatusInfoAsWindowSubtitle(value bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShowStatusInfoAsWindowSubtitle:"), value)
}

// CameraDevice the camera device.
func (x *CameraDeviceView) CameraDevice() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("cameraDevice"))
	return obj.Wrap(_r)
}

// SetCameraDevice wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetCameraDevice(cameraDevice obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCameraDevice:"), objref.IDOf(cameraDevice))
}

// Mode current display mode.
func (x *CameraDeviceView) Mode() CameraDeviceViewDisplayMode {
	_r := objc.Send[CameraDeviceViewDisplayMode](objref.IDOf(x), objc.RegisterName("mode"))
	return _r
}

// SetMode wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetMode(mode CameraDeviceViewDisplayMode) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setMode:"), mode)
}

// HasDisplayModeTable support table view display mode.
func (x *CameraDeviceView) HasDisplayModeTable() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("hasDisplayModeTable"))
	return _r
}

// SetHasDisplayModeTable wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetHasDisplayModeTable(hasDisplayModeTable bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setHasDisplayModeTable:"), hasDisplayModeTable)
}

// HasDisplayModeIcon support icon view display mode.
func (x *CameraDeviceView) HasDisplayModeIcon() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("hasDisplayModeIcon"))
	return _r
}

// SetHasDisplayModeIcon wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetHasDisplayModeIcon(hasDisplayModeIcon bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setHasDisplayModeIcon:"), hasDisplayModeIcon)
}

// DownloadAllControlLabel label for the 'Download All' control - allows for example renaming to 'Import All'.
func (x *CameraDeviceView) DownloadAllControlLabel() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("downloadAllControlLabel"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

// SetDownloadAllControlLabel wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetDownloadAllControlLabel(downloadAllControlLabel string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadAllControlLabel:"), purego.NSString(downloadAllControlLabel))
}

// DownloadSelectedControlLabel label for the 'Download Selected' control.
func (x *CameraDeviceView) DownloadSelectedControlLabel() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("downloadSelectedControlLabel"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

// SetDownloadSelectedControlLabel wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetDownloadSelectedControlLabel(downloadSelectedControlLabel string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadSelectedControlLabel:"), purego.NSString(downloadSelectedControlLabel))
}

// IconSize in icon mode: size of the image thumbnails.
func (x *CameraDeviceView) IconSize() int {
	_r := objc.Send[int](objref.IDOf(x), objc.RegisterName("iconSize"))
	return _r
}

// SetIconSize wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetIconSize(iconSize int) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setIconSize:"), iconSize)
}

// TransferMode transfer mode either file based - or - in memory.
func (x *CameraDeviceView) TransferMode() CameraDeviceViewTransferMode {
	_r := objc.Send[CameraDeviceViewTransferMode](objref.IDOf(x), objc.RegisterName("transferMode"))
	return _r
}

// SetTransferMode wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetTransferMode(transferMode CameraDeviceViewTransferMode) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setTransferMode:"), transferMode)
}

// DisplaysDownloadsDirectoryControl show a downloads directory control.
func (x *CameraDeviceView) DisplaysDownloadsDirectoryControl() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("displaysDownloadsDirectoryControl"))
	return _r
}

// SetDisplaysDownloadsDirectoryControl wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetDisplaysDownloadsDirectoryControl(displaysDownloadsDirectoryControl bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDisplaysDownloadsDirectoryControl:"), displaysDownloadsDirectoryControl)
}

// DownloadsDirectory downloads directory.
func (x *CameraDeviceView) DownloadsDirectory() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("downloadsDirectory"))
	return obj.Wrap(_r)
}

// SetDownloadsDirectory wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetDownloadsDirectory(downloadsDirectory string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDownloadsDirectory:"), rt.FileURL(downloadsDirectory))
}

// DisplaysPostProcessApplicationControl show a postprocessing application control.
func (x *CameraDeviceView) DisplaysPostProcessApplicationControl() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("displaysPostProcessApplicationControl"))
	return _r
}

// SetDisplaysPostProcessApplicationControl wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetDisplaysPostProcessApplicationControl(displaysPostProcessApplicationControl bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setDisplaysPostProcessApplicationControl:"), displaysPostProcessApplicationControl)
}

// PostProcessApplication postprocessing application.
func (x *CameraDeviceView) PostProcessApplication() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("postProcessApplication"))
	return obj.Wrap(_r)
}

// SetPostProcessApplication wraps the corresponding Objective-C method.
func (x *CameraDeviceView) SetPostProcessApplication(postProcessApplication string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setPostProcessApplication:"), rt.FileURL(postProcessApplication))
}

// CanRotateSelectedItemsLeft indicates if the user selected items can be rotated left.
func (x *CameraDeviceView) CanRotateSelectedItemsLeft() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("canRotateSelectedItemsLeft"))
	return _r
}

// CanRotateSelectedItemsRight indicates if the user selected items can be rotated right.
func (x *CameraDeviceView) CanRotateSelectedItemsRight() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("canRotateSelectedItemsRight"))
	return _r
}

// CanDeleteSelectedItems indicates if the user selected items can be deleted.
func (x *CameraDeviceView) CanDeleteSelectedItems() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("canDeleteSelectedItems"))
	return _r
}

// CanDownloadSelectedItems indicates if the user selected items can be downloaded.
func (x *CameraDeviceView) CanDownloadSelectedItems() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("canDownloadSelectedItems"))
	return _r
}

// CameraDeviceViewable is the interface implemented by [CameraDeviceView], for mocking and DI.
type CameraDeviceViewable interface {
	obj.Object
	WithCameraDevice(cameraDevice obj.Object) *CameraDeviceView
	WithMode(mode CameraDeviceViewDisplayMode) *CameraDeviceView
	WithHasDisplayModeTable(hasDisplayModeTable bool) *CameraDeviceView
	WithHasDisplayModeIcon(hasDisplayModeIcon bool) *CameraDeviceView
	WithDownloadAllControlLabel(downloadAllControlLabel string) *CameraDeviceView
	WithDownloadSelectedControlLabel(downloadSelectedControlLabel string) *CameraDeviceView
	WithIconSize(iconSize int) *CameraDeviceView
	WithTransferMode(transferMode CameraDeviceViewTransferMode) *CameraDeviceView
	WithDisplaysDownloadsDirectoryControl(displaysDownloadsDirectoryControl bool) *CameraDeviceView
	WithDownloadsDirectory(downloadsDirectory string) *CameraDeviceView
	WithDisplaysPostProcessApplicationControl(displaysPostProcessApplicationControl bool) *CameraDeviceView
	WithPostProcessApplication(postProcessApplication string) *CameraDeviceView
	SelectedIndexes() obj.Object
	SelectIndexesByExtendingSelection(indexes obj.Object, extend bool)
	RotateLeft(sender obj.Object)
	RotateRight(sender obj.Object)
	DeleteSelectedItems(sender obj.Object)
	DownloadSelectedItems(sender obj.Object)
	DownloadAllItems(sender obj.Object)
	SetCustomIconSizeSlider(slider obj.Object)
	SetCustomModeControl(control obj.Object)
	SetCustomActionControl(control obj.Object)
	SetCustomRotateControl(control obj.Object)
	SetCustomDeleteControl(control obj.Object)
	SetShowStatusInfoAsWindowSubtitle(value bool)
	CameraDevice() obj.Object
	SetCameraDevice(cameraDevice obj.Object)
	Mode() CameraDeviceViewDisplayMode
	SetMode(mode CameraDeviceViewDisplayMode)
	HasDisplayModeTable() bool
	SetHasDisplayModeTable(hasDisplayModeTable bool)
	HasDisplayModeIcon() bool
	SetHasDisplayModeIcon(hasDisplayModeIcon bool)
	DownloadAllControlLabel() string
	SetDownloadAllControlLabel(downloadAllControlLabel string)
	DownloadSelectedControlLabel() string
	SetDownloadSelectedControlLabel(downloadSelectedControlLabel string)
	IconSize() int
	SetIconSize(iconSize int)
	TransferMode() CameraDeviceViewTransferMode
	SetTransferMode(transferMode CameraDeviceViewTransferMode)
	DisplaysDownloadsDirectoryControl() bool
	SetDisplaysDownloadsDirectoryControl(displaysDownloadsDirectoryControl bool)
	DownloadsDirectory() obj.Object
	SetDownloadsDirectory(downloadsDirectory string)
	DisplaysPostProcessApplicationControl() bool
	SetDisplaysPostProcessApplicationControl(displaysPostProcessApplicationControl bool)
	PostProcessApplication() obj.Object
	SetPostProcessApplication(postProcessApplication string)
	CanRotateSelectedItemsLeft() bool
	CanRotateSelectedItemsRight() bool
	CanDeleteSelectedItems() bool
	CanDownloadSelectedItems() bool
}

var _ CameraDeviceViewable = (*CameraDeviceView)(nil)
