// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package foundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
	"unsafe"
)

// ItemProvider wraps [raw.NSItemProvider] with a fluent Go API.
type ItemProvider struct {
	inner *raw.NSItemProvider
}

// Unwrap returns the underlying [raw.NSItemProvider].
func (x *ItemProvider) Unwrap() *raw.NSItemProvider { return x.inner }

// NewItemProvider creates a new [ItemProvider].
func NewItemProvider() *ItemProvider {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("NSItemProvider")), objc.RegisterName("new"))
	return &ItemProvider{inner: raw.NSItemProviderFromID(_id)}
}

// NewItemProviderWithObject creates a new [ItemProvider].
func NewItemProviderWithObject(object raw.NSItemProviderWriting) *ItemProvider {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("NSItemProvider")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithObject:"), object)
	return &ItemProvider{inner: raw.NSItemProviderFromID(_id)}
}

// NewItemProviderWithItemTypeIdentifier creates a new [ItemProvider].
func NewItemProviderWithItemTypeIdentifier(item raw.NSSecureCoding, typeIdentifier string) *ItemProvider {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("NSItemProvider")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithItem:typeIdentifier:"), item, foundation.NSStringStringWithUTF8String(typeIdentifier).Ptr())
	return &ItemProvider{inner: raw.NSItemProviderFromID(_id)}
}

// NewItemProviderWithContentsOfURL creates a new [ItemProvider].
func NewItemProviderWithContentsOfURL(fileURL string) *ItemProvider {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("NSItemProvider")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithContentsOfURL:"), foundation.NSURLFileURLWithPath(foundation.NSStringStringWithUTF8String(fileURL)).Ptr())
	return &ItemProvider{inner: raw.NSItemProviderFromID(_id)}
}

// WithSuggestedName sets the suggestedName property and returns the receiver for chaining.
func (x *ItemProvider) WithSuggestedName(suggestedName string) *ItemProvider {
	x.inner.SetSuggestedName(foundation.NSStringStringWithUTF8String(suggestedName))
	return x
}

// WithPreviewImageHandler sets the previewImageHandler property and returns the receiver for chaining.
func (x *ItemProvider) WithPreviewImageHandler(previewImageHandler objc.Block) *ItemProvider {
	x.inner.SetPreviewImageHandler(previewImageHandler)
	return x
}

// RegisterDataRepresentationForTypeIdentifierVisibilityLoadHandler calls the underlying RegisterDataRepresentationForTypeIdentifierVisibilityLoadHandler.
func (x *ItemProvider) RegisterDataRepresentationForTypeIdentifierVisibilityLoadHandler(typeIdentifier string, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block) {
	x.inner.RegisterDataRepresentationForTypeIdentifierVisibilityLoadHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), visibility, loadHandler)
}

// RegisterFileRepresentationForTypeIdentifierFileOptionsVisibilityLoadHandler calls the underlying RegisterFileRepresentationForTypeIdentifierFileOptionsVisibilityLoadHandler.
func (x *ItemProvider) RegisterFileRepresentationForTypeIdentifierFileOptionsVisibilityLoadHandler(typeIdentifier string, fileOptions raw.NSItemProviderFileOptions, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block) {
	x.inner.RegisterFileRepresentationForTypeIdentifierFileOptionsVisibilityLoadHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), fileOptions, visibility, loadHandler)
}

// RegisteredTypeIdentifiersWithFileOptions calls the underlying RegisteredTypeIdentifiersWithFileOptions.
func (x *ItemProvider) RegisteredTypeIdentifiersWithFileOptions(fileOptions raw.NSItemProviderFileOptions) *raw.NSArray[*raw.NSString] {
	return x.inner.RegisteredTypeIdentifiersWithFileOptions(fileOptions)
}

// HasItemConformingToTypeIdentifier calls the underlying HasItemConformingToTypeIdentifier.
func (x *ItemProvider) HasItemConformingToTypeIdentifier(typeIdentifier string) bool {
	return x.inner.HasItemConformingToTypeIdentifier(foundation.NSStringStringWithUTF8String(typeIdentifier))
}

// HasRepresentationConformingToTypeIdentifierFileOptions calls the underlying HasRepresentationConformingToTypeIdentifierFileOptions.
func (x *ItemProvider) HasRepresentationConformingToTypeIdentifierFileOptions(typeIdentifier string, fileOptions raw.NSItemProviderFileOptions) bool {
	return x.inner.HasRepresentationConformingToTypeIdentifierFileOptions(foundation.NSStringStringWithUTF8String(typeIdentifier), fileOptions)
}

// LoadDataRepresentationForTypeIdentifierCompletionHandler calls the underlying LoadDataRepresentationForTypeIdentifierCompletionHandler.
func (x *ItemProvider) LoadDataRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSData, unsafe.Pointer)) *Progress {
	_r := x.inner.LoadDataRepresentationForTypeIdentifierCompletionHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), completionHandler)
	if _r == nil {
		return nil
	}
	return &Progress{inner: _r}
}

// LoadFileRepresentationForTypeIdentifierCompletionHandler calls the underlying LoadFileRepresentationForTypeIdentifierCompletionHandler.
func (x *ItemProvider) LoadFileRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSURL, unsafe.Pointer)) *Progress {
	_r := x.inner.LoadFileRepresentationForTypeIdentifierCompletionHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), completionHandler)
	if _r == nil {
		return nil
	}
	return &Progress{inner: _r}
}

// LoadInPlaceFileRepresentationForTypeIdentifierCompletionHandler calls the underlying LoadInPlaceFileRepresentationForTypeIdentifierCompletionHandler.
func (x *ItemProvider) LoadInPlaceFileRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSURL, bool, unsafe.Pointer)) *Progress {
	_r := x.inner.LoadInPlaceFileRepresentationForTypeIdentifierCompletionHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), completionHandler)
	if _r == nil {
		return nil
	}
	return &Progress{inner: _r}
}

// RegisterObjectVisibility calls the underlying RegisterObjectVisibility.
func (x *ItemProvider) RegisterObjectVisibility(object raw.NSItemProviderWriting, visibility raw.NSItemProviderRepresentationVisibility) {
	x.inner.RegisterObjectVisibility(object, visibility)
}

// RegisterObjectOfClassVisibilityLoadHandler calls the underlying RegisterObjectOfClassVisibilityLoadHandler.
func (x *ItemProvider) RegisterObjectOfClassVisibilityLoadHandler(aClass unsafe.Pointer, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block) {
	x.inner.RegisterObjectOfClassVisibilityLoadHandler(aClass, visibility, loadHandler)
}

// CanLoadObjectOfClass calls the underlying CanLoadObjectOfClass.
func (x *ItemProvider) CanLoadObjectOfClass(aClass unsafe.Pointer) bool {
	return x.inner.CanLoadObjectOfClass(aClass)
}

// LoadObjectOfClassCompletionHandler calls the underlying LoadObjectOfClassCompletionHandler.
func (x *ItemProvider) LoadObjectOfClassCompletionHandler(aClass unsafe.Pointer, completionHandler func(objc.ID, unsafe.Pointer)) *Progress {
	_r := x.inner.LoadObjectOfClassCompletionHandler(aClass, completionHandler)
	if _r == nil {
		return nil
	}
	return &Progress{inner: _r}
}

// RegisterItemForTypeIdentifierLoadHandler calls the underlying RegisterItemForTypeIdentifierLoadHandler.
func (x *ItemProvider) RegisterItemForTypeIdentifierLoadHandler(typeIdentifier string, loadHandler objc.Block) {
	x.inner.RegisterItemForTypeIdentifierLoadHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), loadHandler)
}

// LoadItemForTypeIdentifierOptionsCompletionHandler calls the underlying LoadItemForTypeIdentifierOptionsCompletionHandler.
func (x *ItemProvider) LoadItemForTypeIdentifierOptionsCompletionHandler(typeIdentifier string, options *raw.NSDictionary[objc.ID, objc.ID], completionHandler func(objc.ID, unsafe.Pointer)) {
	x.inner.LoadItemForTypeIdentifierOptionsCompletionHandler(foundation.NSStringStringWithUTF8String(typeIdentifier), options, completionHandler)
}

// RegisteredTypeIdentifiers returns the collection as a Go slice.
func (x *ItemProvider) RegisteredTypeIdentifiers() []string {
	arr := x.inner.RegisteredTypeIdentifiers()
	if arr == nil {
		return nil
	}
	return purego.NSArrayToSlice(arr.Ptr(), func(_id objc.ID) string {
		return purego.GoString(_id)
	})
}

// SuggestedName calls the underlying SuggestedName.
func (x *ItemProvider) SuggestedName() *String {
	_r := x.inner.SuggestedName()
	if _r == nil {
		return nil
	}
	return &String{inner: _r}
}

// SetSuggestedName calls the underlying SetSuggestedName.
func (x *ItemProvider) SetSuggestedName(suggestedName string) {
	x.inner.SetSuggestedName(foundation.NSStringStringWithUTF8String(suggestedName))
}

// LoadPreviewImageWithOptionsCompletionHandler calls the underlying LoadPreviewImageWithOptionsCompletionHandler.
func (x *ItemProvider) LoadPreviewImageWithOptionsCompletionHandler(options *raw.NSDictionary[objc.ID, objc.ID], completionHandler func(objc.ID, unsafe.Pointer)) {
	x.inner.LoadPreviewImageWithOptionsCompletionHandler(options, completionHandler)
}

// PreviewImageHandler calls the underlying PreviewImageHandler.
func (x *ItemProvider) PreviewImageHandler() objc.Block {
	return x.inner.PreviewImageHandler()
}

// SetPreviewImageHandler calls the underlying SetPreviewImageHandler.
func (x *ItemProvider) SetPreviewImageHandler(previewImageHandler objc.Block) {
	x.inner.SetPreviewImageHandler(previewImageHandler)
}

func (x *ItemProvider) asObject() *raw.NSObject { return &x.inner.NSObject }

// ItemProviderable is the interface implemented by [ItemProvider], for mocking and DI.
type ItemProviderable interface {
	Unwrap() *raw.NSItemProvider
	WithSuggestedName(suggestedName string) *ItemProvider
	WithPreviewImageHandler(previewImageHandler objc.Block) *ItemProvider
	RegisterDataRepresentationForTypeIdentifierVisibilityLoadHandler(typeIdentifier string, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block)
	RegisterFileRepresentationForTypeIdentifierFileOptionsVisibilityLoadHandler(typeIdentifier string, fileOptions raw.NSItemProviderFileOptions, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block)
	RegisteredTypeIdentifiersWithFileOptions(fileOptions raw.NSItemProviderFileOptions) *raw.NSArray[*raw.NSString]
	HasItemConformingToTypeIdentifier(typeIdentifier string) bool
	HasRepresentationConformingToTypeIdentifierFileOptions(typeIdentifier string, fileOptions raw.NSItemProviderFileOptions) bool
	LoadDataRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSData, unsafe.Pointer)) *Progress
	LoadFileRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSURL, unsafe.Pointer)) *Progress
	LoadInPlaceFileRepresentationForTypeIdentifierCompletionHandler(typeIdentifier string, completionHandler func(*raw.NSURL, bool, unsafe.Pointer)) *Progress
	RegisterObjectVisibility(object raw.NSItemProviderWriting, visibility raw.NSItemProviderRepresentationVisibility)
	RegisterObjectOfClassVisibilityLoadHandler(aClass unsafe.Pointer, visibility raw.NSItemProviderRepresentationVisibility, loadHandler objc.Block)
	CanLoadObjectOfClass(aClass unsafe.Pointer) bool
	LoadObjectOfClassCompletionHandler(aClass unsafe.Pointer, completionHandler func(objc.ID, unsafe.Pointer)) *Progress
	RegisterItemForTypeIdentifierLoadHandler(typeIdentifier string, loadHandler objc.Block)
	LoadItemForTypeIdentifierOptionsCompletionHandler(typeIdentifier string, options *raw.NSDictionary[objc.ID, objc.ID], completionHandler func(objc.ID, unsafe.Pointer))
	RegisteredTypeIdentifiers() []string
	SuggestedName() *String
	SetSuggestedName(suggestedName string)
	LoadPreviewImageWithOptionsCompletionHandler(options *raw.NSDictionary[objc.ID, objc.ID], completionHandler func(objc.ID, unsafe.Pointer))
	PreviewImageHandler() objc.Block
	SetPreviewImageHandler(previewImageHandler objc.Block)
}

var _ ItemProviderable = (*ItemProvider)(nil)

