// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package avfoundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// MutableDateRangeMetadataGroup is an idiomatic wrapper over the Objective-C class AVMutableDateRangeMetadataGroup.
//
// It embeds [DateRangeMetadataGroup], promoting that type's methods.
//
// A mutable collection of metadata items that are valid for use within a specific range of dates.
type MutableDateRangeMetadataGroup struct {
	DateRangeMetadataGroup
}

// MutableDateRangeMetadataGroupFromID adopts an existing Objective-C object as a MutableDateRangeMetadataGroup
// (nil for 0), retaining it and registering a release finalizer.
func MutableDateRangeMetadataGroupFromID(id objc.ID) *MutableDateRangeMetadataGroup {
	if id == 0 {
		return nil
	}
	x := &MutableDateRangeMetadataGroup{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mutableDateRangeMetadataGroupAdopt wraps an Objective-C object that this code just created as a
// MutableDateRangeMetadataGroup (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mutableDateRangeMetadataGroupAdopt(id objc.ID) *MutableDateRangeMetadataGroup {
	if id == 0 {
		return nil
	}
	x := &MutableDateRangeMetadataGroup{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewMutableDateRangeMetadataGroup creates a new MutableDateRangeMetadataGroup.
func NewMutableDateRangeMetadataGroup() *MutableDateRangeMetadataGroup {
	_id := objc.Send[objc.ID](objc.ID(_class("AVMutableDateRangeMetadataGroup")), objc.RegisterName("new"))
	return mutableDateRangeMetadataGroupAdopt(_id)
}

// WithStartDate sets the start date for the metadata date range group.
func (mdrmg *MutableDateRangeMetadataGroup) WithStartDate(startDate obj.Object) *MutableDateRangeMetadataGroup {
	objc.Send[objc.ID](objref.IDOf(mdrmg), objc.RegisterName("setStartDate:"), objref.IDOf(startDate))
	return mdrmg
}

// WithEndDate sets the end date for the metadata date range group.
func (mdrmg *MutableDateRangeMetadataGroup) WithEndDate(endDate obj.Object) *MutableDateRangeMetadataGroup {
	objc.Send[objc.ID](objref.IDOf(mdrmg), objc.RegisterName("setEndDate:"), objref.IDOf(endDate))
	return mdrmg
}

// WithItems sets an array of associated metadata items.
func (mdrmg *MutableDateRangeMetadataGroup) WithItems(items ...MetadataItemProvider) *MutableDateRangeMetadataGroup {
	_arr := purego.SliceToNSArray(items, func(_v MetadataItemProvider) objc.ID { return objref.IDOf(_v) })
	objc.Send[objc.ID](objref.IDOf(mdrmg), objc.RegisterName("setItems:"), _arr)
	return mdrmg
}

var _ DateRangeMetadataGroupProvider = (*MutableDateRangeMetadataGroup)(nil)

var _ MetadataGroupProvider = (*MutableDateRangeMetadataGroup)(nil)
