// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package mpsneuralnetwork

import (
	"github.com/ebitengine/purego/objc"

	"github.com/deploymenttheory/go-bindings-macosplatform/internal/pureobjc"
)

// Node representing a @ref MPSNNGramMatrixCalculationGradient kernel
//
// Apple documentation: https://developer.apple.com/documentation/mpsneuralnetwork/mpsnngrammatrixcalculationgradientnode
type MPSNNGramMatrixCalculationGradientNode struct {
	MPSNNGradientFilterNode
}

var (
	_clsMPSNNGramMatrixCalculationGradientNode = _objcClass("MPSNNGramMatrixCalculationGradientNode")
	_mPSNNGramMatrixCalculationGradientNodeSelNodeWithSourceGradientSourceImageGradientState = objc.RegisterName("nodeWithSourceGradient:sourceImage:gradientState:")
	_mPSNNGramMatrixCalculationGradientNodeSelInitWithSourceGradientSourceImageGradientState = objc.RegisterName("initWithSourceGradient:sourceImage:gradientState:")
	_mPSNNGramMatrixCalculationGradientNodeSelNodeWithSourceGradientSourceImageGradientStateAlpha = objc.RegisterName("nodeWithSourceGradient:sourceImage:gradientState:alpha:")
	_mPSNNGramMatrixCalculationGradientNodeSelInitWithSourceGradientSourceImageGradientStateAlpha = objc.RegisterName("initWithSourceGradient:sourceImage:gradientState:alpha:")
	_mPSNNGramMatrixCalculationGradientNodeSelAlpha = objc.RegisterName("alpha")
)

func MPSNNGramMatrixCalculationGradientNodeFromID(id objc.ID) *MPSNNGramMatrixCalculationGradientNode {
	if id == 0 {
		return nil
	}
	o := &MPSNNGramMatrixCalculationGradientNode{}
	o.InitPtr(id)
	pureobjc.Track(o)
	return o
}

func MPSNNGramMatrixCalculationGradientNodeNodeWithSourceGradientSourceImageGradientState(sourceGradient *MPSNNImageNode, sourceImage *MPSNNImageNode, gradientState *MPSNNGradientStateNode) *MPSNNGramMatrixCalculationGradientNode {
	_ret := objc.Send[objc.ID](objc.ID(_clsMPSNNGramMatrixCalculationGradientNode), _mPSNNGramMatrixCalculationGradientNodeSelNodeWithSourceGradientSourceImageGradientState, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSNNGramMatrixCalculationGradientNodeFromID(_ret)
}

func (o *MPSNNGramMatrixCalculationGradientNode) InitWithSourceGradientSourceImageGradientState(sourceGradient *MPSNNImageNode, sourceImage *MPSNNImageNode, gradientState *MPSNNGradientStateNode) *MPSNNGramMatrixCalculationGradientNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _mPSNNGramMatrixCalculationGradientNodeSelInitWithSourceGradientSourceImageGradientState, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr())
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSNNGramMatrixCalculationGradientNodeFromID(_ret)
}

func MPSNNGramMatrixCalculationGradientNodeNodeWithSourceGradientSourceImageGradientStateAlpha(sourceGradient *MPSNNImageNode, sourceImage *MPSNNImageNode, gradientState *MPSNNGradientStateNode, alpha float32) *MPSNNGramMatrixCalculationGradientNode {
	_ret := objc.Send[objc.ID](objc.ID(_clsMPSNNGramMatrixCalculationGradientNode), _mPSNNGramMatrixCalculationGradientNodeSelNodeWithSourceGradientSourceImageGradientStateAlpha, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr(), alpha)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSNNGramMatrixCalculationGradientNodeFromID(_ret)
}

func (o *MPSNNGramMatrixCalculationGradientNode) InitWithSourceGradientSourceImageGradientStateAlpha(sourceGradient *MPSNNImageNode, sourceImage *MPSNNImageNode, gradientState *MPSNNGradientStateNode, alpha float32) *MPSNNGramMatrixCalculationGradientNode {
	_ret := objc.Send[objc.ID](o.Ptr(), _mPSNNGramMatrixCalculationGradientNodeSelInitWithSourceGradientSourceImageGradientStateAlpha, sourceGradient.Ptr(), sourceImage.Ptr(), gradientState.Ptr(), alpha)
	if _ret != 0 { _ret.Send(objc.RegisterName("retain")) }
	return MPSNNGramMatrixCalculationGradientNodeFromID(_ret)
}

// @property   alpha @abstract   Scaling factor for the output. Default: 1.0f.
func (o *MPSNNGramMatrixCalculationGradientNode) Alpha() float32 {
	_ret := objc.Send[float32](o.Ptr(), _mPSNNGramMatrixCalculationGradientNodeSelAlpha)
	return _ret
}

