// Code generated by go-bindings-purecg. DO NOT EDIT.
//go:build darwin

package intents

import (
	"github.com/ebitengine/purego/objc"
)

// INAnswerCallIntentHandling wraps the ObjC protocol INAnswerCallIntentHandling.
type INAnswerCallIntentHandling interface {
	HandleAnswerCallCompletion(intent *INAnswerCallIntent, completion func(*INAnswerCallIntentResponse))
}

// INEditMessageIntentHandling wraps the ObjC protocol INEditMessageIntentHandling.
type INEditMessageIntentHandling interface {
	HandleEditMessageCompletion(intent *INEditMessageIntent, completion func(*INEditMessageIntentResponse))
}

// INHangUpCallIntentHandling wraps the ObjC protocol INHangUpCallIntentHandling.
type INHangUpCallIntentHandling interface {
	HandleHangUpCallCompletion(intent *INHangUpCallIntent, completion func(*INHangUpCallIntentResponse))
}

// INIntentHandlerProviding wraps the ObjC protocol INIntentHandlerProviding.
type INIntentHandlerProviding interface {
	HandlerForIntent(intent *INIntent) objc.ID
}

// INSendMessageIntentHandling wraps the ObjC protocol INSendMessageIntentHandling.
type INSendMessageIntentHandling interface {
	HandleSendMessageCompletion(intent *INSendMessageIntent, completion func(*INSendMessageIntentResponse))
}

// INShareFocusStatusIntentHandling wraps the ObjC protocol INShareFocusStatusIntentHandling.
type INShareFocusStatusIntentHandling interface {
	HandleShareFocusStatusCompletion(intent *INShareFocusStatusIntent, completion func(*INShareFocusStatusIntentResponse))
}

// INSpeakable wraps the ObjC protocol INSpeakable.
type INSpeakable interface {
}

// INStartCallIntentHandling wraps the ObjC protocol INStartCallIntentHandling.
type INStartCallIntentHandling interface {
	HandleStartCallCompletion(intent *INStartCallIntent, completion func(objc.ID))
}

// INUnsendMessagesIntentHandling wraps the ObjC protocol INUnsendMessagesIntentHandling.
type INUnsendMessagesIntentHandling interface {
	HandleUnsendMessagesCompletion(intent *INUnsendMessagesIntent, completion func(*INUnsendMessagesIntentResponse))
}
