// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"context"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/errkit"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// MTRBaseClusterBinaryInputBasic is an idiomatic wrapper over the Objective-C class MTRBaseClusterBinaryInputBasic.
//
// It embeds [MTRGenericBaseCluster], promoting that type's methods.
type MTRBaseClusterBinaryInputBasic struct {
	MTRGenericBaseCluster
}

// MTRBaseClusterBinaryInputBasicFromID adopts an existing Objective-C object as a MTRBaseClusterBinaryInputBasic
// (nil for 0), retaining it and registering a release finalizer.
func MTRBaseClusterBinaryInputBasicFromID(id objc.ID) *MTRBaseClusterBinaryInputBasic {
	if id == 0 {
		return nil
	}
	x := &MTRBaseClusterBinaryInputBasic{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mTRBaseClusterBinaryInputBasicAdopt wraps an Objective-C object that this code just created as a
// MTRBaseClusterBinaryInputBasic (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTRBaseClusterBinaryInputBasicAdopt(id objc.ID) *MTRBaseClusterBinaryInputBasic {
	if id == 0 {
		return nil
	}
	x := &MTRBaseClusterBinaryInputBasic{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewMTRBaseClusterBinaryInputBasicWithDeviceEndpointIDQueue for all instance methods (reads, writes, commands) that take a completion, the completion will be called on the provided queue.
func NewMTRBaseClusterBinaryInputBasicWithDeviceEndpointIDQueue(device *MTRBaseDevice, endpointID obj.Object, queue obj.Object) *MTRBaseClusterBinaryInputBasic {
	_alloc := objc.Send[objc.ID](objc.ID(_class("MTRBaseClusterBinaryInputBasic")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithDevice:endpointID:queue:"), objref.IDOf(device), objref.IDOf(endpointID), objref.IDOf(queue))
	return mTRBaseClusterBinaryInputBasicAdopt(_id)
}

// NewMTRBaseClusterBinaryInputBasicWithDeviceEndpointQueue creates a new MTRBaseClusterBinaryInputBasic.
func NewMTRBaseClusterBinaryInputBasicWithDeviceEndpointQueue(device *MTRBaseDevice, endpoint uint16, queue obj.Object) *MTRBaseClusterBinaryInputBasic {
	_alloc := objc.Send[objc.ID](objc.ID(_class("MTRBaseClusterBinaryInputBasic")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithDevice:endpoint:queue:"), objref.IDOf(device), endpoint, objref.IDOf(queue))
	return mTRBaseClusterBinaryInputBasicAdopt(_id)
}

// ReadAttributeActiveTextWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeActiveTextWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeActiveTextWithCompletion(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeActiveTextWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeActiveTextWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeActiveTextWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeActiveTextWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeActiveTextWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeDescriptionWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeDescriptionWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeDescriptionWithCompletion(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeDescriptionWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeDescriptionWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeDescriptionWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeDescriptionWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeDescriptionWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeInactiveTextWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeInactiveTextWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeInactiveTextWithCompletion(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeInactiveTextWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeInactiveTextWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeInactiveTextWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeInactiveTextWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeInactiveTextWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeOutOfServiceWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeOutOfServiceWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeOutOfServiceWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeOutOfServiceWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeOutOfServiceWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeOutOfServiceWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeOutOfServiceWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeOutOfServiceWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributePolarityWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributePolarityWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributePolarityWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributePolarityWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributePolarityWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributePolarityWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributePolarityWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributePolarityWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributePresentValueWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributePresentValueWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributePresentValueWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributePresentValueWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributePresentValueWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributePresentValueWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributePresentValueWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributePresentValueWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeReliabilityWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeReliabilityWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeReliabilityWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeReliabilityWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeReliabilityWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeReliabilityWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeReliabilityWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeReliabilityWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeStatusFlagsWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeStatusFlagsWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeStatusFlagsWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeStatusFlagsWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeStatusFlagsWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeStatusFlagsWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeStatusFlagsWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeStatusFlagsWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeApplicationTypeWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeApplicationTypeWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeApplicationTypeWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeApplicationTypeWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeApplicationTypeWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeApplicationTypeWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeApplicationTypeWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeApplicationTypeWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeGeneratedCommandListWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeGeneratedCommandListWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeGeneratedCommandListWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeGeneratedCommandListWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeGeneratedCommandListWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeGeneratedCommandListWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeGeneratedCommandListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeGeneratedCommandListWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeAcceptedCommandListWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeAcceptedCommandListWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeAcceptedCommandListWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeAcceptedCommandListWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeAcceptedCommandListWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeAcceptedCommandListWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeAcceptedCommandListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeAcceptedCommandListWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeAttributeListWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeAttributeListWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeAttributeListWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeAttributeListWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeAttributeListWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeAttributeListWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeAttributeListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeAttributeListWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeFeatureMapWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeFeatureMapWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeFeatureMapWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeFeatureMapWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeFeatureMapWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeFeatureMapWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeFeatureMapWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeFeatureMapWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeClusterRevisionWithCompletion wraps the corresponding Objective-C method.
//
// ReadAttributeClusterRevisionWithCompletion blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeClusterRevisionWithCompletion(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeClusterRevisionWithCompletion:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeClusterRevisionWithParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeClusterRevisionWithParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeClusterRevisionWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeClusterRevisionWithParams:subscriptionEstablished:reportHandler:"), objref.IDOf(params), subscriptionEstablished, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeActiveText wraps the corresponding Objective-C method.
//
// ReadAttributeActiveText blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeActiveText(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeActiveTextWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeActiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeActiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeActiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeActiveTextWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeDescription wraps the corresponding Objective-C method.
//
// ReadAttributeDescription blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeDescription(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeDescriptionWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeDescriptionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeDescriptionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeDescriptionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeDescriptionWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeInactiveText wraps the corresponding Objective-C method.
//
// ReadAttributeInactiveText blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeInactiveText(ctx context.Context) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeInactiveTextWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeInactiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeInactiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeInactiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result string, err error) {
	type _result struct {
		val string
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = purego.GoString(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeInactiveTextWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero string
		return _zero, ctx.Err()
	}
}

// ReadAttributeOutOfService wraps the corresponding Objective-C method.
//
// ReadAttributeOutOfService blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeOutOfService(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeOutOfServiceWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeOutOfServiceWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeOutOfServiceWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeOutOfServiceWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeOutOfServiceWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributePolarity wraps the corresponding Objective-C method.
//
// ReadAttributePolarity blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributePolarity(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributePolarityWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributePolarityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributePolarityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributePolarityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributePolarityWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributePresentValue wraps the corresponding Objective-C method.
//
// ReadAttributePresentValue blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributePresentValue(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributePresentValueWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributePresentValueWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributePresentValueWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributePresentValueWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributePresentValueWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeReliability wraps the corresponding Objective-C method.
//
// ReadAttributeReliability blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeReliability(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeReliabilityWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeReliabilityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeReliabilityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeReliabilityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeReliabilityWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeStatusFlags wraps the corresponding Objective-C method.
//
// ReadAttributeStatusFlags blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeStatusFlags(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeStatusFlagsWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeStatusFlagsWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeStatusFlagsWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeStatusFlagsWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeStatusFlagsWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeApplicationType wraps the corresponding Objective-C method.
//
// ReadAttributeApplicationType blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeApplicationType(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeApplicationTypeWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeApplicationTypeWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeApplicationTypeWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeApplicationTypeWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeApplicationTypeWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeGeneratedCommandList wraps the corresponding Objective-C method.
//
// ReadAttributeGeneratedCommandList blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeGeneratedCommandList(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeGeneratedCommandListWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeGeneratedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeGeneratedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeGeneratedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeGeneratedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeAcceptedCommandList wraps the corresponding Objective-C method.
//
// ReadAttributeAcceptedCommandList blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeAcceptedCommandList(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeAcceptedCommandListWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeAcceptedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeAcceptedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeAcceptedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeAcceptedCommandListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeAttributeList wraps the corresponding Objective-C method.
//
// ReadAttributeAttributeList blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeAttributeList(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeAttributeListWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeAttributeListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeAttributeListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeAttributeListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeAttributeListWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeFeatureMap wraps the corresponding Objective-C method.
//
// ReadAttributeFeatureMap blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeFeatureMap(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeFeatureMapWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeFeatureMapWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeFeatureMapWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeFeatureMapWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeFeatureMapWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// ReadAttributeClusterRevision wraps the corresponding Objective-C method.
//
// ReadAttributeClusterRevision blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) ReadAttributeClusterRevision(ctx context.Context) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("readAttributeClusterRevisionWithCompletionHandler:"), _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// SubscribeAttributeClusterRevisionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler wraps the corresponding Objective-C method.
//
// SubscribeAttributeClusterRevisionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler blocks until the operation completes or ctx is cancelled.
func (x *MTRBaseClusterBinaryInputBasic) SubscribeAttributeClusterRevisionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (result obj.Object, err error) {
	type _result struct {
		val obj.Object
		err error
	}
	_ch := make(chan _result, 1)
	_block := objc.NewBlock(func(_ objc.Block, _p0 objc.ID, _p1 objc.ID) {
		var _o _result
		_o.err = errkit.FromObjC(purego.NSErrorToError(_p1))
		_o.val = obj.Wrap(_p0)
		_ch <- _o
	})
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("subscribeAttributeClusterRevisionWithMinInterval:maxInterval:params:subscriptionEstablished:reportHandler:"), objref.IDOf(minInterval), objref.IDOf(maxInterval), objref.IDOf(params), subscriptionEstablishedHandler, _block)
	select {
	case _o := <-_ch:
		return _o.val, _o.err
	case <-ctx.Done():
		var _zero obj.Object
		return _zero, ctx.Err()
	}
}

// MTRBaseClusterBinaryInputBasicable is the interface implemented by [MTRBaseClusterBinaryInputBasic], for mocking and DI.
type MTRBaseClusterBinaryInputBasicable interface {
	obj.Object
	ReadAttributeActiveTextWithCompletion(ctx context.Context) (string, error)
	SubscribeAttributeActiveTextWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (string, error)
	ReadAttributeDescriptionWithCompletion(ctx context.Context) (string, error)
	SubscribeAttributeDescriptionWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (string, error)
	ReadAttributeInactiveTextWithCompletion(ctx context.Context) (string, error)
	SubscribeAttributeInactiveTextWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (string, error)
	ReadAttributeOutOfServiceWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeOutOfServiceWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributePolarityWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributePolarityWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributePresentValueWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributePresentValueWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeReliabilityWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeReliabilityWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeStatusFlagsWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeStatusFlagsWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeApplicationTypeWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeApplicationTypeWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeGeneratedCommandListWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeGeneratedCommandListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeAcceptedCommandListWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeAcceptedCommandListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeAttributeListWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeAttributeListWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeFeatureMapWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeFeatureMapWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeClusterRevisionWithCompletion(ctx context.Context) (obj.Object, error)
	SubscribeAttributeClusterRevisionWithParamsSubscriptionEstablishedReportHandler(ctx context.Context, params *MTRSubscribeParams, subscriptionEstablished func()) (obj.Object, error)
	ReadAttributeActiveText(ctx context.Context) (string, error)
	SubscribeAttributeActiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (string, error)
	ReadAttributeDescription(ctx context.Context) (string, error)
	SubscribeAttributeDescriptionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (string, error)
	ReadAttributeInactiveText(ctx context.Context) (string, error)
	SubscribeAttributeInactiveTextWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (string, error)
	ReadAttributeOutOfService(ctx context.Context) (obj.Object, error)
	SubscribeAttributeOutOfServiceWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributePolarity(ctx context.Context) (obj.Object, error)
	SubscribeAttributePolarityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributePresentValue(ctx context.Context) (obj.Object, error)
	SubscribeAttributePresentValueWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeReliability(ctx context.Context) (obj.Object, error)
	SubscribeAttributeReliabilityWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeStatusFlags(ctx context.Context) (obj.Object, error)
	SubscribeAttributeStatusFlagsWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeApplicationType(ctx context.Context) (obj.Object, error)
	SubscribeAttributeApplicationTypeWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeGeneratedCommandList(ctx context.Context) (obj.Object, error)
	SubscribeAttributeGeneratedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeAcceptedCommandList(ctx context.Context) (obj.Object, error)
	SubscribeAttributeAcceptedCommandListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeAttributeList(ctx context.Context) (obj.Object, error)
	SubscribeAttributeAttributeListWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeFeatureMap(ctx context.Context) (obj.Object, error)
	SubscribeAttributeFeatureMapWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
	ReadAttributeClusterRevision(ctx context.Context) (obj.Object, error)
	SubscribeAttributeClusterRevisionWithMinIntervalMaxIntervalParamsSubscriptionEstablishedReportHandler(ctx context.Context, minInterval obj.Object, maxInterval obj.Object, params *MTRSubscribeParams, subscriptionEstablishedHandler func()) (obj.Object, error)
}

var _ MTRBaseClusterBinaryInputBasicable = (*MTRBaseClusterBinaryInputBasic)(nil)

var _ MTRGenericBaseClusterProvider = (*MTRBaseClusterBinaryInputBasic)(nil)

var _ MTRClusterProvider = (*MTRBaseClusterBinaryInputBasic)(nil)
