// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"runtime"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/framework/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// MTRClusterPath is an idiomatic wrapper over the Objective-C class MTRClusterPath.
//
// MTRClusterPath is an abstract base — you do not construct it directly. Construct one of [MTRAttributePath], [MTRCommandPath], [MTREventPath] and pass it where a MTRClusterPath is accepted.
type MTRClusterPath struct {
	objref.Handle
}

// MTRClusterPathFromID adopts an existing Objective-C object as a MTRClusterPath
// (nil for 0), retaining it and registering a release finalizer.
func MTRClusterPathFromID(id objc.ID) *MTRClusterPath {
	if id == 0 {
		return nil
	}
	x := &MTRClusterPath{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mTRClusterPathAdopt wraps an Objective-C object that this code just created as a
// MTRClusterPath (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTRClusterPathAdopt(id objc.ID) *MTRClusterPath {
	if id == 0 {
		return nil
	}
	x := &MTRClusterPath{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (mcp *MTRClusterPath) Description() string {
	defer runtime.KeepAlive(mcp)
	return rt.Description(objref.IDOf(mcp))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (mcp *MTRClusterPath) IsEqual(other obj.Object) bool {
	defer runtime.KeepAlive(mcp)
	defer runtime.KeepAlive(other)
	return rt.IsEqual(objref.IDOf(mcp), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (mcp *MTRClusterPath) IsKind(className string) bool {
	defer runtime.KeepAlive(mcp)
	return rt.IsKind(objref.IDOf(mcp), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (mcp *MTRClusterPath) String() string {
	defer runtime.KeepAlive(mcp)
	return rt.Description(objref.IDOf(mcp))
}

// Endpoint returns the endpoint.
func (mcp *MTRClusterPath) Endpoint() *foundation.Number {
	defer runtime.KeepAlive(mcp)
	_r := objc.Send[objc.ID](objref.IDOf(mcp), objc.RegisterName("endpoint"))
	return foundation.NumberFromID(_r)
}

// Cluster returns the cluster.
func (mcp *MTRClusterPath) Cluster() *foundation.Number {
	defer runtime.KeepAlive(mcp)
	_r := objc.Send[objc.ID](objref.IDOf(mcp), objc.RegisterName("cluster"))
	return foundation.NumberFromID(_r)
}

// isMTRClusterPath marks MTRClusterPath — and, by embedding promotion, its
// subclasses — as a member of the MTRClusterPath hierarchy, sealing its provider
// interface so only real members satisfy it.
func (mcp *MTRClusterPath) isMTRClusterPath() {}

var _ MTRClusterPathProvider = (*MTRClusterPath)(nil)
