// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams is an idiomatic wrapper over the Objective-C class MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams.
type MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams struct {
	objref.Handle
}

// MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsFromID adopts an existing Objective-C object as a MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams
// (nil for 0), retaining it and registering a release finalizer.
func MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsFromID(id objc.ID) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	if id == 0 {
		return nil
	}
	x := &MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsAdopt wraps an Objective-C object that this code just created as a
// MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsAdopt(id objc.ID) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	if id == 0 {
		return nil
	}
	x := &MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) String() string {
	return rt.Description(objref.IDOf(x))
}

// NewMTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams creates a new MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams.
func NewMTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams() *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	_id := objc.Send[objc.ID](objc.ID(_class("MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams")), objc.RegisterName("new"))
	return mTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsAdopt(_id)
}

// WithRequestedStartTime sets the property and returns the receiver so calls can be chained.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) WithRequestedStartTime(requestedStartTime obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setRequestedStartTime:"), objref.IDOf(requestedStartTime))
	return x
}

// WithCause sets the property and returns the receiver so calls can be chained.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) WithCause(cause obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCause:"), objref.IDOf(cause))
	return x
}

// WithTimedInvokeTimeoutMs controls whether the command is a timed command (using Timed Invoke).
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) WithTimedInvokeTimeoutMs(timedInvokeTimeoutMs obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setTimedInvokeTimeoutMs:"), objref.IDOf(timedInvokeTimeoutMs))
	return x
}

// WithServerSideProcessingTimeout controls how much time, in seconds, we will allow for the server to process the command.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) WithServerSideProcessingTimeout(serverSideProcessingTimeout obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setServerSideProcessingTimeout:"), objref.IDOf(serverSideProcessingTimeout))
	return x
}

// RequestedStartTime wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) RequestedStartTime() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("requestedStartTime"))
	return obj.Wrap(_r)
}

// SetRequestedStartTime wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) SetRequestedStartTime(requestedStartTime obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setRequestedStartTime:"), objref.IDOf(requestedStartTime))
}

// Cause wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) Cause() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("cause"))
	return obj.Wrap(_r)
}

// SetCause wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) SetCause(cause obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setCause:"), objref.IDOf(cause))
}

// TimedInvokeTimeoutMs controls whether the command is a timed command (using Timed Invoke). If nil (the default value), a regular invoke is done for commands that do not require a timed invoke and a timed invoke with some default timed request timeout is done for commands that require a timed invoke. If not nil, a timed invoke is done, with the provided value used as the timed request timeout.  The value should be chosen small enough to provide the desired security properties but large enough that it will allow a round-trip from the sever to the client (for the status response and actual invoke request) within the timeout window.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) TimedInvokeTimeoutMs() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("timedInvokeTimeoutMs"))
	return obj.Wrap(_r)
}

// SetTimedInvokeTimeoutMs wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setTimedInvokeTimeoutMs:"), objref.IDOf(timedInvokeTimeoutMs))
}

// ServerSideProcessingTimeout controls how much time, in seconds, we will allow for the server to process the command. The command will then time out if that much time, plus an allowance for retransmits due to network failures, passes. If nil, the framework will try to select an appropriate timeout value itself.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) ServerSideProcessingTimeout() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("serverSideProcessingTimeout"))
	return obj.Wrap(_r)
}

// SetServerSideProcessingTimeout wraps the corresponding Objective-C method.
func (x *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams) SetServerSideProcessingTimeout(serverSideProcessingTimeout obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setServerSideProcessingTimeout:"), objref.IDOf(serverSideProcessingTimeout))
}

// MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsable is the interface implemented by [MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams], for mocking and DI.
type MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsable interface {
	obj.Object
	WithRequestedStartTime(requestedStartTime obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams
	WithCause(cause obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams
	WithTimedInvokeTimeoutMs(timedInvokeTimeoutMs obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams
	WithServerSideProcessingTimeout(serverSideProcessingTimeout obj.Object) *MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams
	RequestedStartTime() obj.Object
	SetRequestedStartTime(requestedStartTime obj.Object)
	Cause() obj.Object
	SetCause(cause obj.Object)
	TimedInvokeTimeoutMs() obj.Object
	SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs obj.Object)
	ServerSideProcessingTimeout() obj.Object
	SetServerSideProcessingTimeout(serverSideProcessingTimeout obj.Object)
}

var _ MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParamsable = (*MTRDeviceEnergyManagementClusterStartTimeAdjustRequestParams)(nil)
