// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/matter"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
)

// MTRGroupsClusterAddGroupParams wraps [raw.MTRGroupsClusterAddGroupParams] with a fluent Go API.
type MTRGroupsClusterAddGroupParams struct {
	inner *raw.MTRGroupsClusterAddGroupParams
}

// Unwrap returns the underlying [raw.MTRGroupsClusterAddGroupParams].
func (x *MTRGroupsClusterAddGroupParams) Unwrap() *raw.MTRGroupsClusterAddGroupParams { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *MTRGroupsClusterAddGroupParams) ID() objc.ID { return x.inner.Ptr() }

// MTRGroupsClusterAddGroupParamsFromID adopts an existing object pointer as a MTRGroupsClusterAddGroupParams (nil for 0).
func MTRGroupsClusterAddGroupParamsFromID(id objc.ID) *MTRGroupsClusterAddGroupParams {
	if id == 0 {
		return nil
	}
	return &MTRGroupsClusterAddGroupParams{inner: raw.MTRGroupsClusterAddGroupParamsFromID(id)}
}

// NewMTRGroupsClusterAddGroupParams creates a new [MTRGroupsClusterAddGroupParams].
func NewMTRGroupsClusterAddGroupParams() *MTRGroupsClusterAddGroupParams {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("MTRGroupsClusterAddGroupParams")), objc.RegisterName("new"))
	return &MTRGroupsClusterAddGroupParams{inner: raw.MTRGroupsClusterAddGroupParamsFromID(_id)}
}

// WithGroupID sets the groupID property and returns the receiver for chaining.
func (x *MTRGroupsClusterAddGroupParams) WithGroupID(groupID *foundation.NSNumber) *MTRGroupsClusterAddGroupParams {
	x.inner.SetGroupID(groupID)
	return x
}

// WithGroupName sets the groupName property and returns the receiver for chaining.
func (x *MTRGroupsClusterAddGroupParams) WithGroupName(groupName string) *MTRGroupsClusterAddGroupParams {
	x.inner.SetGroupName(foundation.NSStringStringWithUTF8String(groupName))
	return x
}

// Controls whether the command is a timed command (using Timed Invoke). If nil (the default value), a regular invoke is done for commands that do not require a timed invoke and a timed invoke with some default timed request timeout is done for commands that require a timed invoke. If not nil, a timed invoke is done, with the provided value used as the timed request timeout.  The value should be chosen small enough to provide the desired security properties but large enough that it will allow a round-trip from the sever to the client (for the status response and actual invoke request) within the timeout window.
//
// WithTimedInvokeTimeoutMs sets the timedInvokeTimeoutMs property and returns the receiver for chaining.
func (x *MTRGroupsClusterAddGroupParams) WithTimedInvokeTimeoutMs(timedInvokeTimeoutMs *foundation.NSNumber) *MTRGroupsClusterAddGroupParams {
	x.inner.SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs)
	return x
}

// Controls how much time, in seconds, we will allow for the server to process the command. The command will then time out if that much time, plus an allowance for retransmits due to network failures, passes. If nil, the framework will try to select an appropriate timeout value itself.
//
// WithServerSideProcessingTimeout sets the serverSideProcessingTimeout property and returns the receiver for chaining.
func (x *MTRGroupsClusterAddGroupParams) WithServerSideProcessingTimeout(serverSideProcessingTimeout *foundation.NSNumber) *MTRGroupsClusterAddGroupParams {
	x.inner.SetServerSideProcessingTimeout(serverSideProcessingTimeout)
	return x
}

// WithGroupId sets the groupId property and returns the receiver for chaining.
func (x *MTRGroupsClusterAddGroupParams) WithGroupId(groupId *foundation.NSNumber) *MTRGroupsClusterAddGroupParams {
	x.inner.SetGroupId(groupId)
	return x
}

// GroupID calls the underlying GroupID.
func (x *MTRGroupsClusterAddGroupParams) GroupID() *foundation.NSNumber {
	return x.inner.GroupID()
}

// SetGroupID calls the underlying SetGroupID.
func (x *MTRGroupsClusterAddGroupParams) SetGroupID(groupID *foundation.NSNumber) {
	x.inner.SetGroupID(groupID)
}

// GroupName calls the underlying GroupName.
func (x *MTRGroupsClusterAddGroupParams) GroupName() string {
	_r := x.inner.GroupName()
	if _r == nil {
		return ""
	}
	return purego.GoString(_r.Ptr())
}

// SetGroupName calls the underlying SetGroupName.
func (x *MTRGroupsClusterAddGroupParams) SetGroupName(groupName string) {
	x.inner.SetGroupName(foundation.NSStringStringWithUTF8String(groupName))
}

// Controls whether the command is a timed command (using Timed Invoke). If nil (the default value), a regular invoke is done for commands that do not require a timed invoke and a timed invoke with some default timed request timeout is done for commands that require a timed invoke. If not nil, a timed invoke is done, with the provided value used as the timed request timeout.  The value should be chosen small enough to provide the desired security properties but large enough that it will allow a round-trip from the sever to the client (for the status response and actual invoke request) within the timeout window.
//
// TimedInvokeTimeoutMs calls the underlying TimedInvokeTimeoutMs.
func (x *MTRGroupsClusterAddGroupParams) TimedInvokeTimeoutMs() *foundation.NSNumber {
	return x.inner.TimedInvokeTimeoutMs()
}

// SetTimedInvokeTimeoutMs calls the underlying SetTimedInvokeTimeoutMs.
func (x *MTRGroupsClusterAddGroupParams) SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs *foundation.NSNumber) {
	x.inner.SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs)
}

// Controls how much time, in seconds, we will allow for the server to process the command. The command will then time out if that much time, plus an allowance for retransmits due to network failures, passes. If nil, the framework will try to select an appropriate timeout value itself.
//
// ServerSideProcessingTimeout calls the underlying ServerSideProcessingTimeout.
func (x *MTRGroupsClusterAddGroupParams) ServerSideProcessingTimeout() *foundation.NSNumber {
	return x.inner.ServerSideProcessingTimeout()
}

// SetServerSideProcessingTimeout calls the underlying SetServerSideProcessingTimeout.
func (x *MTRGroupsClusterAddGroupParams) SetServerSideProcessingTimeout(serverSideProcessingTimeout *foundation.NSNumber) {
	x.inner.SetServerSideProcessingTimeout(serverSideProcessingTimeout)
}

// GroupId calls the underlying GroupId.
func (x *MTRGroupsClusterAddGroupParams) GroupId() *foundation.NSNumber {
	return x.inner.GroupId()
}

// SetGroupId calls the underlying SetGroupId.
func (x *MTRGroupsClusterAddGroupParams) SetGroupId(groupId *foundation.NSNumber) {
	x.inner.SetGroupId(groupId)
}

// MTRGroupsClusterAddGroupParamsable is the interface implemented by [MTRGroupsClusterAddGroupParams], for mocking and DI.
type MTRGroupsClusterAddGroupParamsable interface {
	Unwrap() *raw.MTRGroupsClusterAddGroupParams
	WithGroupID(groupID *foundation.NSNumber) *MTRGroupsClusterAddGroupParams
	WithGroupName(groupName string) *MTRGroupsClusterAddGroupParams
	WithTimedInvokeTimeoutMs(timedInvokeTimeoutMs *foundation.NSNumber) *MTRGroupsClusterAddGroupParams
	WithServerSideProcessingTimeout(serverSideProcessingTimeout *foundation.NSNumber) *MTRGroupsClusterAddGroupParams
	WithGroupId(groupId *foundation.NSNumber) *MTRGroupsClusterAddGroupParams
	GroupID() *foundation.NSNumber
	SetGroupID(groupID *foundation.NSNumber)
	GroupName() string
	SetGroupName(groupName string)
	TimedInvokeTimeoutMs() *foundation.NSNumber
	SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs *foundation.NSNumber)
	ServerSideProcessingTimeout() *foundation.NSNumber
	SetServerSideProcessingTimeout(serverSideProcessingTimeout *foundation.NSNumber)
	GroupId() *foundation.NSNumber
	SetGroupId(groupId *foundation.NSNumber)
}

var _ MTRGroupsClusterAddGroupParamsable = (*MTRGroupsClusterAddGroupParams)(nil)
