// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// MTROvenCavityOperationalStateClusterErrorStateStruct is an idiomatic wrapper over the Objective-C class MTROvenCavityOperationalStateClusterErrorStateStruct.
type MTROvenCavityOperationalStateClusterErrorStateStruct struct {
	objref.Handle
}

// MTROvenCavityOperationalStateClusterErrorStateStructFromID adopts an existing Objective-C object as a MTROvenCavityOperationalStateClusterErrorStateStruct
// (nil for 0), retaining it and registering a release finalizer.
func MTROvenCavityOperationalStateClusterErrorStateStructFromID(id objc.ID) *MTROvenCavityOperationalStateClusterErrorStateStruct {
	if id == 0 {
		return nil
	}
	x := &MTROvenCavityOperationalStateClusterErrorStateStruct{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// mTROvenCavityOperationalStateClusterErrorStateStructAdopt wraps an Objective-C object that this code just created as a
// MTROvenCavityOperationalStateClusterErrorStateStruct (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTROvenCavityOperationalStateClusterErrorStateStructAdopt(id objc.ID) *MTROvenCavityOperationalStateClusterErrorStateStruct {
	if id == 0 {
		return nil
	}
	x := &MTROvenCavityOperationalStateClusterErrorStateStruct{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewMTROvenCavityOperationalStateClusterErrorStateStruct creates a new MTROvenCavityOperationalStateClusterErrorStateStruct.
func NewMTROvenCavityOperationalStateClusterErrorStateStruct() *MTROvenCavityOperationalStateClusterErrorStateStruct {
	_id := objc.Send[objc.ID](objc.ID(_class("MTROvenCavityOperationalStateClusterErrorStateStruct")), objc.RegisterName("new"))
	return mTROvenCavityOperationalStateClusterErrorStateStructAdopt(_id)
}

// WithErrorStateID sets errorStateID and returns the receiver so calls can be chained.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) WithErrorStateID(errorStateID obj.Object) *MTROvenCavityOperationalStateClusterErrorStateStruct {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateID:"), objref.IDOf(errorStateID))
	return x
}

// WithErrorStateLabel sets errorStateLabel and returns the receiver so calls can be chained.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) WithErrorStateLabel(errorStateLabel string) *MTROvenCavityOperationalStateClusterErrorStateStruct {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateLabel:"), purego.NSString(errorStateLabel))
	return x
}

// WithErrorStateDetails sets errorStateDetails and returns the receiver so calls can be chained.
func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) WithErrorStateDetails(errorStateDetails string) *MTROvenCavityOperationalStateClusterErrorStateStruct {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateDetails:"), purego.NSString(errorStateDetails))
	return x
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) ErrorStateID() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("errorStateID"))
	return obj.Wrap(_r)
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) SetErrorStateID(errorStateID obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateID:"), objref.IDOf(errorStateID))
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) ErrorStateLabel() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("errorStateLabel"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) SetErrorStateLabel(errorStateLabel string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateLabel:"), purego.NSString(errorStateLabel))
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) ErrorStateDetails() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("errorStateDetails"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

func (x *MTROvenCavityOperationalStateClusterErrorStateStruct) SetErrorStateDetails(errorStateDetails string) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setErrorStateDetails:"), purego.NSString(errorStateDetails))
}

// MTROvenCavityOperationalStateClusterErrorStateStructable is the interface implemented by [MTROvenCavityOperationalStateClusterErrorStateStruct], for mocking and DI.
type MTROvenCavityOperationalStateClusterErrorStateStructable interface {
	obj.Object
	WithErrorStateID(errorStateID obj.Object) *MTROvenCavityOperationalStateClusterErrorStateStruct
	WithErrorStateLabel(errorStateLabel string) *MTROvenCavityOperationalStateClusterErrorStateStruct
	WithErrorStateDetails(errorStateDetails string) *MTROvenCavityOperationalStateClusterErrorStateStruct
	ErrorStateID() obj.Object
	SetErrorStateID(errorStateID obj.Object)
	ErrorStateLabel() string
	SetErrorStateLabel(errorStateLabel string)
	ErrorStateDetails() string
	SetErrorStateDetails(errorStateDetails string)
}

var _ MTROvenCavityOperationalStateClusterErrorStateStructable = (*MTROvenCavityOperationalStateClusterErrorStateStruct)(nil)
