// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/matter"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
	"unsafe"
)

// MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams wraps [raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams] with a fluent Go API.
type MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams struct {
	inner *raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams
}

// Unwrap returns the underlying [raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams].
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) Unwrap() *raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams {
	return x.inner
}

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) ID() objc.ID {
	return x.inner.Ptr()
}

// MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsFromID adopts an existing object pointer as a MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams (nil for 0).
func MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsFromID(id objc.ID) *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams {
	if id == 0 {
		return nil
	}
	return &MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams{inner: raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsFromID(id)}
}

// Initialize an MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams with a response-value dictionary of the sort that MTRDeviceResponseHandler would receive. Will return nil and hand out an error if the response-value dictionary is not a command data response or is not the right command response. Will return nil and hand out an error if the data response does not match the known schema for this command.
//
// NewMTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsWithResponseValueError creates a new [MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams].
func NewMTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsWithResponseValueError(responseValue *foundation.NSDictionary[*foundation.NSString, objc.ID]) (*MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams, error) {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams")), objc.RegisterName("alloc"))
	var _nsErr uintptr
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithResponseValue:error:"), responseValue.Ptr(), unsafe.Pointer(&_nsErr))
	if _nsErr != 0 {
		return nil, purego.NSErrorToError(objc.ID(_nsErr))
	}
	return &MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams{inner: raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsFromID(_id)}, nil
}

// WithStatus sets the status property and returns the receiver for chaining.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) WithStatus(status *foundation.NSNumber) *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams {
	x.inner.SetStatus(status)
	return x
}

// WithStatusText sets the statusText property and returns the receiver for chaining.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) WithStatusText(statusText string) *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams {
	x.inner.SetStatusText(foundation.NSStringStringWithUTF8String(statusText))
	return x
}

// Status calls the underlying Status.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) Status() *foundation.NSNumber {
	return x.inner.Status()
}

// SetStatus calls the underlying SetStatus.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) SetStatus(status *foundation.NSNumber) {
	x.inner.SetStatus(status)
}

// StatusText calls the underlying StatusText.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) StatusText() string {
	_r := x.inner.StatusText()
	if _r == nil {
		return ""
	}
	return purego.GoString(_r.Ptr())
}

// SetStatusText calls the underlying SetStatusText.
func (x *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams) SetStatusText(statusText string) {
	x.inner.SetStatusText(foundation.NSStringStringWithUTF8String(statusText))
}

// MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsable is the interface implemented by [MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams], for mocking and DI.
type MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsable interface {
	Unwrap() *raw.MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams
	WithStatus(status *foundation.NSNumber) *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams
	WithStatusText(statusText string) *MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams
	Status() *foundation.NSNumber
	SetStatus(status *foundation.NSNumber)
	StatusText() string
	SetStatusText(statusText string)
}

var _ MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParamsable = (*MTRRefrigeratorAndTemperatureControlledCabinetModeClusterChangeToModeResponseParams)(nil)
