// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/matter"
	"github.com/ebitengine/purego/objc"
)

// MTRBaseClusterRVCCleanMode wraps [raw.MTRBaseClusterRVCCleanMode] with a fluent Go API.
type MTRBaseClusterRVCCleanMode struct {
	inner *raw.MTRBaseClusterRVCCleanMode
}

// Unwrap returns the underlying [raw.MTRBaseClusterRVCCleanMode].
func (x *MTRBaseClusterRVCCleanMode) Unwrap() *raw.MTRBaseClusterRVCCleanMode { return x.inner }

// NewMTRBaseClusterRVCCleanModeWithDeviceEndpointIDQueue creates a new [MTRBaseClusterRVCCleanMode].
func NewMTRBaseClusterRVCCleanModeWithDeviceEndpointIDQueue(device *raw.MTRBaseDevice, endpointID *foundation.NSNumber, queue *foundation.NSObject) *MTRBaseClusterRVCCleanMode {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("MTRBaseClusterRVCCleanMode")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithDevice:endpointID:queue:"), device.Ptr(), endpointID.Ptr(), queue.Ptr())
	return &MTRBaseClusterRVCCleanMode{inner: raw.MTRBaseClusterRVCCleanModeFromID(_id)}
}

func (x *MTRBaseClusterRVCCleanMode) asMTRGenericBaseCluster() *raw.MTRGenericBaseCluster { return &x.inner.MTRGenericBaseCluster }

func (x *MTRBaseClusterRVCCleanMode) asMTRCluster() *raw.MTRCluster { return &x.inner.MTRGenericBaseCluster.MTRCluster }

