// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/matter"
	"github.com/ebitengine/purego/objc"
)

// MTRDeviceEnergyManagementClusterCancelRequestParams wraps [raw.MTRDeviceEnergyManagementClusterCancelRequestParams] with a fluent Go API.
type MTRDeviceEnergyManagementClusterCancelRequestParams struct {
	inner *raw.MTRDeviceEnergyManagementClusterCancelRequestParams
}

// Unwrap returns the underlying [raw.MTRDeviceEnergyManagementClusterCancelRequestParams].
func (x *MTRDeviceEnergyManagementClusterCancelRequestParams) Unwrap() *raw.MTRDeviceEnergyManagementClusterCancelRequestParams { return x.inner }

// NewMTRDeviceEnergyManagementClusterCancelRequestParams creates a new [MTRDeviceEnergyManagementClusterCancelRequestParams].
func NewMTRDeviceEnergyManagementClusterCancelRequestParams() *MTRDeviceEnergyManagementClusterCancelRequestParams {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("MTRDeviceEnergyManagementClusterCancelRequestParams")), objc.RegisterName("new"))
	return &MTRDeviceEnergyManagementClusterCancelRequestParams{inner: raw.MTRDeviceEnergyManagementClusterCancelRequestParamsFromID(_id)}
}

// WithTimedInvokeTimeoutMs sets the timedInvokeTimeoutMs property and returns the receiver for chaining.
func (x *MTRDeviceEnergyManagementClusterCancelRequestParams) WithTimedInvokeTimeoutMs(timedInvokeTimeoutMs *foundation.NSNumber) *MTRDeviceEnergyManagementClusterCancelRequestParams {
	x.inner.SetTimedInvokeTimeoutMs(timedInvokeTimeoutMs)
	return x
}

// WithServerSideProcessingTimeout sets the serverSideProcessingTimeout property and returns the receiver for chaining.
func (x *MTRDeviceEnergyManagementClusterCancelRequestParams) WithServerSideProcessingTimeout(serverSideProcessingTimeout *foundation.NSNumber) *MTRDeviceEnergyManagementClusterCancelRequestParams {
	x.inner.SetServerSideProcessingTimeout(serverSideProcessingTimeout)
	return x
}

