// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package contacts

import (
	"runtime"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/rt"
	"github.com/ebitengine/purego/objc"
)

// ContactProperty is an idiomatic wrapper over the Objective-C class CNContactProperty.
//
// An object that represents a property of a contact.
type ContactProperty struct {
	objref.Handle
}

// ContactPropertyFromID adopts an existing Objective-C object as a ContactProperty
// (nil for 0), retaining it and registering a release finalizer.
func ContactPropertyFromID(id objc.ID) *ContactProperty {
	if id == 0 {
		return nil
	}
	x := &ContactProperty{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// contactPropertyAdopt wraps an Objective-C object that this code just created as a
// ContactProperty (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func contactPropertyAdopt(id objc.ID) *ContactProperty {
	if id == 0 {
		return nil
	}
	x := &ContactProperty{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (cp *ContactProperty) Description() string {
	defer runtime.KeepAlive(cp)
	return rt.Description(objref.IDOf(cp))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (cp *ContactProperty) IsEqual(other obj.Object) bool {
	defer runtime.KeepAlive(cp)
	defer runtime.KeepAlive(other)
	return rt.IsEqual(objref.IDOf(cp), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (cp *ContactProperty) IsKind(className string) bool {
	defer runtime.KeepAlive(cp)
	return rt.IsKind(objref.IDOf(cp), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (cp *ContactProperty) String() string {
	defer runtime.KeepAlive(cp)
	return rt.Description(objref.IDOf(cp))
}

// NewContactProperty creates a new ContactProperty.
func NewContactProperty() *ContactProperty {
	_id := objc.Send[objc.ID](objc.ID(_class("CNContactProperty")), objc.RegisterName("new"))
	return contactPropertyAdopt(_id)
}

// Contact returns the contact.
func (cp *ContactProperty) Contact() *Contact {
	defer runtime.KeepAlive(cp)
	_r := objc.Send[objc.ID](objref.IDOf(cp), objc.RegisterName("contact"))
	return ContactFromID(_r)
}

// Key returns the key of the contact property, as defined in CNContact.h.
func (cp *ContactProperty) Key() string {
	defer runtime.KeepAlive(cp)
	_r := objc.Send[objc.ID](objref.IDOf(cp), objc.RegisterName("key"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

// Value returns the value of the property.
func (cp *ContactProperty) Value() obj.Object {
	defer runtime.KeepAlive(cp)
	_r := objc.Send[objc.ID](objref.IDOf(cp), objc.RegisterName("value"))
	return obj.Wrap(_r)
}

// Identifier returns the identifier of the labeled value if the property is an array of labeled values, otherwise is nil.
func (cp *ContactProperty) Identifier() string {
	defer runtime.KeepAlive(cp)
	_r := objc.Send[objc.ID](objref.IDOf(cp), objc.RegisterName("identifier"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

// Label returns the label of the labeled value if the property is an array of labeled values, otherwise is nil.
func (cp *ContactProperty) Label() string {
	defer runtime.KeepAlive(cp)
	_r := objc.Send[objc.ID](objref.IDOf(cp), objc.RegisterName("label"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}
