// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package xar

import raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/raw/libraries/xar"

// These aliases re-export the raw xar bindings' exported
// types and values so callers name them through this package.

type (
	XarFileT      = raw.XarFileT
	XarHeader     = raw.XarHeader
	XarHeaderT    = raw.XarHeaderT
	XarIterT      = raw.XarIterT
	XarSignatureT = raw.XarSignatureT
	XarStream     = raw.XarStream
	XarSubdocT    = raw.XarSubdocT
	XarT          = raw.XarT
)
