// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"runtime"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/libraries/dispatch"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/ebitengine/purego/objc"
)

// MTRClusterBridgedDeviceBasic is an idiomatic wrapper over the Objective-C class MTRClusterBridgedDeviceBasic.
//
// It embeds [MTRClusterBridgedDeviceBasicInformation], promoting that type's methods.
type MTRClusterBridgedDeviceBasic struct {
	MTRClusterBridgedDeviceBasicInformation
}

// MTRClusterBridgedDeviceBasicFromID adopts an existing Objective-C object as a MTRClusterBridgedDeviceBasic
// (nil for 0), retaining it and registering a release finalizer.
func MTRClusterBridgedDeviceBasicFromID(id objc.ID) *MTRClusterBridgedDeviceBasic {
	if id == 0 {
		return nil
	}
	x := &MTRClusterBridgedDeviceBasic{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mTRClusterBridgedDeviceBasicAdopt wraps an Objective-C object that this code just created as a
// MTRClusterBridgedDeviceBasic (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTRClusterBridgedDeviceBasicAdopt(id objc.ID) *MTRClusterBridgedDeviceBasic {
	if id == 0 {
		return nil
	}
	x := &MTRClusterBridgedDeviceBasic{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewMTRClusterBridgedDeviceBasicWithDeviceEndpointQueue creates a new MTRClusterBridgedDeviceBasic.
func NewMTRClusterBridgedDeviceBasicWithDeviceEndpointQueue(device *MTRDevice, endpoint uint16, queue dispatch.Queue) *MTRClusterBridgedDeviceBasic {
	defer runtime.KeepAlive(device)
	_alloc := objc.Send[objc.ID](objc.ID(_class("MTRClusterBridgedDeviceBasic")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithDevice:endpoint:queue:"), objref.IDOf(device), endpoint, objc.ID(uintptr(queue.Ptr())))
	return mTRClusterBridgedDeviceBasicAdopt(_id)
}

var _ MTRClusterBridgedDeviceBasicInformationProvider = (*MTRClusterBridgedDeviceBasic)(nil)

var _ MTRGenericClusterProvider = (*MTRClusterBridgedDeviceBasic)(nil)

var _ MTRClusterProvider = (*MTRClusterBridgedDeviceBasic)(nil)
