// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package matter

import (
	"runtime"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/rt"
	"github.com/ebitengine/purego/objc"
)

// MTREnergyEVSEClusterEVConnectedEvent is an idiomatic wrapper over the Objective-C class MTREnergyEVSEClusterEVConnectedEvent.
type MTREnergyEVSEClusterEVConnectedEvent struct {
	objref.Handle
}

// MTREnergyEVSEClusterEVConnectedEventFromID adopts an existing Objective-C object as a MTREnergyEVSEClusterEVConnectedEvent
// (nil for 0), retaining it and registering a release finalizer.
func MTREnergyEVSEClusterEVConnectedEventFromID(id objc.ID) *MTREnergyEVSEClusterEVConnectedEvent {
	if id == 0 {
		return nil
	}
	x := &MTREnergyEVSEClusterEVConnectedEvent{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// mTREnergyEVSEClusterEVConnectedEventAdopt wraps an Objective-C object that this code just created as a
// MTREnergyEVSEClusterEVConnectedEvent (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func mTREnergyEVSEClusterEVConnectedEventAdopt(id objc.ID) *MTREnergyEVSEClusterEVConnectedEvent {
	if id == 0 {
		return nil
	}
	x := &MTREnergyEVSEClusterEVConnectedEvent{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) Description() string {
	defer runtime.KeepAlive(meecece)
	return rt.Description(objref.IDOf(meecece))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) IsEqual(other obj.Object) bool {
	defer runtime.KeepAlive(meecece)
	defer runtime.KeepAlive(other)
	return rt.IsEqual(objref.IDOf(meecece), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) IsKind(className string) bool {
	defer runtime.KeepAlive(meecece)
	return rt.IsKind(objref.IDOf(meecece), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) String() string {
	defer runtime.KeepAlive(meecece)
	return rt.Description(objref.IDOf(meecece))
}

// NewMTREnergyEVSEClusterEVConnectedEvent creates a new MTREnergyEVSEClusterEVConnectedEvent.
func NewMTREnergyEVSEClusterEVConnectedEvent() *MTREnergyEVSEClusterEVConnectedEvent {
	_id := objc.Send[objc.ID](objc.ID(_class("MTREnergyEVSEClusterEVConnectedEvent")), objc.RegisterName("new"))
	return mTREnergyEVSEClusterEVConnectedEventAdopt(_id)
}

// WithSessionID sets the session ID.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) WithSessionID(sessionID obj.Object) *MTREnergyEVSEClusterEVConnectedEvent {
	defer runtime.KeepAlive(sessionID)
	objc.Send[objc.ID](objref.IDOf(meecece), objc.RegisterName("setSessionID:"), objref.IDOf(sessionID))
	return meecece
}

// SessionID returns the session ID.
func (meecece *MTREnergyEVSEClusterEVConnectedEvent) SessionID() *foundation.Number {
	defer runtime.KeepAlive(meecece)
	_r := objc.Send[objc.ID](objref.IDOf(meecece), objc.RegisterName("sessionID"))
	return foundation.NumberFromID(_r)
}
