// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package metalperformanceshaders

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/metalperformanceshaders"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/mpsneuralnetwork"
	"github.com/ebitengine/purego/objc"
)

// CNNSubPixelConvolutionDescriptor wraps [raw.MPSCNNSubPixelConvolutionDescriptor] with a fluent Go API.
type CNNSubPixelConvolutionDescriptor struct {
	inner *raw.MPSCNNSubPixelConvolutionDescriptor
}

// Unwrap returns the underlying [raw.MPSCNNSubPixelConvolutionDescriptor].
func (x *CNNSubPixelConvolutionDescriptor) Unwrap() *raw.MPSCNNSubPixelConvolutionDescriptor {
	return x.inner
}

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *CNNSubPixelConvolutionDescriptor) ID() objc.ID { return x.inner.Ptr() }

// CNNSubPixelConvolutionDescriptorFromID adopts an existing object pointer as a CNNSubPixelConvolutionDescriptor (nil for 0).
func CNNSubPixelConvolutionDescriptorFromID(id objc.ID) *CNNSubPixelConvolutionDescriptor {
	if id == 0 {
		return nil
	}
	return &CNNSubPixelConvolutionDescriptor{inner: raw.MPSCNNSubPixelConvolutionDescriptorFromID(id)}
}

// NewCNNSubPixelConvolutionDescriptor creates a new [CNNSubPixelConvolutionDescriptor].
func NewCNNSubPixelConvolutionDescriptor() *CNNSubPixelConvolutionDescriptor {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("MPSCNNSubPixelConvolutionDescriptor")), objc.RegisterName("new"))
	return &CNNSubPixelConvolutionDescriptor{inner: raw.MPSCNNSubPixelConvolutionDescriptorFromID(_id)}
}

// WithSubPixelScaleFactor sets the subPixelScaleFactor property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithSubPixelScaleFactor(subPixelScaleFactor uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.SetSubPixelScaleFactor(subPixelScaleFactor)
	return x
}

// WithKernelWidth sets the kernelWidth property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithKernelWidth(kernelWidth uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetKernelWidth(kernelWidth)
	return x
}

// WithKernelHeight sets the kernelHeight property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithKernelHeight(kernelHeight uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetKernelHeight(kernelHeight)
	return x
}

// WithInputFeatureChannels sets the inputFeatureChannels property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithInputFeatureChannels(inputFeatureChannels uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetInputFeatureChannels(inputFeatureChannels)
	return x
}

// WithOutputFeatureChannels sets the outputFeatureChannels property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithOutputFeatureChannels(outputFeatureChannels uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetOutputFeatureChannels(outputFeatureChannels)
	return x
}

// WithStrideInPixelsX sets the strideInPixelsX property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithStrideInPixelsX(strideInPixelsX uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetStrideInPixelsX(strideInPixelsX)
	return x
}

// WithStrideInPixelsY sets the strideInPixelsY property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithStrideInPixelsY(strideInPixelsY uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetStrideInPixelsY(strideInPixelsY)
	return x
}

// WithGroups sets the groups property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithGroups(groups uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetGroups(groups)
	return x
}

// WithDilationRateX sets the dilationRateX property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithDilationRateX(dilationRateX uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetDilationRateX(dilationRateX)
	return x
}

// WithDilationRateY sets the dilationRateY property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithDilationRateY(dilationRateY uint) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetDilationRateY(dilationRateY)
	return x
}

// WithFusedNeuronDescriptor sets the fusedNeuronDescriptor property and returns the receiver for chaining.
func (x *CNNSubPixelConvolutionDescriptor) WithFusedNeuronDescriptor(fusedNeuronDescriptor *mpsneuralnetwork.MPSNNNeuronDescriptor) *CNNSubPixelConvolutionDescriptor {
	x.inner.MPSCNNConvolutionDescriptor.SetFusedNeuronDescriptor(fusedNeuronDescriptor)
	return x
}

// SubPixelScaleFactor calls the underlying SubPixelScaleFactor.
func (x *CNNSubPixelConvolutionDescriptor) SubPixelScaleFactor() uint {
	return x.inner.SubPixelScaleFactor()
}

// SetSubPixelScaleFactor calls the underlying SetSubPixelScaleFactor.
func (x *CNNSubPixelConvolutionDescriptor) SetSubPixelScaleFactor(subPixelScaleFactor uint) {
	x.inner.SetSubPixelScaleFactor(subPixelScaleFactor)
}

func (x *CNNSubPixelConvolutionDescriptor) asCNNConvolutionDescriptor() *mpsneuralnetwork.MPSCNNConvolutionDescriptor {
	return &x.inner.MPSCNNConvolutionDescriptor
}

// CNNSubPixelConvolutionDescriptorable is the interface implemented by [CNNSubPixelConvolutionDescriptor], for mocking and DI.
type CNNSubPixelConvolutionDescriptorable interface {
	Unwrap() *raw.MPSCNNSubPixelConvolutionDescriptor
	WithSubPixelScaleFactor(subPixelScaleFactor uint) *CNNSubPixelConvolutionDescriptor
	WithKernelWidth(kernelWidth uint) *CNNSubPixelConvolutionDescriptor
	WithKernelHeight(kernelHeight uint) *CNNSubPixelConvolutionDescriptor
	WithInputFeatureChannels(inputFeatureChannels uint) *CNNSubPixelConvolutionDescriptor
	WithOutputFeatureChannels(outputFeatureChannels uint) *CNNSubPixelConvolutionDescriptor
	WithStrideInPixelsX(strideInPixelsX uint) *CNNSubPixelConvolutionDescriptor
	WithStrideInPixelsY(strideInPixelsY uint) *CNNSubPixelConvolutionDescriptor
	WithGroups(groups uint) *CNNSubPixelConvolutionDescriptor
	WithDilationRateX(dilationRateX uint) *CNNSubPixelConvolutionDescriptor
	WithDilationRateY(dilationRateY uint) *CNNSubPixelConvolutionDescriptor
	WithFusedNeuronDescriptor(fusedNeuronDescriptor *mpsneuralnetwork.MPSNNNeuronDescriptor) *CNNSubPixelConvolutionDescriptor
	SubPixelScaleFactor() uint
	SetSubPixelScaleFactor(subPixelScaleFactor uint)
}

var _ CNNSubPixelConvolutionDescriptorable = (*CNNSubPixelConvolutionDescriptor)(nil)
