// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package metalperformanceshaders

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/foundation"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/metal"
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/metalperformanceshaders"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/mpscore"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/mpsimage"
	"github.com/ebitengine/purego/objc"
)

// A filter that returns the mean value for each row in an image.
//
// ImageReduceRowMean wraps [raw.MPSImageReduceRowMean] with a fluent Go API.
type ImageReduceRowMean struct {
	inner *raw.MPSImageReduceRowMean
}

// Unwrap returns the underlying [raw.MPSImageReduceRowMean].
func (x *ImageReduceRowMean) Unwrap() *raw.MPSImageReduceRowMean { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *ImageReduceRowMean) ID() objc.ID { return x.inner.Ptr() }

// ImageReduceRowMeanFromID adopts an existing object pointer as a ImageReduceRowMean (nil for 0).
func ImageReduceRowMeanFromID(id objc.ID) *ImageReduceRowMean {
	if id == 0 {
		return nil
	}
	return &ImageReduceRowMean{inner: raw.MPSImageReduceRowMeanFromID(id)}
}

// NewImageReduceRowMeanWithDevice creates a new [ImageReduceRowMean].
func NewImageReduceRowMeanWithDevice(device metal.MTLDevice) *ImageReduceRowMean {
	_alloc := objc.Send[objc.ID](objc.ID(objc.GetClass("MPSImageReduceRowMean")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithDevice:"), device)
	return &ImageReduceRowMean{inner: raw.MPSImageReduceRowMeanFromID(_id)}
}

// @property   clipRectSource @abstract   The source rectangle to use when reading data. @discussion A MTLRegion that indicates which part of the source to read. If the clipRectSource does not lie completely within the source image, the intersection of the image bounds and clipRectSource will be used. The clipRectSource replaces the MPSUnaryImageKernel offset parameter for this filter. The latter is ignored.   Default: MPSRectNoClip, use the entire source texture. The clipRect specified in MPSUnaryImageKernel is used to control the origin in the destination texture where the min, max values are written.  The clipRect.width must be >=2.  The clipRect.height must be >= 1.
//
// WithClipRectSource sets the clipRectSource property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithClipRectSource(clipRectSource metal.MTLRegion) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.SetClipRectSource(clipRectSource)
	return x
}

// The position of the destination clip rectangle origin relative to the source buffer.
//
// WithOffset sets the offset property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithOffset(offset mpscore.MPSOffset) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.SetOffset(offset)
	return x
}

// An optional clip rectangle to use when writing data. Only the pixels in the rectangle will be overwritten.
//
// WithClipRect sets the clipRect property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithClipRect(clipRect metal.MTLRegion) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.SetClipRect(clipRect)
	return x
}

// The edge mode to use when texture reads stray off the edge of an image.
//
// WithEdgeMode sets the edgeMode property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithEdgeMode(edgeMode mpscore.MPSImageEdgeMode) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.SetEdgeMode(edgeMode)
	return x
}

// The set of options used to run the kernel.
//
// WithOptions sets the options property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithOptions(options mpscore.MPSKernelOptions) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.MPSKernel.SetOptions(options)
	return x
}

// The string that identifies the kernel.
//
// WithLabel sets the label property and returns the receiver for chaining.
func (x *ImageReduceRowMean) WithLabel(label string) *ImageReduceRowMean {
	x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.MPSKernel.SetLabel(foundation.NSStringStringWithUTF8String(label))
	return x
}

func (x *ImageReduceRowMean) asImageReduceUnary() *mpsimage.MPSImageReduceUnary {
	return &x.inner.MPSImageReduceUnary
}

func (x *ImageReduceRowMean) asUnaryImageKernel() *mpsimage.MPSUnaryImageKernel {
	return &x.inner.MPSImageReduceUnary.MPSUnaryImageKernel
}

func (x *ImageReduceRowMean) asKernel() *mpscore.MPSKernel {
	return &x.inner.MPSImageReduceUnary.MPSUnaryImageKernel.MPSKernel
}

// ImageReduceRowMeanable is the interface implemented by [ImageReduceRowMean], for mocking and DI.
type ImageReduceRowMeanable interface {
	Unwrap() *raw.MPSImageReduceRowMean
	WithClipRectSource(clipRectSource metal.MTLRegion) *ImageReduceRowMean
	WithOffset(offset mpscore.MPSOffset) *ImageReduceRowMean
	WithClipRect(clipRect metal.MTLRegion) *ImageReduceRowMean
	WithEdgeMode(edgeMode mpscore.MPSImageEdgeMode) *ImageReduceRowMean
	WithOptions(options mpscore.MPSKernelOptions) *ImageReduceRowMean
	WithLabel(label string) *ImageReduceRowMean
}

var _ ImageReduceRowMeanable = (*ImageReduceRowMean)(nil)
