// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package metalperformanceshaders

import (
	raw "github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/metalperformanceshaders"
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/frameworks/mpscore"
	"github.com/ebitengine/purego/objc"
)

// A description of attributes used to create an MPS matrix.
//
// MatrixDescriptor wraps [raw.MPSMatrixDescriptor] with a fluent Go API.
type MatrixDescriptor struct {
	inner *raw.MPSMatrixDescriptor
}

// Unwrap returns the underlying [raw.MPSMatrixDescriptor].
func (x *MatrixDescriptor) Unwrap() *raw.MPSMatrixDescriptor { return x.inner }

// ID returns the underlying Objective-C object pointer (objc.ID), for
// passing to C APIs that take an object or CFTypeRef pointer.
func (x *MatrixDescriptor) ID() objc.ID { return x.inner.Ptr() }

// MatrixDescriptorFromID adopts an existing object pointer as a MatrixDescriptor (nil for 0).
func MatrixDescriptorFromID(id objc.ID) *MatrixDescriptor {
	if id == 0 {
		return nil
	}
	return &MatrixDescriptor{inner: raw.MPSMatrixDescriptorFromID(id)}
}

// NewMatrixDescriptor creates a new [MatrixDescriptor].
func NewMatrixDescriptor() *MatrixDescriptor {
	_id := objc.Send[objc.ID](objc.ID(objc.GetClass("MPSMatrixDescriptor")), objc.RegisterName("new"))
	return &MatrixDescriptor{inner: raw.MPSMatrixDescriptorFromID(_id)}
}

// The number of rows in the matrix.
//
// WithRows sets the rows property and returns the receiver for chaining.
func (x *MatrixDescriptor) WithRows(rows uint) *MatrixDescriptor {
	x.inner.SetRows(rows)
	return x
}

// The number of columns in the matrix.
//
// WithColumns sets the columns property and returns the receiver for chaining.
func (x *MatrixDescriptor) WithColumns(columns uint) *MatrixDescriptor {
	x.inner.SetColumns(columns)
	return x
}

// The type of the values in the matrix.
//
// WithDataType sets the dataType property and returns the receiver for chaining.
func (x *MatrixDescriptor) WithDataType(dataType mpscore.MPSDataType) *MatrixDescriptor {
	x.inner.SetDataType(dataType)
	return x
}

// The stride, in bytes, between corresponding elements of consecutive rows in the matrix.
//
// WithRowBytes sets the rowBytes property and returns the receiver for chaining.
func (x *MatrixDescriptor) WithRowBytes(rowBytes uint) *MatrixDescriptor {
	x.inner.SetRowBytes(rowBytes)
	return x
}

// @property   rows @discussion The number of rows in a matrix.
//
// Rows calls the underlying Rows.
func (x *MatrixDescriptor) Rows() uint {
	return x.inner.Rows()
}

// SetRows calls the underlying SetRows.
func (x *MatrixDescriptor) SetRows(rows uint) {
	x.inner.SetRows(rows)
}

// @property   columns @discussion The number of columns in a matrix.
//
// Columns calls the underlying Columns.
func (x *MatrixDescriptor) Columns() uint {
	return x.inner.Columns()
}

// SetColumns calls the underlying SetColumns.
func (x *MatrixDescriptor) SetColumns(columns uint) {
	x.inner.SetColumns(columns)
}

// @property   matrices @discussion The number of matrices.
//
// Matrices calls the underlying Matrices.
func (x *MatrixDescriptor) Matrices() uint {
	return x.inner.Matrices()
}

// @property   dataType @discussion The type of the data which makes up the values of the matrix.
//
// DataType calls the underlying DataType.
func (x *MatrixDescriptor) DataType() mpscore.MPSDataType {
	return x.inner.DataType()
}

// SetDataType calls the underlying SetDataType.
func (x *MatrixDescriptor) SetDataType(dataType mpscore.MPSDataType) {
	x.inner.SetDataType(dataType)
}

// @property   rowBytes @discussion The stride, in bytes, between corresponding elements of consecutive rows.  Must be a multiple of the element size.
//
// RowBytes calls the underlying RowBytes.
func (x *MatrixDescriptor) RowBytes() uint {
	return x.inner.RowBytes()
}

// SetRowBytes calls the underlying SetRowBytes.
func (x *MatrixDescriptor) SetRowBytes(rowBytes uint) {
	x.inner.SetRowBytes(rowBytes)
}

// @property   matrixBytes @discussion The stride, in bytes, between corresponding elements of consecutive matrices.  Must be a multiple of rowBytes.
//
// MatrixBytes calls the underlying MatrixBytes.
func (x *MatrixDescriptor) MatrixBytes() uint {
	return x.inner.MatrixBytes()
}

// MatrixDescriptorable is the interface implemented by [MatrixDescriptor], for mocking and DI.
type MatrixDescriptorable interface {
	Unwrap() *raw.MPSMatrixDescriptor
	WithRows(rows uint) *MatrixDescriptor
	WithColumns(columns uint) *MatrixDescriptor
	WithDataType(dataType mpscore.MPSDataType) *MatrixDescriptor
	WithRowBytes(rowBytes uint) *MatrixDescriptor
	Rows() uint
	SetRows(rows uint)
	Columns() uint
	SetColumns(columns uint)
	Matrices() uint
	DataType() mpscore.MPSDataType
	SetDataType(dataType mpscore.MPSDataType)
	RowBytes() uint
	SetRowBytes(rowBytes uint)
	MatrixBytes() uint
}

var _ MatrixDescriptorable = (*MatrixDescriptor)(nil)
