// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package foundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// PropertyListSerialization is an idiomatic wrapper over the Objective-C class NSPropertyListSerialization.
//
// An object that converts between a property list and one of several serialized representations.
type PropertyListSerialization struct {
	objref.Handle
}

// PropertyListSerializationFromID adopts an existing Objective-C object as a PropertyListSerialization
// (nil for 0), retaining it and registering a release finalizer.
func PropertyListSerializationFromID(id objc.ID) *PropertyListSerialization {
	if id == 0 {
		return nil
	}
	x := &PropertyListSerialization{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// propertyListSerializationAdopt wraps an Objective-C object that this code just created as a
// PropertyListSerialization (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func propertyListSerializationAdopt(id objc.ID) *PropertyListSerialization {
	if id == 0 {
		return nil
	}
	x := &PropertyListSerialization{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (pls *PropertyListSerialization) Description() string {
	return rt.Description(objref.IDOf(pls))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (pls *PropertyListSerialization) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(pls), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (pls *PropertyListSerialization) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(pls), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (pls *PropertyListSerialization) String() string {
	return rt.Description(objref.IDOf(pls))
}

// NewPropertyListSerialization creates a new PropertyListSerialization.
func NewPropertyListSerialization() *PropertyListSerialization {
	_id := objc.Send[objc.ID](objc.ID(_class("NSPropertyListSerialization")), objc.RegisterName("new"))
	return propertyListSerializationAdopt(_id)
}

// WithScriptingProperties sets the property and returns the receiver so calls can be chained.
func (pls *PropertyListSerialization) WithScriptingProperties(scriptingProperties obj.Object) *PropertyListSerialization {
	objc.Send[objc.ID](objref.IDOf(pls), objc.RegisterName("setScriptingProperties:"), objref.IDOf(scriptingProperties))
	return pls
}
