// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package foundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// ScriptExecutionContext is an idiomatic wrapper over the Objective-C class NSScriptExecutionContext.
//
// The context in which the current script command is executed.
type ScriptExecutionContext struct {
	objref.Handle
}

// ScriptExecutionContextFromID adopts an existing Objective-C object as a ScriptExecutionContext
// (nil for 0), retaining it and registering a release finalizer.
func ScriptExecutionContextFromID(id objc.ID) *ScriptExecutionContext {
	if id == 0 {
		return nil
	}
	x := &ScriptExecutionContext{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// scriptExecutionContextAdopt wraps an Objective-C object that this code just created as a
// ScriptExecutionContext (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func scriptExecutionContextAdopt(id objc.ID) *ScriptExecutionContext {
	if id == 0 {
		return nil
	}
	x := &ScriptExecutionContext{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (sec *ScriptExecutionContext) Description() string {
	return rt.Description(objref.IDOf(sec))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (sec *ScriptExecutionContext) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(sec), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (sec *ScriptExecutionContext) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(sec), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (sec *ScriptExecutionContext) String() string {
	return rt.Description(objref.IDOf(sec))
}

// NewScriptExecutionContext creates a new ScriptExecutionContext.
func NewScriptExecutionContext() *ScriptExecutionContext {
	_id := objc.Send[objc.ID](objc.ID(_class("NSScriptExecutionContext")), objc.RegisterName("new"))
	return scriptExecutionContextAdopt(_id)
}

// WithTopLevelObject sets sets the top-level object for an object-specifier evaluation.
func (sec *ScriptExecutionContext) WithTopLevelObject(topLevelObject obj.Object) *ScriptExecutionContext {
	objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("setTopLevelObject:"), objref.IDOf(topLevelObject))
	return sec
}

// WithObjectBeingTested sets sets the top-level container object currently being tested in a “whose” qualifier to a given object.
func (sec *ScriptExecutionContext) WithObjectBeingTested(objectBeingTested obj.Object) *ScriptExecutionContext {
	objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("setObjectBeingTested:"), objref.IDOf(objectBeingTested))
	return sec
}

// WithRangeContainerObject sets sets the top-level container object for a range-specifier evaluation to a give object.
func (sec *ScriptExecutionContext) WithRangeContainerObject(rangeContainerObject obj.Object) *ScriptExecutionContext {
	objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("setRangeContainerObject:"), objref.IDOf(rangeContainerObject))
	return sec
}

// WithScriptingProperties sets the property and returns the receiver so calls can be chained.
func (sec *ScriptExecutionContext) WithScriptingProperties(scriptingProperties obj.Object) *ScriptExecutionContext {
	objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("setScriptingProperties:"), objref.IDOf(scriptingProperties))
	return sec
}

// TopLevelObject wraps the corresponding Objective-C method.
func (sec *ScriptExecutionContext) TopLevelObject() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("topLevelObject"))
	return obj.Wrap(_r)
}

// ObjectBeingTested wraps the corresponding Objective-C method.
func (sec *ScriptExecutionContext) ObjectBeingTested() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("objectBeingTested"))
	return obj.Wrap(_r)
}

// RangeContainerObject wraps the corresponding Objective-C method.
func (sec *ScriptExecutionContext) RangeContainerObject() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(sec), objc.RegisterName("rangeContainerObject"))
	return obj.Wrap(_r)
}
