// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package foundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// UserUnixTask is an idiomatic wrapper over the Objective-C class NSUserUnixTask.
//
// It embeds [UserScriptTask], promoting that type's methods.
//
// An object that executes unix applications.
type UserUnixTask struct {
	UserScriptTask
}

// UserUnixTaskFromID adopts an existing Objective-C object as a UserUnixTask
// (nil for 0), retaining it and registering a release finalizer.
func UserUnixTaskFromID(id objc.ID) *UserUnixTask {
	if id == 0 {
		return nil
	}
	x := &UserUnixTask{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// userUnixTaskAdopt wraps an Objective-C object that this code just created as a
// UserUnixTask (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func userUnixTaskAdopt(id objc.ID) *UserUnixTask {
	if id == 0 {
		return nil
	}
	x := &UserUnixTask{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewUserUnixTask creates a new UserUnixTask.
func NewUserUnixTask() *UserUnixTask {
	_id := objc.Send[objc.ID](objc.ID(_class("NSUserUnixTask")), objc.RegisterName("new"))
	return userUnixTaskAdopt(_id)
}

// WithStandardInput the standard input stream.
func (x *UserUnixTask) WithStandardInput(standardInput *FileHandle) *UserUnixTask {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardInput:"), objref.IDOf(standardInput))
	return x
}

// WithStandardOutput the standard output stream.
func (x *UserUnixTask) WithStandardOutput(standardOutput *FileHandle) *UserUnixTask {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardOutput:"), objref.IDOf(standardOutput))
	return x
}

// WithStandardError the standard error stream.
func (x *UserUnixTask) WithStandardError(standardError *FileHandle) *UserUnixTask {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardError:"), objref.IDOf(standardError))
	return x
}

// WithScriptingProperties sets the property and returns the receiver so calls can be chained.
func (x *UserUnixTask) WithScriptingProperties(scriptingProperties obj.Object) *UserUnixTask {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setScriptingProperties:"), objref.IDOf(scriptingProperties))
	return x
}

// StandardInput wraps the corresponding Objective-C method.
func (x *UserUnixTask) StandardInput() *FileHandle {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("standardInput"))
	return FileHandleFromID(_r)
}

// SetStandardInput wraps the corresponding Objective-C method.
func (x *UserUnixTask) SetStandardInput(standardInput *FileHandle) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardInput:"), objref.IDOf(standardInput))
}

// StandardOutput wraps the corresponding Objective-C method.
func (x *UserUnixTask) StandardOutput() *FileHandle {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("standardOutput"))
	return FileHandleFromID(_r)
}

// SetStandardOutput wraps the corresponding Objective-C method.
func (x *UserUnixTask) SetStandardOutput(standardOutput *FileHandle) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardOutput:"), objref.IDOf(standardOutput))
}

// StandardError wraps the corresponding Objective-C method.
func (x *UserUnixTask) StandardError() *FileHandle {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("standardError"))
	return FileHandleFromID(_r)
}

// SetStandardError wraps the corresponding Objective-C method.
func (x *UserUnixTask) SetStandardError(standardError *FileHandle) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setStandardError:"), objref.IDOf(standardError))
}

// UserUnixTaskable is the interface implemented by [UserUnixTask], for mocking and DI.
type UserUnixTaskable interface {
	obj.Object
	WithStandardInput(standardInput *FileHandle) *UserUnixTask
	WithStandardOutput(standardOutput *FileHandle) *UserUnixTask
	WithStandardError(standardError *FileHandle) *UserUnixTask
	WithScriptingProperties(scriptingProperties obj.Object) *UserUnixTask
	StandardInput() *FileHandle
	SetStandardInput(standardInput *FileHandle)
	StandardOutput() *FileHandle
	SetStandardOutput(standardOutput *FileHandle)
	StandardError() *FileHandle
	SetStandardError(standardError *FileHandle)
}

var _ UserUnixTaskable = (*UserUnixTask)(nil)

var _ UserScriptTaskProvider = (*UserUnixTask)(nil)
