// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package foundation

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// An event driven parser of XML documents (including DTD declarations).
//
// XMLParser is an idiomatic wrapper over the Objective-C class NSXMLParser.
type XMLParser struct {
	objref.Handle
}

// XMLParserFromID adopts an existing Objective-C object as a XMLParser
// (nil for 0), retaining it and registering a release finalizer.
func XMLParserFromID(id objc.ID) *XMLParser {
	if id == 0 {
		return nil
	}
	x := &XMLParser{Handle: objref.Wrap(purego.Retain(id))}
	objref.Track(x)
	return x
}

// xMLParserAdopt wraps an Objective-C object that this code just created as a
// XMLParser (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func xMLParserAdopt(id objc.ID) *XMLParser {
	if id == 0 {
		return nil
	}
	x := &XMLParser{Handle: objref.Wrap(id)}
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (x *XMLParser) Description() string {
	return rt.Description(objref.IDOf(x))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (x *XMLParser) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(x), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (x *XMLParser) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(x), className)
}

// NewXMLParserWithContentsOfURL creates a new XMLParser.
func NewXMLParserWithContentsOfURL(url string) *XMLParser {
	_alloc := objc.Send[objc.ID](objc.ID(_class("NSXMLParser")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithContentsOfURL:"), rt.FileURL(url))
	return xMLParserAdopt(_id)
}

// NewXMLParserWithData creates a new XMLParser.
func NewXMLParserWithData(data *Data) *XMLParser {
	_alloc := objc.Send[objc.ID](objc.ID(_class("NSXMLParser")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithData:"), objref.IDOf(data))
	return xMLParserAdopt(_id)
}

// NewXMLParserWithStream creates a new XMLParser.
func NewXMLParserWithStream(stream *InputStream) *XMLParser {
	_alloc := objc.Send[objc.ID](objc.ID(_class("NSXMLParser")), objc.RegisterName("alloc"))
	_id := objc.Send[objc.ID](_alloc, objc.RegisterName("initWithStream:"), objref.IDOf(stream))
	return xMLParserAdopt(_id)
}

// WithShouldProcessNamespaces sets shouldProcessNamespaces and returns the receiver so calls can be chained.
func (x *XMLParser) WithShouldProcessNamespaces(shouldProcessNamespaces bool) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldProcessNamespaces:"), shouldProcessNamespaces)
	return x
}

// WithShouldReportNamespacePrefixes sets shouldReportNamespacePrefixes and returns the receiver so calls can be chained.
func (x *XMLParser) WithShouldReportNamespacePrefixes(shouldReportNamespacePrefixes bool) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldReportNamespacePrefixes:"), shouldReportNamespacePrefixes)
	return x
}

// WithExternalEntityResolvingPolicy sets externalEntityResolvingPolicy and returns the receiver so calls can be chained.
func (x *XMLParser) WithExternalEntityResolvingPolicy(externalEntityResolvingPolicy XMLParserExternalEntityResolvingPolicy) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setExternalEntityResolvingPolicy:"), externalEntityResolvingPolicy)
	return x
}

// WithAllowedExternalEntityURLs sets allowedExternalEntityURLs and returns the receiver so calls can be chained.
func (x *XMLParser) WithAllowedExternalEntityURLs(allowedExternalEntityURLs obj.Object) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setAllowedExternalEntityURLs:"), objref.IDOf(allowedExternalEntityURLs))
	return x
}

// WithShouldResolveExternalEntities sets shouldResolveExternalEntities and returns the receiver so calls can be chained.
func (x *XMLParser) WithShouldResolveExternalEntities(shouldResolveExternalEntities bool) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldResolveExternalEntities:"), shouldResolveExternalEntities)
	return x
}

// WithScriptingProperties sets scriptingProperties and returns the receiver so calls can be chained.
func (x *XMLParser) WithScriptingProperties(scriptingProperties obj.Object) *XMLParser {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setScriptingProperties:"), objref.IDOf(scriptingProperties))
	return x
}

func (x *XMLParser) Parse() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("parse"))
	return _r
}

func (x *XMLParser) AbortParsing() {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("abortParsing"))
}

func (x *XMLParser) ShouldProcessNamespaces() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("shouldProcessNamespaces"))
	return _r
}

func (x *XMLParser) SetShouldProcessNamespaces(shouldProcessNamespaces bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldProcessNamespaces:"), shouldProcessNamespaces)
}

func (x *XMLParser) ShouldReportNamespacePrefixes() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("shouldReportNamespacePrefixes"))
	return _r
}

func (x *XMLParser) SetShouldReportNamespacePrefixes(shouldReportNamespacePrefixes bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldReportNamespacePrefixes:"), shouldReportNamespacePrefixes)
}

func (x *XMLParser) ExternalEntityResolvingPolicy() XMLParserExternalEntityResolvingPolicy {
	_r := objc.Send[XMLParserExternalEntityResolvingPolicy](objref.IDOf(x), objc.RegisterName("externalEntityResolvingPolicy"))
	return _r
}

func (x *XMLParser) SetExternalEntityResolvingPolicy(externalEntityResolvingPolicy XMLParserExternalEntityResolvingPolicy) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setExternalEntityResolvingPolicy:"), externalEntityResolvingPolicy)
}

func (x *XMLParser) AllowedExternalEntityURLs() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("allowedExternalEntityURLs"))
	return obj.Wrap(_r)
}

func (x *XMLParser) SetAllowedExternalEntityURLs(allowedExternalEntityURLs obj.Object) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setAllowedExternalEntityURLs:"), objref.IDOf(allowedExternalEntityURLs))
}

func (x *XMLParser) ShouldResolveExternalEntities() bool {
	_r := objc.Send[bool](objref.IDOf(x), objc.RegisterName("shouldResolveExternalEntities"))
	return _r
}

func (x *XMLParser) SetShouldResolveExternalEntities(shouldResolveExternalEntities bool) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setShouldResolveExternalEntities:"), shouldResolveExternalEntities)
}

func (x *XMLParser) PublicID() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("publicID"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

func (x *XMLParser) SystemID() string {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("systemID"))
	if _r == 0 {
		return ""
	}
	return purego.GoString(_r)
}

func (x *XMLParser) LineNumber() int {
	_r := objc.Send[int](objref.IDOf(x), objc.RegisterName("lineNumber"))
	return _r
}

func (x *XMLParser) ColumnNumber() int {
	_r := objc.Send[int](objref.IDOf(x), objc.RegisterName("columnNumber"))
	return _r
}

// XMLParserable is the interface implemented by [XMLParser], for mocking and DI.
type XMLParserable interface {
	obj.Object
	WithShouldProcessNamespaces(shouldProcessNamespaces bool) *XMLParser
	WithShouldReportNamespacePrefixes(shouldReportNamespacePrefixes bool) *XMLParser
	WithExternalEntityResolvingPolicy(externalEntityResolvingPolicy XMLParserExternalEntityResolvingPolicy) *XMLParser
	WithAllowedExternalEntityURLs(allowedExternalEntityURLs obj.Object) *XMLParser
	WithShouldResolveExternalEntities(shouldResolveExternalEntities bool) *XMLParser
	WithScriptingProperties(scriptingProperties obj.Object) *XMLParser
	Parse() bool
	AbortParsing()
	ShouldProcessNamespaces() bool
	SetShouldProcessNamespaces(shouldProcessNamespaces bool)
	ShouldReportNamespacePrefixes() bool
	SetShouldReportNamespacePrefixes(shouldReportNamespacePrefixes bool)
	ExternalEntityResolvingPolicy() XMLParserExternalEntityResolvingPolicy
	SetExternalEntityResolvingPolicy(externalEntityResolvingPolicy XMLParserExternalEntityResolvingPolicy)
	AllowedExternalEntityURLs() obj.Object
	SetAllowedExternalEntityURLs(allowedExternalEntityURLs obj.Object)
	ShouldResolveExternalEntities() bool
	SetShouldResolveExternalEntities(shouldResolveExternalEntities bool)
	PublicID() string
	SystemID() string
	LineNumber() int
	ColumnNumber() int
}

var _ XMLParserable = (*XMLParser)(nil)
