// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package healthkit

import (
	"unsafe"

	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/rt"
	"github.com/ebitengine/purego/objc"
)

// StatisticsCollection is an idiomatic wrapper over the Objective-C class HKStatisticsCollection.
//
// An object that manages a collection of statistics, representing the results calculated over separate time intervals.
type StatisticsCollection struct {
	objref.Handle
}

// StatisticsCollectionFromID adopts an existing Objective-C object as a StatisticsCollection
// (nil for 0), retaining it and registering a release finalizer.
func StatisticsCollectionFromID(id objc.ID) *StatisticsCollection {
	if id == 0 {
		return nil
	}
	x := &StatisticsCollection{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// statisticsCollectionAdopt wraps an Objective-C object that this code just created as a
// StatisticsCollection (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func statisticsCollectionAdopt(id objc.ID) *StatisticsCollection {
	if id == 0 {
		return nil
	}
	x := &StatisticsCollection{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// Description returns the object's -description text.
func (sc *StatisticsCollection) Description() string {
	return rt.Description(objref.IDOf(sc))
}

// IsEqual reports Objective-C equality (isEqual:) with another object.
func (sc *StatisticsCollection) IsEqual(other obj.Object) bool {
	return rt.IsEqual(objref.IDOf(sc), objref.IDOf(other))
}

// IsKind reports whether the object is an instance of the named class or a subclass.
func (sc *StatisticsCollection) IsKind(className string) bool {
	return rt.IsKind(objref.IDOf(sc), className)
}

// String returns the object's -description text, so a wrapper prints usefully
// under fmt.
func (sc *StatisticsCollection) String() string {
	return rt.Description(objref.IDOf(sc))
}

// NewStatisticsCollection creates a new StatisticsCollection.
func NewStatisticsCollection() *StatisticsCollection {
	_id := objc.Send[objc.ID](objc.ID(_class("HKStatisticsCollection")), objc.RegisterName("new"))
	return statisticsCollectionAdopt(_id)
}

// StatisticsForDate returns the statistics object for the time interval that contains the provided date.
func (sc *StatisticsCollection) StatisticsForDate(date obj.Object) *Statistics {
	_r := objc.Send[objc.ID](objref.IDOf(sc), objc.RegisterName("statisticsForDate:"), objref.IDOf(date))
	return StatisticsFromID(_r)
}

// EnumerateStatisticsFromDateToDateWith enumerates the statistics objects for all the time intervals from the start date until the end date.
func (sc *StatisticsCollection) EnumerateStatisticsFromDateToDateWith(startDate obj.Object, endDate obj.Object, block func(obj.Object, *bool)) {
	objc.Send[objc.ID](objref.IDOf(sc), objc.RegisterName("enumerateStatisticsFromDate:toDate:withBlock:"), objref.IDOf(startDate), objref.IDOf(endDate), objc.NewBlock(func(_ objc.Block, _b0 objc.ID, _b1 unsafe.Pointer) { block(obj.Wrap(_b0), (*bool)(_b1)) }))
}

// Statistics returns an array of statistics objects representing the populated time intervals covered by the statistics collection query.
//
// Statistics returns the collection as a Go slice.
func (sc *StatisticsCollection) Statistics() []*Statistics {
	_arr := objc.Send[objc.ID](objref.IDOf(sc), objc.RegisterName("statistics"))
	return purego.NSArrayToSlice(_arr, func(_id objc.ID) *Statistics { return StatisticsFromID(_id) })
}

// Sources returns a set containing all the sources that had samples matched by the statistics collection query.
func (sc *StatisticsCollection) Sources() obj.Object {
	_r := objc.Send[objc.ID](objref.IDOf(sc), objc.RegisterName("sources"))
	return obj.Wrap(_r)
}
