// Code generated by go-bindings-codegen. DO NOT EDIT.

//go:build darwin

package virtualization

import (
	"github.com/deploymenttheory/go-bindings-macosplatform/bindings/runtime/purego"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/internal/objref"
	"github.com/deploymenttheory/go-bindings-macosplatform/opinionated/idiomatic/obj"
	"github.com/ebitengine/purego/objc"
)

// VirtioSoundDeviceOutputStreamConfiguration is an idiomatic wrapper over the Objective-C class VZVirtioSoundDeviceOutputStreamConfiguration.
//
// It embeds [VirtioSoundDeviceStreamConfiguration], promoting that type's methods.
//
// An object that defines a Virtio sound device output stream configuration.
type VirtioSoundDeviceOutputStreamConfiguration struct {
	VirtioSoundDeviceStreamConfiguration
}

// VirtioSoundDeviceOutputStreamConfigurationFromID adopts an existing Objective-C object as a VirtioSoundDeviceOutputStreamConfiguration
// (nil for 0), retaining it and registering a release finalizer.
func VirtioSoundDeviceOutputStreamConfigurationFromID(id objc.ID) *VirtioSoundDeviceOutputStreamConfiguration {
	if id == 0 {
		return nil
	}
	x := &VirtioSoundDeviceOutputStreamConfiguration{}
	x.Handle = objref.Wrap(purego.Retain(id))
	objref.Track(x)
	return x
}

// virtioSoundDeviceOutputStreamConfigurationAdopt wraps an Objective-C object that this code just created as a
// VirtioSoundDeviceOutputStreamConfiguration (nil for 0). The caller already owns the object's reference,
// so this does not add another; it only arranges for the object to be released
// once Go stops using it. Constructors use it.
func virtioSoundDeviceOutputStreamConfigurationAdopt(id objc.ID) *VirtioSoundDeviceOutputStreamConfiguration {
	if id == 0 {
		return nil
	}
	x := &VirtioSoundDeviceOutputStreamConfiguration{}
	x.Handle = objref.Wrap(id)
	objref.Track(x)
	return x
}

// NewVirtioSoundDeviceOutputStreamConfiguration creates a new VirtioSoundDeviceOutputStreamConfiguration.
func NewVirtioSoundDeviceOutputStreamConfiguration() *VirtioSoundDeviceOutputStreamConfiguration {
	_id := objc.Send[objc.ID](objc.ID(_class("VZVirtioSoundDeviceOutputStreamConfiguration")), objc.RegisterName("new"))
	return virtioSoundDeviceOutputStreamConfigurationAdopt(_id)
}

// WithSink an audio stream sink that defines how the host handles audio data produced by the guest.
func (x *VirtioSoundDeviceOutputStreamConfiguration) WithSink(sink AudioOutputStreamSinkProvider) *VirtioSoundDeviceOutputStreamConfiguration {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setSink:"), objref.IDOf(sink))
	return x
}

// Sink wraps the corresponding Objective-C method.
func (x *VirtioSoundDeviceOutputStreamConfiguration) Sink() *AudioOutputStreamSink {
	_r := objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("sink"))
	return AudioOutputStreamSinkFromID(_r)
}

// SetSink wraps the corresponding Objective-C method.
func (x *VirtioSoundDeviceOutputStreamConfiguration) SetSink(sink *AudioOutputStreamSink) {
	objc.Send[objc.ID](objref.IDOf(x), objc.RegisterName("setSink:"), objref.IDOf(sink))
}

// VirtioSoundDeviceOutputStreamConfigurationable is the interface implemented by [VirtioSoundDeviceOutputStreamConfiguration], for mocking and DI.
type VirtioSoundDeviceOutputStreamConfigurationable interface {
	obj.Object
	WithSink(sink AudioOutputStreamSinkProvider) *VirtioSoundDeviceOutputStreamConfiguration
	Sink() *AudioOutputStreamSink
	SetSink(sink *AudioOutputStreamSink)
}

var _ VirtioSoundDeviceOutputStreamConfigurationable = (*VirtioSoundDeviceOutputStreamConfiguration)(nil)

var _ VirtioSoundDeviceStreamConfigurationProvider = (*VirtioSoundDeviceOutputStreamConfiguration)(nil)
